sogebot/sogeBot

public/pages/viewers/list.html

fix(ui): correctly show subgifts in viewers list

---

src/bot/tmi.js

feat(tmi): add userId to log

---

package.json

build: 9.4.0-SNAPSHOT

---

dist/js/components.js
locales/cs/ui/core/tmi.json
locales/en/ui/core/tmi.json
public/pages/core.html
src/bot/api.js
src/bot/commons.ts
src/bot/data/globalIgnoreList.ts
src/bot/message.js
src/bot/systems/top.ts
src/bot/tmi.js
src/bot/users.js
test/tests/message/random.js
test/tests/tmi/ignore.js

feat(tmi): add global ignorelist and ignorelist by id

---

src/bot/api.js
src/bot/panel.js
src/panel/others/changegamedlg.vue

fix(ui): fix behavior on game/title/tags dialog

---

src/bot/integrations/donationalerts.ts
src/bot/integrations/streamlabs.ts
src/bot/tmi.js
src/bot/users.js
tools/migrate.js

fix(users): save bits/tips amount as number type

---

src/bot/oauth.ts

fix(oauth): typecheck tokens to not save null values

---

src/bot/oauth.ts

fix(oauth): cleanup correct scopes variable

---

src/bot/oauth.ts

fix(oauth): validate oauth after refresh

---

package.json

build: 9.5.0-SNAPSHOT

---

src/bot/tmi.js

fix(tmi): skip counting messages on offline stream

---

src/bot/watchers.ts

fix(watchers): force lower cased system name

---

src/bot/decorators.ts
src/bot/oauth.ts
src/bot/watchers.ts

refactor(decorators): add readonly settings option

---

src/bot/customvariables.js

fix(cvars): save to history on widget change

---

src/panel/others/changegamedlg.vue

fix(ui): remove delete button from current title

---

src/bot/_interface.ts
src/bot/systems/moderation.ts
test/tests/moderation/whitelist.js

fix(moderation): properly moderate changed !songrequest command

---

locales/cs.json
locales/en.json
src/bot/systems/userinfo.ts

fix(userinfo): update incorrect locale variable

---

src/bot/events.ts
test/tests/moderation/whitelist.js

fix(events): run fireRunCommand correctly with user

---

src/bot/api.js

fix(api): make title and game force more aggresive

---

package.json

build: 9.4.1

---

Makefile

fix(build): add fonts.json to zipfile

---

locales/cs.json
locales/en.json
src/bot/events.ts
src/bot/tmi.js

fix(events): add proper tier for sub events where applicable

---

d.ts/index.d.ts
src/bot/_interface.ts
src/bot/decorators.ts
src/bot/decorators/on.ts
src/bot/integrations/donationalerts.ts
src/bot/integrations/phillipsHue.ts
src/bot/integrations/spotify.ts
src/bot/integrations/streamlabs.ts
src/bot/integrations/twitter.ts

before enabled variable is accounted
Fixes #2408

feat(interface): add onStartup to ensure everything is loaded

---

src/bot/panel.js
src/panel/others/changegamedlg.vue

fix(ui): sort games by time of use

---

src/bot/api.js

fix(api): set API status on getCurrentStreamData

---

src/panel/others/checklist.vue
tools/migrate.js

fix(checklist): use proper checklist key for top panel ui

---

package.json

build: 9.4.2

---

tools/changelog.js

refactor(changelog): add fixes string to changelog list

---

src/bot/systems/keywords.ts

fix(keywords): use full sender object to parse

---

npm-shrinkwrap.json
package.json
webpack.config.js
yarn.lock

build(webpack): remove cache-loader

---

src/panel/views/settings/interface.vue

fix(ui): process settings category only if exists

---

locales/cs.json
locales/en.json
public/pages/viewers/list.html
src/panel/components/loading.vue

Added locales 'this-may-take-a-while'
Fixes #2435
[skip-tests]

fix(ui): update loading spinner for viewers page

---

public/index.html
src/panel/widgets/components/ytplayer.vue

feat(ytplayer): add 'skip and remove from playlist'

---

package.json
webpack.config.js

build(webpack): add watcher script for webpack

---

src/panel/views/settings/interface.vue

fix(ui): add scrollbar when top stats are stickied

---

public/index.html
src/panel/widgets/components/ytplayer.vue

fix(ui): detach only dropdown-detach classes

---

webpack.config.js

build(webpack): set optimizations

---

public/index.html

fix(ui): skip dropdown-detach if there is nothing to detach

---

src/panel/widgets/components/ytplayer.vue

fix(ui): detach only ytplayer dropdown

---

src/panel/views/settings/interface.vue

fix(ui): remove interval on settings destroy

---

locales/cs/ui.registry.customvariables.json
locales/en/ui.registry.customvariables.json
src/bot/customvariables.js
src/bot/panel.js
src/panel/views/registries/custom-variables/custom-variables-edit.vue

URL must be generated through UI
Requested by https://ideas.sogebot.xyz/posts/145/url-call-to-change-variable

feat(customvariables): get and post URLs for custom variables

---

src/panel/views/registries/custom-variables/custom-variables-edit.vue

refactor(customvariables): add missing changes pending info

---

src/panel/views/registries/custom-variables/custom-variables-edit.vue

fix(customvariables): buttons for urls will have proper width

---

src/panel/views/registries/custom-variables/custom-variables-edit.vue

refactor(cvars): add alert on route change when pending changes

---

locales/en/ui.commons.json

fix(locales): set correct translation for reset

---

src/panel/views/settings/interface.vue

fix(ui): hide bottom overflow for systems list

---

Makefile
package.json
src/bot/_interface.ts
src/bot/decorators.ts
src/bot/permissions.ts
src/bot/systems/points.ts
src/bot/watchers.ts
src/panel/views/settings/components/interface/textarea-from-array.vue
src/panel/views/settings/interface.vue

feat(points): add permission based settings

---

src/panel/views/settings/interface.vue

fix(ui): permbased settings should not blur on change

---

src/bot/_interface.ts

fix(interface): return correct values if set_default_values

---

src/bot/systems/points.ts

fix(points): use permbased values instead of defaults

---

src/bot/_interface.ts

fix(interface): load 0 or false values from db correctly

---

package.json

build: 9.6.0-SNAPSHOT

---

locales/en.json

fix(locale): set correct locale for this-may-take-a-while

---

d.ts/index.d.ts
src/bot/_interface.ts
src/bot/decorators.ts

fix(permissions): set correct default permissions

---

d.ts/index.d.ts
locales/en.json
package.json
src/bot/_interface.ts
src/bot/decorators.ts
tools/changelog.js

build: 9.5.1

---

src/bot/api.js
src/bot/cache.js

fix(api): use getChannelDataOldAPI offline-only

---

tools/migrate.js

fix(migrate): simplify db versions

---

locales/cs/ui.registry.customvariables.json
locales/en/ui.registry.customvariables.json
src/bot/customvariables.js
src/panel/views/registries/custom-variables/custom-variables-edit.vue

feat(cvars): add response toggle for POST variable change

---

src/overlay/components/alerts.vue
src/overlay/components/carousel.vue
src/overlay/components/clips.vue
src/overlay/components/emotes.vue
src/overlay/components/goals.vue
src/overlay/components/polls.vue
src/overlay/components/stats.vue
src/overlay/components/text.vue
src/panel/widgets/components/bets.vue
src/panel/widgets/components/chat.vue
src/panel/widgets/components/commercial.vue
src/panel/widgets/components/eventlist.vue
src/panel/widgets/components/queue.vue
src/panel/widgets/components/ytplayer.vue

fix(ui): properly destroy intervals

---

package.json

build: 9.7.0-SNAPSHOT

---

src/bot/tmi.js

fix(tmi): fire correct raid event

---

locales/cs/ui/integrations/spotify.json
locales/en/ui/integrations/spotify.json
src/bot/integrations/spotify.ts

feat(spotify): show whole artists of song

---

.eslintrc.json
src/bot/workers.ts

fix(workers): set empty array for spread

---

src/bot/systems/keywords.ts
test/tests/keywords/basic_workflow.js

fix(keywords): handle correctly unicode keywords

---

src/bot/systems/keywords.ts
test/tests/keywords/basic_workflow.js

fix(keywords): send full sender object

---

src/bot/systems/keywords.ts
test/tests/keywords/basic_workflow.js

fix(keywords): extend regexp with punctuations

---

public/popout.html

fix(popout): inherit selected theme

---

public/index.html
scss/custom.scss
src/panel/others/checklist.vue
src/panel/others/quickStatsApp.vue

fix(panel): update visuals on smaller screens

---

src/bot/systems/points.ts

fix(points): add parenthesis to point calculation

---

src/overlay/views/alertsRegistry.vue

fix(alerts): merge classes if in ref

---

src/overlay/views/alertsRegistry.vue

fix(alerts):  properly load css styles for alerts

---

src/bot/data/templates/alerts-with-message.txt
src/bot/data/templates/alerts.txt

fix(alerts): update template with correct variable name

---

src/overlay/views/alertsRegistry.vue

…ced mode
Fixes #2524
[skip-tests]

fix(alerts): highlight messageTemplate variables in advanced mode

---

src/overlay/index.ts
src/overlay/views/goals.vue

fix(goals): set correct goals route

---

src/overlay/views/alertsRegistry.vue

fix(alerts): use proper lodash get

---

src/panel/views/registries/alerts/alerts-edit.vue

fix(alerts): load correct alert group

---

src/panel/views/registries/alerts/alerts-edit.vue

fix(alerts): set proper col classes to not break codemirror

---

src/panel/components/media.vue

fix(alerts): retry setting volume if ref is not mounted yet

---

src/overlay/views/alertsRegistry.vue

fix(alerts): load responsiveVoice key without refresh

---

src/bot/systems/points.ts
src/bot/users.js
tools/migrate.js

fix(points): add points using chat time

---

locales/cs/ui/systems/userinfo.json
locales/en/ui/systems/userinfo.json
src/bot/systems/userinfo.ts

feat(userinfo): add configurable lastseen timestamp format

---

src/panel/views/registries/alerts/components/form-cheers.vue
src/panel/views/registries/alerts/components/form-follow.vue
src/panel/views/registries/alerts/components/form-resubs.vue

fix(alerts): remove incorrect resub validations

---

src/bot/systems/points.ts
src/bot/users.js
tools/migrate.js

fix(points): count online/offline points independently

---

src/bot/users.js

fix(users): update chat time offline/online independently

---

locales/cs/ui.systems.songs.json
locales/en/ui.systems.songs.json
src/bot/systems/songs.ts

Idea https://ideas.sogebot.xyz/posts/149/provide-own-youtube-api-key

feat(songs): set own YouTube API Key

---

src/panel/views/settings/interface.vue

fix(ui): remove category from permission based setting

---

src/bot/systems/userinfo.ts

Idea https://ideas.sogebot.xyz/posts/119

feat(userinfo): add $role to !me

---

public/oauth.html
src/login/views/login.vue

fix(auth): use b64 for state encoding

---

src/login/views/login.vue

fix(login): add login button to popout error

---

src/panel/views/settings/interface.vue

fix(ui): null check also ui object to include even if value is null

---

src/panel/others/user.js

fix(ui): wait until main is loaded before loggedUser use

---

locales/cs/ui/registry/alerts.json
locales/en/ui/registry/alerts.json
src/panel/views/registries/alerts/components/form-follow.vue

feat(ui): add set defaults button for code

---

package.json

build: 9.8.0-SNAPSHOT

---

src/panel/views/managers/keywords/keywords-list.vue
src/panel/views/managers/quotes/quotes-list.vue
src/panel/views/registries/alerts/alerts-list.vue
src/panel/views/registries/custom-variables/custom-variables-edit.vue
src/panel/views/registries/custom-variables/custom-variables-list.vue

refactor(ui): update slot syntax for b-table

---

src/overlay/views/alertsRegistry.vue

fix(alerts): propagate messageText with actual values

---

package.json

build: 9.7.1

---

package.json

build: 9.7.2

---

src/bot/panel.js
src/panel/widgets/dashboard.js
src/panel/widgets/dashboard.vue
tools/database.js
tools/migrate.js
tsconfig.json

refactor(dashboard): use uuid id instead of _id

---

d.ts/index.d.ts
src/bot/systems/polls.ts
src/panel/views/managers/polls.vue
tools/database.js
tools/migrate.js

refactor(polls): use uuid id instead of _id

---

public/pages/timers/edit.html
public/pages/timers/list.html
src/bot/systems/timers.ts
tools/database.js
tools/migrate.js

refactor(timers): use uuid id instead of _id

---

public/pages/customcommands/edit.html
public/pages/customcommands/list.html
src/bot/systems/customCommands.ts
test/tests/commands/run.js
tools/database.js
tools/migrate.js

refactor(customcommands): use uuid id instead of _id

---

src/bot/customvariables.js
src/bot/databases/nedb.js
src/bot/systems/customCommands.ts
src/bot/systems/quotes.ts
src/bot/systems/timers.ts
src/panel/views/registries/custom-variables/custom-variables-edit.vue
src/panel/views/registries/custom-variables/custom-variables-list.vue
src/panel/widgets/components/customvariables.vue
src/panel/widgets/dashboard.vue
test/tests/commands/count_filter.js
test/tests/commands/run.js
test/tests/polls/bits.js
test/tests/polls/normal.js
test/tests/polls/tips.js
test/tests/quotes/add.js
test/tests/quotes/remove.js
test/tests/timers/add.js
test/tests/timers/list.js
test/tests/timers/toggle.js
test/tests/timers/unset.js
tools/database.js
tools/migrate.js

refactor(customvariables): use uuid id instead of _id

---

tools/database.js

refactor(tools): remove relationships

---

public/index.html
scss/custom.scss
src/panel/others/checklist.vue
src/panel/others/quickStatsApp.vue

feat(ui): update menu, stats to be more mobile-friendly

---

src/bot/permissions.ts
src/bot/registries/alerts.ts

fix: collection indexing

---

src/overlay/views/alertsRegistry.vue

fix(alerts): message font setting to be not overriden by font settings

---

src/panel/views/managers/commands/commands-edit.vue

fix(commands): resolve promise if responses are empty

---

src/panel/views/managers/commands/commands-list.vue

fix(commands): align buttons to right

---

src/panel/views/managers/commands/commands-edit.vue

fix(commands): emit set to save correct response data

---

src/bot/systems/customCommands.ts
test/tests/commands/run.js

fix(commands): $_ variables to be not ignored with param

---

src/panel/others/quickStatsApp.vue

fix(stats): set unique ref

---

src/panel/views/registries/custom-variables/custom-variables-edit.vue

fix(commands): remove type from readonly input

---

tools/release.js

refactor(tools): skip tests on doc creation

---

package.json

build: 9.8.0

---

Makefile
npm-shrinkwrap.json

refactor(make): remove auto shrinkwrap

---

package.json

build: 9.9.0-SNAPSHOT

---

src/bot/permissions.ts

fix(permissions): warn only once about permission in logs

---

src/bot/general.ts
src/bot/logging.js

fix(debug): load missing debug information on !_debug

---

src/bot/message.js

fix(message): sort alias, commands lists

---

src/bot/databases/mongodb.js

fix(mongodb): add useUnifiedTopology

---

src/bot/webhooks.js

fix(webhooks): trigger stream start event on streamId change

---

src/bot/systems/customCommands.ts
test/tests/message/touser.js

fix(commands): include $touser to allowed params

---

src/bot/customvariables.js
src/bot/events.ts
src/bot/message.js

fix(events): use custom variable registry for inc/dec event

---

Dockerfile
Makefile
docker.sh
docs/_master/install-and-upgrade.md
tools/release.js

build(docker): add docker release building

---

.github/workflows/dockerimage.yml

build(actions): add docker nightly worfklow

---

src/bot/_interface.ts
src/bot/api.js
src/bot/games/duel.ts
src/bot/games/fightme.ts
src/bot/games/heist.ts
src/bot/games/wheelOfFortune.ts
src/bot/overlays/eventlist.ts
src/bot/permissions.ts
src/bot/systems/alias.ts
src/bot/systems/cooldown.ts
src/bot/systems/highlights.ts
src/bot/systems/moderation.ts
src/bot/systems/price.ts
src/bot/systems/queue.ts
src/bot/systems/quotes.ts
src/bot/systems/raffles.ts
src/bot/systems/ranks.ts
src/bot/systems/songs.ts
src/bot/widgets/cmdboard.ts
test/tests/games/duel.js

refactor(db): add missing indexes

---

.github/workflows/dockerimage.yml

build(docker): update docker action to publish

---

.github/workflows/dockerimage.yml

build(docker): lowercase repository name

---

.github/workflows/dockerimage.yml

build(docker): use another docker action to push to github

---

.github/workflows/dockerimage.yml

build(docker): add image name

---

.github/workflows/dockerimage.yml

build(docker): missing checkout

---

locales/cs.json
locales/en.json
src/panel/helpers/getListOf.ts
src/panel/index.ts
src/panel/views/managers/commands/commands-list.vue
src/panel/views/managers/events/list.vue
src/panel/views/managers/hltb.vue
src/panel/views/managers/keywords/keywords-list.vue
src/panel/views/managers/polls.vue
src/panel/views/managers/quotes/quotes-list.vue
src/panel/views/settings/interface.vue

This doesn't have all systems, only ones ported to Vue
Fixes #2636

feat(ui): error alert on manage if system disabled

---

.github/workflows/dockerimage-release.yml
.github/workflows/dockerimage.yml

build(docker): change tag name to nightly, remove from latest

---

.github/workflows/dockerimage-release.yml
.github/workflows/dockerimage.yml

build(docker): have proper version tags

---

.github/workflows/dockerimage-release.yml
.github/workflows/dockerimage.yml
docs/_master/install-and-upgrade.md

build(docker): set latest tag and update docs

---

docs/_master/install-and-upgrade.md

docs(docker): add docker pull information

---

docs/_master/install-and-upgrade.md

docs(docker): remove randomized token

---

public/index.html
src/panel/index.ts
src/panel/views/dashboard/stub.vue

fix(ui): correct link to redirect to dashboard

---

src/bot/commons.ts
src/bot/systems/songs.ts
src/panel/widgets/components/ytplayer.vue

fix(songs): set bot username for songs from playlist

---

src/panel/views/settings/components/interface/wof-responses.vue

fix(ui): static keys for wof options and responses

---

src/panel/views/managers/events/edit.vue

fix(events): sync value on textarea

---

package.json

build: 9.9.0

---

package.json

build: 9.10.0-SNAPSHOT

---

.github/workflows/dockerimage-release.yml

build(docker): add on release hook

---

public/index.html

fix(ui): check if dropdown needs to be detached

---

tools/release-master.sh
tools/release.js

build(tools): simplify release tool

---

src/panel/others/checklist.vue

fix(checklist): set correct link

---

src/panel/views/settings/interface.vue

fix(ui): return viewers values if missing

---

public/pages/registry/gallery/list.html
src/bot/overlays/gallery.ts
src/bot/panel.js
tools/migrate.js

refactor(gallery): use uuid instead of _id

---

src/panel/views/settings/components/permissions/list.vue

fix(permissions): remove dragging from viewers permission

---

src/bot/systems/keywords.ts
test/tests/keywords/list.js

test(keywords): split list test to make it more robust

---

scss/custom.scss

fix(ui): add z-index to bottom bar

---

src/panel/widgets/components/ytplayer.vue

fix(ytplayer): start request if autoplay is enabled

---

.vscode/settings.json
d.ts/registry.d.ts
package.json
src/bot/databases/mongodb.js
src/bot/databases/nedb.js
src/bot/panel.js
src/bot/registries/alerts.ts
src/overlay/views/alertsRegistry.vue
src/panel/components/loading.vue
src/panel/components/media.vue
src/panel/views/registries/alerts/alerts-edit.vue
src/panel/views/registries/alerts/components/form-cheers.vue
src/panel/views/registries/alerts/components/form-follow.vue
src/panel/views/registries/alerts/components/form-hosts.vue
src/panel/views/registries/alerts/components/form-resubs.vue
tools/migrate.js

refactor(alerts): split media from main collection

---

src/bot/panel.js
src/panel/index.html
src/panel/index.ts
src/panel/others/footer.ts
src/panel/others/footer.vue

refactor(ui): move footer to vue

---

src/bot/systems/moderation.ts

fix(moderation): set correct translation string

---

src/panel/views/settings/components/permissions/edit.vue
src/panel/views/settings/components/permissions/list.vue
src/panel/views/settings/interface.vue

refactor(ui): fix ui

---

locales/cs/ui.menu.json
locales/cs/ui/integrations/streamelements.json
locales/en/ui.menu.json
locales/en/ui/integrations/streamelements.json
src/bot/integrations/streamelements.ts

I just started. I'm waiting for fix that issue https://github.com/sogehige/sogeBot/issues/2699 for continue developing this integration.

feat(integrations): add streamelements integration

---

scss/custom.scss

fix(menu): force absolute position

---

locales/cs/ui.menu.json
locales/cs/ui/integrations/qiwi.json
locales/en/ui.menu.json
locales/en/ui/integrations/qiwi.json
src/bot/integrations/qiwi.ts

feat(integrations): add qiwi donate integration

---

src/panel/views/settings/interface.vue

fix(ui): show status in settings

---

webpack.config.js

build(webpack): set proper overlay chunk

---

.gitignore
src/panel/popout.html
webpack.config.js

fix(popout): use proper chunks for popout

---

package.json

chore(dependencies): remove cross-var

---

src/panel/views/registries/alerts/alerts-list.vue

feat(alerts): add test button to list

---

src/login/index.html
src/overlay/index.html
webpack.config.js

build(webpack): remove original entries

---

src/panel/views/managers/alias/alias-list.vue

fix(ui): set unique permission keys

---

src/bot/customvariables.js
src/bot/systems/customCommands.ts
test/helpers/messages.js
test/tests/commands/run.js

fix(commands): response should be correctly sent

---

package.json

build(webpack): exclude css, vue from treeshake

---

src/bot/decorators.ts

feat(decorators): shared to be able to save in db

---

tools/rerunTests.js

test(rerun): stdout/stderr for rerun

---

src/panel/views/settings/components/interface/global-ignorelist-exclude.vue

fix(ui): import proper lodash library

---

src/bot/overlays/emotes.ts

fix(emotes): simplified 404 error on bttv

---

public/pages/timers/edit.html
src/bot/systems/timers.ts

fix(timers): use original id during edit

---

src/bot/systems/keywords.ts
test/tests/keywords/list.js

fix(keywords): send list in proper order

---

tools/rerunTests.js

test(rerun): use process.stdout to remove newline

---

src/bot/api.ts

refactor(api): trigger stop stream only on isStreamOnline change

---

src/bot/databases/mongodb.js
src/bot/databases/nedb.js
src/bot/integrations/donationalerts.ts
src/bot/integrations/qiwi.ts
src/bot/integrations/streamlabs.ts
src/bot/systems/top.ts
src/bot/users.js
test/tests/permissions/check.js
test/tests/top/bits.js
test/tests/top/tips.js
tools/migrate.js

fix(top): use proper db ordering

---

test/tests/raffles/pick.js

test(raffle): use userId, not username

---

d.ts/registry.d.ts
locales/cs/ui/registry/alerts.json
locales/en/ui/registry/alerts.json
src/overlay/views/alertsRegistry.vue
src/panel/views/registries/alerts/alerts-edit.vue
src/panel/views/registries/alerts/components/form-cheers.vue
src/panel/views/registries/alerts/components/form-follow.vue
src/panel/views/registries/alerts/components/form-hosts.vue
src/panel/views/registries/alerts/components/form-resubs.vue
src/panel/views/registries/alerts/components/tts.vue
tools/migrate.js

feat(alerts): add toggle to keep alert visible during TTS

---

tools/migrate.js

fix(migrate): update by id not uuid

---

src/bot/message.js
src/bot/panel.js
src/bot/systems/songs.ts
src/bot/workers.ts
src/panel/widgets/components/ytplayer.vue

feat(songs): check isPlaying per socket

---

src/bot/api.ts
src/bot/systems/highlights.ts
src/bot/webhooks.js

fix(api): start stream properly with webhooks

---

src/panel/views/registries/goalsList.vue

fix(goals): use proper lodash-es functions

---

d.ts/index.d.ts
src/bot/cluster.js
src/bot/main.js
src/bot/twitch.ts
src/bot/webhooks.ts

refactor(twitch): move to typescript

---

src/bot/cluster.js
src/bot/main.js
src/bot/ui.ts
src/bot/users.ts
test/tests/message/random.js

refactor(imports): fix ui, users imports

---

src/bot/databases/mongodb.js
src/bot/users.ts

fix(users): don't remove onlien users on watch time update

---

src/bot/systems/commercial.ts

fix(commercial): fix error catch to use io if usable

---

src/panel/others/checklist.vue
src/panel/views/managers/commands/commands-list.vue
src/panel/views/managers/events/edit.vue
src/panel/views/managers/hltb.vue
src/panel/views/managers/polls.vue
src/panel/views/settings/components/interface/credits-custom-texts.vue
src/panel/views/settings/components/interface/credits-social.vue
src/panel/views/settings/components/permissions/userslist.vue
src/panel/widgets/components/bets.vue
src/panel/widgets/components/chat.vue
src/panel/widgets/components/customvariables.vue
src/panel/widgets/components/eventlist.vue
src/panel/widgets/components/queue.vue
src/panel/widgets/components/raffles.vue
src/panel/widgets/components/soundboard.vue
src/panel/widgets/components/spotify.vue
src/panel/widgets/dashboard.js
src/panel/widgets/dashboard.vue

refactor(ui): remove implicit lodash use

---

public/oauth/spotify.html

fix(spotify): redirect to spotify integration

---

src/panel/views/managers/events/edit.vue

fix(events): show right arrow on edit only

---

src/panel/others/quickStatsApp.vue

fix(stats): hide avg stat change if hidden

---

src/panel/others/quickStatsApp.vue

fix(stats): game column should have correct width on mobile

---

src/panel/widgets/components/ytplayer.vue

fix(ytplayer): add info log on song retry about adblockers

---

src/overlay/views/alerts.vue

fix(alerts): skip alert if something went wrong

---

.npmrc
Makefile
docs/_master/install-and-upgrade.md

build(make): use npm ci to install deps

---

npm-shrinkwrap.json

build(shrinkwrap): shrinkwrap update

---

Dockerfile

build(dockerfile): fix config.example.json path

---

.npmrc
Makefile
docs/_master/install-and-upgrade.md

This reverts commit dd52fdd9ca7a585aa7bddb561edd8427b120c265.

build(make): revert use npm ci to install deps (#2796)

---

CONTRIBUTING.md
docs/README.md

docs: remove standardjs information

---

test/helpers/messages.js
test/tests/commands/run.js
test/tests/message/cvars.js

test(messages): remove chatOut reset on isSent

---

src/panel/index.ts
src/panel/widgets/components/eventlist.vue

refactor(ui): fix eventlist translate

---

src/bot/integrations/donationalerts.ts
src/bot/integrations/qiwi.ts
src/bot/integrations/streamelements.ts
src/bot/integrations/streamlabs.ts
test/tests/events/tip.js

fix(tips): add correctly to currentTips stats new tip

---

src/overlay/views/alertsRegistry.vue
src/panel/views/registries/alerts/components/tts.vue

fix(tts): volume should be number

---

src/panel/views/managers/viewers/viewers-edit.vue

fix(ui): make orderBy available in template

---

src/bot/panel.js

refactor(panel): remove unused page paths

---

.github/workflows/tests.yml

build(tests): run tests on any PR

---

src/login/views/login.vue

fix(login): assume ? as part of popout url

---

src/panel/helpers/socket.ts

fix(public): remove redutant console.log at socket getConfiguration

---

src/panel/widgets/components/commercial.vue

refactor(commercial): put tags into single attributes

---

src/panel/components/statsbar/statsbar.vue

refactor(statsbar): show correct diff numbers

---

src/panel/widgets/components/eventlist.vue
src/panel/widgets/components/soundboard.vue

refactor(widgets): remove old jquery code

---

src/panel/views/dashboard/dashboard.vue

refactor(dashboard): show only selected dashboard

---

d.ts/index.d.ts
src/bot/registries/text.ts
src/overlay/views/text.vue
src/panel/views/registries/text-overlay/text-overlay-edit.vue
src/panel/views/registries/text-overlay/text-overlay-list.vue
tools/migrate.js

fix(overlays): remove redundant link in settings

---

src/panel/views/dashboard/dashboard.vue

refactor(dashboard): set correct height of widget on mobile

---

src/bot/webhooks.ts

fix(webhooks): start stream everytime when id is changed

---

scss/custom.scss

fix(ui): update eventlist css to be more compact

---

scss/custom.scss
src/panel/index.ts

fix(ui): statsbar should have correct mobile padding

---

scss/custom.scss
src/panel/components/statsbar/statsbar.vue
src/panel/index.ts

fix(statsbar): diff colors should be correct

---

src/panel/components/statsbar/statsbar.vue

fix(statsbar): treat watchedTime as timestamp

---

src/bot/data/config.example.json

fix(config): remove comma from example config

---

.github/workflows/tests.yml
Makefile
package.json

build(tests): add jsonlint to test json files

---

src/login/views/login.vue

fix(login): add login button to must+be+caster error

---

src/bot/panel.js
src/bot/socket.ts
src/bot/ui.ts
src/login/index.html
src/overlay/index.html
src/panel/helpers/isUserLoggedIn.ts
src/panel/helpers/socket.ts
src/panel/index.ts
src/panel/popout.ts

fix(ui): split public and private configuration

---

src/panel/helpers/isUserLoggedIn.ts

fix(ui): return correct isUserCaster() value

---

src/bot/ui.ts

fix(ui): wait or webhooks availability before subscribe

---

docs/_master/_sidebar.md
docs/_master/howto/connection-to-socket.md
locales/cs/ui/core/socket.json
locales/en/ui/core/socket.json
package.json
src/bot/socket.ts
src/bot/workers.ts
src/panel/views/settings/components/interface/uuid-generator.vue
src/panel/views/settings/interface.vue

feat(socket): add socketToken generator

---

.vscode/settings.json
Makefile
npm-shrinkwrap.json
package.json
src/bot/systems/moderation.ts

build(typescript): set version to 3.7.1-rc

---

.github/workflows/tests.yml
Dockerfile

build(docker): set node version to 13

---

d.ts/registry.d.ts
locales/cs/ui/registry/alerts.json
locales/en/ui/registry/alerts.json
package.json
src/bot/registries/alerts.ts
src/overlay/views/alertsRegistry.vue
src/panel/views/registries/alerts/alerts-edit.vue
src/panel/views/registries/alerts/components/tts.vue
tools/migrate.js

When enabled, urls will be skipped when TTS is speaking
Fixes #2827

feat(alerts): add skipUrls for TTS

---

package.json

build: 9.10.0

---

package.json

build: 9.11.0-SNAPSHOT

---

src/bot/permissions.ts

fix(permissions): if user doesn't exist, assume it is only viewer

---

docs/_master/tools/database.md
src/bot/api.ts
src/bot/databases/mongodb.js
src/bot/databases/nedb.js
src/bot/tmi.ts
tools/migrate.js

refactor(heap): remove cache.(hosts|raids) and fix online users

---

src/panel/components/statsbar/statsbar.vue

fix(statsbar): remove redundant console.log

---

src/panel/views/dashboard/dashboard.vue

fix(dashboard): add missing buttons for add, remove dashboards

---

src/panel/views/managers/viewers/viewers-edit.vue

fix(ui): properly show tips/bits editation dropdowns

---

src/bot/_interface.ts
src/login/views/login.vue
src/panel/helpers/isUserLoggedIn.ts
src/panel/index.ts
src/panel/popout.ts

fix(ui): error if update endpoint access without admin

---

src/bot/socket.ts

So we don't lose auth on crash etc.

fix(socket): make socket persistent

---

package.json

build: 9.10.1

---

Makefile

build(makefile): config.example.json copy to /

---

Makefile

build(makefile): remove dist from zip

---

src/bot/_interface.ts
src/overlay/index.ts

fix(overlays): socket get endpoints should be public

---

src/bot/oauth.ts

fix(oauth): show error from generator

---

src/panel/views/settings/components/interface/command-input-with-permission.vue

fix(ui): show command permissions dropdown in settings

---

src/bot/_interface.ts
src/bot/cluster.js
src/bot/decorators.ts
src/bot/games/gamble.ts
src/bot/integrations/donationalerts.ts
src/bot/integrations/phillipsHue.ts
src/bot/integrations/spotify.ts
src/bot/message.js
src/bot/systems/cooldown.ts
src/bot/systems/customCommands.ts
src/bot/systems/highlights.ts
src/bot/systems/moderation.ts
src/bot/systems/points.ts
src/bot/systems/raffles.ts
src/bot/systems/top.ts
src/bot/systems/userinfo.ts

fix(cluster): load socket settings on cluster

---

package.json

build: 9.10.2

---

src/bot/overlays/emotes.ts

fix(emotes): simplify ffz 404 error

---

src/bot/api.ts
src/bot/databases/database.js
src/bot/microservices/getChannelChattersUnofficialAPI.ts
src/bot/widgets/joinpart.ts
src/panel/widgets/components/join.vue
src/panel/widgets/components/part.vue

feat(threads): move getChannelChattersUnofficialAPI to own thread

---

src/bot/api.ts

refactor(api): revert getChannelChattersUnofficialAPI interval time

---

.github/workflows/tests.yml
CONTRIBUTING.md

build(tests): skip tests when [skip-tests] in PR

---

src/bot/systems/userinfo.ts
src/panel/views/settings/components/interface/sortable-list.vue

fix(ui): use correct eye icons

---

src/panel/views/managers/viewers/viewers-edit.vue

fix(ui): center misaligned inputs

---

src/bot/_interface.ts
src/bot/panel.js
src/panel/views/settings/interface.vue

fix(interface): force env DISABLE settings

---

src/bot/api.ts

fix(api): use from_id and not rely id from db

---

src/bot/api.ts

fix(api): return response only if defined

---

src/bot/systems/customCommands.ts

fix(customCommands): send messages slower to keep order

---

src/bot/tmi.ts

fix(tmi): set correct if condition

---

src/panel/views/registries/alerts/components/tts.vue

fix(ui): volume TTS step by 1%

---

src/bot/databases/interface.js
src/bot/databases/mongodb.js
src/bot/databases/nedb.js
tools/migrate.js

And delet removeIndex from bot start
Fixes #2933

refactor(migrate): remove duplicated users if needed

---

src/bot/socket.ts

fix(sockets): check auth only if socket list is loaded

---

src/overlay/views/stats.vue

fix(stats): show 0 if stream is offline

---

package.json
tools/runTests.js

refactor(tests): rerun of tests should not return false positive

---

.github/workflows/tests.yml
test/tests/permissions/check.js

test(only): add test for describe.only

---

src/panel/views/settings/components/interface/wof-responses.vue

fix(wof): properly save responses

---

package.json

build: 10.0.0-SNAPSHOT

---

.gitignore
src/bot/api.ts
src/bot/currency.ts
src/bot/translate.js

refactor(flow): remove redundant flow comments

---

tools/database.js

refactor(tools): fix responses migration

---

.gitignore

build(gitignore): add db file and ormconfig

---

tools/database.js

refactor(tools): remove console.log

---

tools/database.js

refactor(tools): fix importing unusual users and alert media

---

tools/database.js

refactor(tools): fix renamed commands migration

---

src/bot/data/ormconfig.sqlite.json
src/bot/database/entity/alias.ts
src/bot/database/entity/eventList.ts
src/bot/database/entity/twitch.ts
src/bot/database/entity/user.ts
src/bot/database/migration/mysql/1573940087256-valuesJsonToText.ts
src/bot/database/migration/mysql/1573940742362-aliasCommandText.ts
src/bot/database/migration/mysql/1573942464821-tipsAndBitsMessagesToText.ts
src/bot/database/migration/mysql/1573943514152-media_longtext.ts
src/bot/database/migration/postgres/1573940087256-valuesJsonToText.ts
src/bot/database/migration/postgres/1573940742362-aliasCommandText.ts
src/bot/database/migration/postgres/1573942464821-tipsAndBitsMessagesToText.ts
src/bot/database/migration/sqlite/1573941777062-valuesJsonToText.ts
src/bot/database/migration/sqlite/1573941849651-aliasCommandText.ts
src/bot/database/migration/sqlite/1573942908160-tipsAndBitsMessagesToText.ts
src/bot/panel.js
src/bot/stats.js
src/panel/widgets/components/customvariables.vue
tools/database.js

refactor(migration): set alias command and values_json as text

---

src/bot/microservices/getChannelChattersUnofficialAPI.ts

refactor(typeorm): remove connection options from connect

---

src/bot/database/migration/postgres/1573940742362-aliasCommandText.ts
src/bot/database/migration/postgres/1573942464821-tipsAndBitsMessagesToText.ts

refactor(migration): set correct sql command for postgre

---

src/bot/database/entity/alias.ts
src/bot/database/migration/mysql/1573940742362-aliasCommandText.ts
src/bot/database/migration/postgres/1573940742362-aliasCommandText.ts
src/bot/database/migration/sqlite/1573941849651-aliasCommandText.ts

refactor(migration): remove index from alias command

---

src/bot/_interface.ts

refactor(interface): persist enable/disable settings

---

src/bot/api.ts
src/bot/microservices/getChannelChattersUnofficialAPI.ts
src/bot/tmi.ts

refactor(online): fix incorrectly get data from db

---

src/bot/customvariables.ts

fix(customvariables): oldValue cannot be null

---

src/bot/database/entity/song.ts
src/bot/database/migration/mysql/1573998223383-multipleSongRequestWithSameVideoId.ts
src/bot/database/migration/postgres/1573998123801-multipleSongRequestWithSameVideoId.ts
src/bot/database/migration/sqlite/1573997722003-multipleSongRequestWithSameVideoId.ts
src/bot/systems/songs.ts
src/panel/widgets/components/ytplayer.vue

refactor(ytplayer): fix playing of videos

---

src/bot/general.ts

refactor(general): fix !_debug output

---

src/overlay/views/eventlist.vue

refactor(eventlist): refresh eventlist once in a while

---

src/bot/overlays/emotes.ts

fix(emotes): emotes should not be parsed on whisper

---

Dockerfile
docker.sh

build(docker): remove db settings, add dev deps

---

docker.sh

build(docker): cp ormconfig from conf dir

---

docker.sh

build(docker): remove additional space

---

docker.sh

build(docker): fix file variable

---

docs/_master/install-and-upgrade.md

docs(docker): update official docker install

---

scss/custom.scss
src/panel/components/dialog/changegamedialog.vue

fix(ui): responsive image carousel

---

src/bot/_interface.ts
src/bot/changelog.ts
src/bot/database/entity/settings.ts
src/bot/decorators.ts
src/bot/microservices/getChannelChattersUnofficialAPI.ts
src/bot/watchers.ts

refactor(entity): set settings value as simple-json

---

src/bot/_interface.ts
src/bot/changelog.ts
src/bot/database/entity/settings.ts
src/bot/decorators.ts
src/bot/microservices/getChannelChattersUnofficialAPI.ts
src/bot/watchers.ts

This reverts commit 1c40ca4cef447326b9c9527637d9e5376bfaaadf.

refactor(entity): revert set settings value as simple-json

---

src/public/views/playlist.vue

refactor(playlist): fix public playlist items

---

src/bot/_interface.ts
src/bot/database/entity/socket.ts
src/bot/database/migration/mysql/1574119687882-socketsTable.ts
src/bot/database/migration/postgres/1574119661920-socketsTable.ts
src/bot/database/migration/sqlite/1574119471769-socketsTable.ts
src/bot/socket.ts
tools/database.js

By adding await for auth process and
own socket table
Fixes #2997
Fixes #2994

fix(socket): made socket auth robust

---

src/bot/_interface.ts

refactor(interface): properly update command when not updated before

---

.github/workflows/tests.yml

build(cache): add npm cache

---

src/bot/microservices/getUserFromTwitch.ts

fix(microservice): parse token json value to get user

---

src/bot/_interface.ts
src/bot/customvariables.ts
src/bot/heapdump.ts
src/bot/helpers/permissions.ts
src/bot/main.js
src/bot/parser.ts
src/bot/permissions.ts
src/bot/systems/alias.ts
src/bot/systems/customCommands.ts
src/bot/systems/price.ts
src/bot/systems/raffles.ts
src/bot/tmi.ts

perf(various): changes to increase performance

---

src/bot/watchers.ts

So we don't check equality of same variable

fix(watcher): clone value to not work with pointer

---

src/bot/oauth.ts

fix(oauth): undefined check for error data

---

src/bot/main.js

fix(main): start heap debug on any value

---

src/bot/main.js
src/bot/overlays/emotes.ts

fix(emotes): remove dead code

---

npm-shrinkwrap.json
package.json

build(dependencies): update broken ytdl dependency

---

src/panel/views/managers/events/edit.vue

fix(events): load correct event definition

---

src/bot/api.ts
src/bot/heapdump.ts
src/bot/main.js
src/bot/systems/points.ts
src/bot/systems/userinfo.ts
src/bot/tmi.ts
src/bot/users.ts

perf(heap): various performance updates

---

src/bot/socket.ts
src/panel/views/settings/components/interface/socket-list.vue
src/panel/views/settings/interface.vue

feat(socket): add connection list to settings

---

package.json
src/bot/integrations/spotify.ts
src/oauth/spotify.html
src/oauth/spotify.ts
src/oauth/spotify.vue
webpack.config.js

fix(spotify): remove token usage on auth

---

src/bot/integrations/spotify.ts

fix(spotify): ignore commands on offline stream

---

src/bot/api.ts

fix(api): hide subscribe errors after first error

---

src/bot/cluster.ts
src/bot/data/config.example.json
src/bot/main.ts

refactor(cluster): init cluster only on main thread

---

src/bot/tmi.ts

fix(tmi): force resub message to be string

---

src/bot/decorators.ts
src/bot/oauth.ts
src/bot/permissions.ts
src/bot/translate.ts

refactor(decorators): wait for proper load from db

---

package.json

build: 10.0.0

---

package.json

build: 10.1.0-SNAPSHOT

---

src/bot/microservices/getChannelChattersUnofficialAPI.ts

fix(microservice): kill process with code 0 when done

---

package.json

build: 10.0.1

---

src/bot/parser.ts

refactor(parser): remove debug parser.time if

---

tools/database.js

fix(tools): set default permission for cvar if missing

---

tools/database.js

fix(tools): import bits/tips without message

---

src/panel/components/dialog/changegamedialog.vue

fix(ui): load dialog game/status data

---

src/bot/api.ts

fix(api): set better error message

---

src/bot/socket.ts

fix(socket): load by refreshToken correctly

---

src/bot/panel.js
src/panel/views/settings/translations.vue

fix(ui): load custom translations properly

---

src/bot/data/ormconfig.mysql.json
src/bot/data/ormconfig.postgres.json
src/bot/data/ormconfig.sqlite.json

fix(ormconfig): set correct subscriber path

---

package.json

build: 10.0.2

---

package.json

build(husky): pre-commit eslint ts files

---

src/bot/api.ts

feat(api): add getChannelFollowers per day

---

src/bot/database/migration/mysql/1575376319694-dropAliasIndex.ts
src/bot/database/migration/postgres/1575376319694-dropAliasIndex.ts
src/bot/database/migration/sqlite/1575376319694-dropAliasIndex.ts

fix(migration): drop on alias index command

---

src/bot/systems/raffles.ts

fix(raffles): announce only running raffles

---

src/bot/watchers.ts

fix(watchers): set correct path for core variables

---

package.json

build: 10.1.0

---

package.json

build: 10.2.0-SNAPSHOT

---

src/bot/panel.js

fix(panel): import tmi library

---

src/panel/widgets/components/join.vue
src/panel/widgets/components/part.vue

fix(ui): properly sort join/part list

---

docs/howto/connection-to-socket.md

docs(socket): update connection to socket

---

package.json

build: 10.1.1

---

src/bot/panel.js
src/panel/helpers/getListOf.ts
src/panel/index.ts
src/panel/widgets/components/join.vue
src/panel/widgets/components/part.vue

fix(ui): default empty list in join/part widget

---

src/overlay/index.ts
src/panel/index.ts
src/panel/popout.ts
src/public/index.ts

build(moment): remove any type

---

package.json
src/panel/views/managers/viewers/viewers-edit.vue

fix(ui): use vue-flatpickr for viewer datepick

---

package.json

build: 10.1.2

---

Dockerfile

build(docker): bump node version to 13.3.0

---

Dockerfile

build(docker): install autoconf

---

Dockerfile

build(docker): install automake

---

Dockerfile

build(docker): install zlib, zlib-dev

---

Dockerfile

build(docker): install nasm, libtool

---

Makefile
d.ts/filetypes.d.ts
d.ts/global.d.ts
d.ts/index.d.ts
d.ts/twitchjs.d.ts
d.ts/users.d.ts
npm-shrinkwrap.json
package.json
patches/twitch-js-types.patch
src/bot/cluster.ts
src/bot/commons.ts
src/bot/events.ts
src/bot/oauth.ts
src/bot/overlays/emotes.ts
src/bot/parser.ts
src/bot/systems/commercial.ts
src/bot/systems/polls.ts
src/bot/tmi.ts
tsconfig.json

chore(twitch-js): bump to 2.0.0-beta.33

---

src/bot/games/duel.ts
src/bot/games/fightme.ts
src/bot/games/gamble.ts
src/bot/games/heist.ts
src/bot/games/roulette.ts
src/bot/main.ts
src/bot/systems/bets.ts
src/bot/systems/points.ts
src/bot/systems/price.ts
src/bot/systems/raffles.ts
test/tests/games/roulette.js

Fixes https://community.sogebot.xyz/t/seppuku-and-roulette-points-can-be-negated/36

fix(points): force minimal 0 points on decrement

---

tools/changelog.js

refactor(changelog): add community fixes link

---

test/tests/raffles/community#32.js

test(raffle): check owner is added to raffle only once

---

src/bot/systems/raffles.ts
test/tests/raffles/community#38.js

test(raffles): user should not be added if not eligible

---

src/public/views/songrequests.vue

Fixes https://community.sogebot.xyz/t/add-images-for-public-songrequests/35

fix(public): typo in song property

---

src/bot/main.ts

refactor(connection): add connection options debug

---

src/bot/data/ormconfig.mysql.json
src/bot/data/ormconfig.postgres.json
src/bot/data/ormconfig.sqlite.json
src/bot/main.ts
tools/database.js

fix(database): load entities during createConnection

---

package.json

build: 10.2.0

---

package.json

build: 10.3.0-SNASPHOT

---

src/bot/games/gamble.ts
test/tests/games/gamble.js

Fixes https://community.sogebot.xyz/t/gamble-oops-something-went-wrong/39

fix(gamble): correct points system variable

---

src/panel/widgets/components/customvariables.vue
src/panel/widgets/components/eventlist.vue
src/panel/widgets/components/join.vue
src/panel/widgets/components/part.vue

fix(ui): toggle drag correctly for join/part widgets

---

package.json
src/bot/data/config.example.json

fix(config): cleanup config.example.json

---

src/bot/data/ormconfig.mysql.json
src/bot/data/ormconfig.postgres.json
src/bot/data/ormconfig.sqlite.json
src/bot/main.ts

Reason is to possibility to run cli migration manually

fix(database): revert entities, migrations,  subscribers

---

src/panel/views/managers/viewers/viewers-edit.vue

Fixes https://ideas.sogebot.xyz/posts/161/change-bit-tip-date-of-viewers

feat(ui): add bits/tips date editation

---

test/tests/tmi/user_message_counted#3106.js

test(tmi): add user message count test

---

src/bot/api.ts

fix(api): streamEnd/streamStart trigger relevant module

---

src/bot/database/migration/mysql/1573837107520-initialize.ts

fix(migration): remove database name from table creation

---

tools/database.js

fix(tools): load entities from ormconfig during migration

---

src/bot/database/entity/commands.ts
src/bot/database/migration/mysql/1576758423496-commandResponsesResponseToText.ts
src/bot/database/migration/postgres/1576758423496-commandResponsesResponseToText.ts
src/bot/database/migration/sqlite/1576758423496-commandResponsesResponseToText.ts

fix(commands): set response entity as text

---

tools/database.js

fix(tools): set empty string for js/css attribute

---

src/bot/main.ts
src/bot/systems/userinfo.ts
src/bot/tmi.ts
src/bot/users.ts

fix(users): remove relations causing heap crash

---

src/bot/general.ts

fix(general): !_debug should log proper message

---

src/bot/systems/customcommands.ts

fix(commands): remove responses nullcheck

---

src/bot/systems/customcommands.ts

fix(commands): check cb for function

---

src/bot/_interface.ts
src/bot/changelog.ts
src/bot/database/entity/settings.ts
src/bot/decorators.ts
src/bot/watchers.ts

refactor(typeorm): remove decorators from settings

---

src/bot/database/entity/widget.ts

refactor(typeorm): remove decorators from widget

---

src/bot/socket.ts

fix(socket): load properly socketToken on authorize

---

src/bot/_interface.ts

fix(interface): on.load should trigger correctly

---

package.json

build: 10.3.0

---

package.json

build: 10.4.0-SNAPSHOT

---

src/bot/systems/raffles.ts

refactor(raffle): add raffle debug

---

src/bot/currency.ts
src/bot/users.ts

fix(currency): recalc tips on rate change

---

src/bot/api.ts
src/bot/database/entity/twitch.ts

refactor(typeorm): update twitch schema

---

src/bot/database/entity/translation.ts

refactor(typeorm): update translation schema

---

src/bot/database/entity/timer.ts
src/bot/systems/timers.ts
src/panel/views/managers/timers/timers-edit.vue
src/panel/views/managers/timers/timers-list.vue
test/tests/timers/add.js
test/tests/timers/list.js
test/tests/timers/toggle.js
test/tests/timers/unset.js

refactor(typeorm): update timer schema

---

src/bot/api.ts
src/bot/database/entity/threadEvent.ts

refactor(typeorm): update threadEvent schema

---

src/bot/database/entity/text.ts
src/bot/registries/text.ts

refactor(typeorm): update text schema

---

src/bot/database/entity/song.ts
src/bot/systems/songs.ts
src/panel/views/managers/songs/songs-bannedsongs.vue
src/panel/views/managers/songs/songs-playlist.vue

refactor(typeorm): update song schema

---

src/bot/database/entity/socket.ts
src/bot/socket.ts

refactor(typeorm): update socket schema

---

src/bot/database/entity/rank.ts
src/bot/database/entity/scrimMatchId.ts
src/bot/systems/ranks.ts
src/bot/systems/scrim.ts
src/panel/views/managers/ranks/ranks-edit.vue
src/panel/views/managers/ranks/ranks-list.vue

refactor(typeorm): update rank, scrim schemas

---

src/bot/database/entity/raffle.ts
src/bot/systems/raffles.ts

refactor(typeorm): update raffle schema

---

src/bot/database/entity/poll.ts
src/bot/database/entity/price.ts
src/bot/database/entity/queue.ts
src/bot/systems/polls.ts
src/bot/systems/price.ts
src/bot/systems/queue.ts
src/panel/views/managers/polls.vue
src/panel/views/managers/price/price-edit.vue

refactor(typeorm): update poll, price, queue schema

---

src/bot/_interface.ts
src/bot/database/entity/permissions.ts
src/bot/permissions.ts
src/bot/systems/alias.ts
src/bot/systems/customcommands.ts
src/panel/components/navbar/user.vue
src/panel/views/managers/alias/alias-edit.vue
src/panel/views/managers/alias/alias-list.vue
src/panel/views/settings/components/permissions/edit.vue
src/panel/views/settings/components/permissions/list.vue
src/panel/views/settings/interface.vue
src/panel/views/settings/permissions.vue

refactor(typeorm): update permissions schema

---

src/bot/database/entity/moderation.ts
src/bot/systems/moderation.ts

refactor(typeorm): update moderation schema

---

src/bot/database/entity/howLongToBeatGame.ts
src/bot/database/entity/keyword.ts
src/bot/systems/howlongtobeat.ts
src/bot/systems/keywords.ts
src/panel/views/managers/hltb.vue
src/panel/views/managers/keywords/keywords-edit.vue
src/panel/views/managers/keywords/keywords-list.vue

refactor(typeorm): update hltb, keyword schema

---

src/bot/database/entity/heist.ts
src/bot/database/entity/highlight.ts
src/bot/systems/highlights.ts

refactor(typeorm): update heist, highlight schema

---

src/bot/database/entity/goal.ts
src/bot/message.js
src/bot/overlays/goals.ts
src/bot/parser.ts
src/bot/systems/keywords.ts
src/bot/systems/userinfo.ts
src/overlay/views/goals.vue
src/panel/views/registries/goals/goals-edit.vue
src/panel/views/registries/goals/goals-list.vue
test/tests/cooldowns/check.js
test/tests/keywords/basic_workflow.js
tools/runTests.js

refactor(typeorm): update goal schema

---

src/bot/database/entity/quotes.ts
src/bot/database/entity/raffle.ts
src/bot/systems/quotes.ts
src/panel/views/managers/quotes/quotes-edit.vue
src/panel/views/managers/quotes/quotes-list.vue

refactor(typeorm): update quote schema

---

src/bot/database/entity/eventList.ts
src/bot/database/entity/gallery.ts
src/bot/overlays/credits.ts
src/bot/overlays/eventlist.ts
src/bot/twitch.ts

refactor(typeorm): update eventlist, gallery schema

---

src/bot/database/entity/duel.ts
src/bot/database/entity/event.ts
src/bot/database/entity/goal.ts
src/bot/database/entity/permissions.ts
src/bot/database/entity/poll.ts
src/bot/database/entity/timer.ts
src/bot/events.ts
src/bot/games/duel.ts
src/panel/views/managers/events/edit.vue
src/panel/views/managers/events/list.vue
test/tests/events/cheer.js
test/tests/events/follow.js
test/tests/events/tip.js

refactor(typeorm): update duel, event schema

---

src/bot/database/entity/cooldown.ts
src/bot/database/entity/dashboard.ts
src/bot/systems/cooldown.ts
src/panel/views/managers/cooldowns/cooldowns-edit.vue
src/panel/views/managers/cooldowns/cooldowns-list.vue
test/tests/cooldowns/check.js

refactor(typeorm): update dashboard, cooldown schema

---

src/bot/database/entity/changelog.ts
src/bot/database/entity/checklist.ts
src/bot/database/entity/commands.ts
src/bot/systems/customcommands.ts
src/bot/widgets/cmdboard.ts
src/panel/views/managers/commands/commands-edit.vue
src/panel/views/managers/commands/commands-list.vue

refactor(typeorm): update changelog, checklist, commands schema

---

src/bot/panel.js
src/panel/views/settings/translations.vue

fix(panel): properly set/revert custom translation

---

src/bot/database/entity/cacheEmotes.ts
src/bot/database/entity/cacheGames.ts
src/bot/database/entity/cacheTitles.ts
src/bot/overlays/emotes.ts
src/overlay/views/alertsRegistry.vue

refactor(typeorm): update cache schemas

---

src/bot/microservices/getChannelChattersUnofficialAPI.ts

refactor(microservice): add module-alias import

---

src/bot/database/entity/alias.ts
src/bot/database/entity/bets.ts
src/bot/systems/alias.ts
src/bot/systems/bets.ts
src/overlay/views/bets.vue
src/panel/views/managers/alias/alias-edit.vue
src/panel/views/managers/alias/alias-list.vue

refactor(typeorm): update alias, bets schema

---

src/bot/database/entity/dashboard.ts

refactor(typeorm): dashboard fix inverse side

---

src/bot/stats.js

refactor(typeorm): fix stats save

---

.gitignore
locales/cs/ui/core/general.json
locales/en/ui/core/general.json
package.json
src/bot/_interface.ts
src/bot/general.ts
src/bot/main.ts
src/panel/views/settings/components/interface/helpbox.vue
src/panel/views/settings/interface.vue

feat(general): add graceful exit options

---

bin/startup.sh

fix(shell): add missing exit to startup.sh

---

src/bot/general.ts
src/bot/panel.js

refactor(exit): graceful exit if nothing logged in ui

---

src/bot/database/entity/alert.ts
src/bot/registries/alerts.ts
src/overlay/views/alertsRegistry.vue
src/panel/components/media.vue
src/panel/views/registries/alerts/alerts-edit.vue
src/panel/views/registries/alerts/alerts-list.vue
src/panel/views/registries/alerts/components/form-cheers.vue
src/panel/views/registries/alerts/components/form-follow.vue
src/panel/views/registries/alerts/components/form-hosts.vue
src/panel/views/registries/alerts/components/form-resubs.vue
src/panel/views/registries/alerts/components/tts.vue

refactor(typeorm): update alerts schemas

---

src/bot/microservices/getChannelChattersUnofficialAPI.ts

refactor(microservice): add debug message for catch

---

tools/runTests.js

test(tools): runTests status reset

---

src/bot/microservices/getChannelChattersUnofficialAPI.ts

fix(getChannelChattersUnofficialAPI): force lowercase channel/bot

---

src/bot/panel.js

refactor(typeorm): fix widget creation

---

src/panel/components/statsbar/statsbar.vue

fix(statsbar): show only 1 number after decimal point

---

package.json

build: 10.4.0

---

package.json

build: 10.5.0-SNAPSHOT

---

tools/changelog.js

fix(tools): changelog should not crash on incorrect fixes string

---

src/bot/widgets/eventlist.ts

fix(eventlist): show proper eventlist data in widget

---

package.json

build: 10.4.1

---

src/bot/systems/songs.ts

fix(songs): load playlist data on mysql

---

src/bot/systems/howlongtobeat.ts

When game is not played yet, we got
incorrect error on !hltb command instead
of initializing new hltb game in db

fix(hltb): load data from service on first use of !htlb

---

src/bot/registries/randomizer.ts

fix(randomizer): remove items with null groupId

---

package.json

build: 10.4.2

---

locales/cs/ui/registry/randomizer.json
locales/en/ui/registry/randomizer.json
src/panel/views/registries/randomizer/randomizer-edit.vue

Fixes https://community.sogebot.xyz/t/add-percentage-probability-readonly-for-items-in-randomizer/47

feat(randomizer): add probability table

---

src/bot/registries/randomizer.ts

fix(randomizer): properly save items to database

---

src/bot/systems/userinfo.ts

fix(userinfo): use expects for username parsing

---

package.json

refactor(package): move gc track to own run-script

---

src/panel/widgets/components/randomizer.vue

fix(randomizer): better visual cues in widget

---

src/bot/events.ts
src/panel/views/managers/events/edit.vue

fix(events): don't save test user to db

---

package.json

build: 10.5.0

---

package.json

build: 10.6.0-SNAPSHOT

---

scss/custom.scss

fix(css): set more readable color for table headers

---

src/bot/integrations/twitter.ts

fix(twitter): set proper function  to send message

---

src/bot/systems/points.ts

This cause promise to be not resolved thus halted interval

fix(points): remove return on new user

---

src/bot/database/entity/cooldown.ts
src/bot/database/migration/mysql/1580138082569-CooldownViewerUsernameToUserId.ts
src/bot/database/migration/postgres/1580137967891-CooldownViewerUsernameToUserId.ts
src/bot/database/migration/sqlite/1580137841264-CooldownViewerUsernameToUserId.ts
src/bot/systems/cooldown.ts
test/tests/cooldowns/check.js

fix(cooldown): change viewer username to userId key

---

src/bot/users.ts

fix(users): reset messages with pointsByMessageGivenAt

---

src/bot/database/migration/mysql/1580154710641-resetPoints.ts
src/bot/database/migration/postgres/1580154710641-resetPoints.ts
src/bot/database/migration/sqlite/1580154710641-resetPoints.ts
src/bot/systems/points.ts

fix(points): fix incorrect default values for given points

---

package.json

build: 10.5.1

---

src/bot/systems/points.ts

fix(points): add cron warning message on reset

---

src/panel/views/registries/custom-variables/custom-variables-list.vue

Fixes https://discordapp.com/channels/317348946144002050/619437014001123338/672808497179656242

fix(customvariables): show ui on null value

---

src/bot/registries/alerts.ts

Fixes https://discordapp.com/channels/317348946144002050/619437014001123338/672810317662650385

fix(alerts): attempt to remove media only if needed

---

src/bot/integrations/qiwi.ts
src/bot/integrations/streamelements.ts

fix(integrations): import missed exchange function

---

src/bot/systems/songs.ts

fix(songs): use own api key on search

---

src/bot/microservices/getChannelChattersUnofficialAPI.ts

refactor(microservice): add getChannelChattersUnofficialAPI debugging

---

src/bot/customvariables.ts
src/panel/views/registries/custom-variables/custom-variables-code.txt

Fixes https://ideas.sogebot.xyz/posts/159/console-log-for-custom-variable-script

feat(customvariables): expose info, warning logging to eval

---

src/bot/parser.ts

refactor(parser): add debug for parser permission

---

test/tests/parser/time.js

test(parser): add simple parser time check

---

src/bot/parser.ts

refactor(parser): add debug process, time to isModerated

---

src/bot/helpers/permissions.ts
src/bot/permissions.ts

refactor(permissions): add cache to highest permission

---

src/bot/tmi.ts

refactor(tmi): remove await from message increment

---

src/bot/systems/howlongtobeat.ts

fix(hltb): refresh thumbnail image

---

.github/workflows/dockerimage-release.yml
.github/workflows/dockerimage.yml

build(docker): update docker build usage

---

.github/workflows/dockerimage-release.yml
.github/workflows/dockerimage.yml

build(docker): set exact version for action-docker

---

.github/workflows/dockerimage-release.yml
.github/workflows/dockerimage.yml

build(docker): set older version of action-docker

---

src/bot/systems/cooldown.ts
test/tests/cooldowns/check.js

refactor(cooldowns): add more debug messages

---

src/bot/systems/cooldown.ts
test/tests/cooldowns/check.js

fix(cooldown): use latest timestamp in case of duplicate

---

src/bot/customvariables.ts

fix(customvariables): propagate sender/param correctly

---

package.json
src/bot/customvariables.ts

fix(customvariables): load properly random variable

---

package.json

build: 10.6.0

---

npm-shrinkwrap.json

build(shinkwrap): update shrinkwrap

---

package.json

build: 10.7.0-SNAPSHOT

---

tools/changelog.js

refactor(changelog): add ideas/discord links

---

src/bot/tmi.ts

fix(tmi): ignore REWARDGIFT event

---

src/bot/database/entity/settings.ts
src/bot/database/migration/mysql/1581787294824-uniqueSettings.ts
src/bot/database/migration/postgres/1581787485853-uniqueSettings.ts
src/bot/database/migration/sqlite/1581787552555-uniqueSettings.ts

fix(settings): set unique indices for namespace + name

---

Dockerfile

To use latest version available

build(docker): remove node version from docker

---

src/bot/_interface.ts
src/bot/api.ts

fix(startup): wait for db connection

---

src/bot/systems/songs.ts
src/panel/views/managers/songs/songs-playlist.vue

fix(songs): add skip button for playlist import

---

package.json

build: 10.6.1

---

.markdownlint.json
docs/_master/install-and-upgrade.md

docs: add note about docker registry login

---

docs/_master/_sidebar.md
docs/_master/howto/run-bot-in-cluster.md
src/bot/changelog.ts
src/bot/cluster.ts
src/bot/main.ts

fix(cluster): proper startup for cluster mode

---

src/bot/_interface.ts
src/bot/main.ts

fix(startup): change startup order

---

docs/_master/configuration/env.md
src/bot/microservices/getChannelChattersUnofficialAPI.ts

feat(thread): add env variable THREAD to disable worker_thread

---

.vscode/launch.json
package.json

refactor(debug): inspect listen to 0.0.0.0 without brk

---

locales/cs/ui/registry/alerts.json
locales/en/ui/registry/alerts.json
package.json
src/bot/database/entity/alert.ts
src/bot/database/migration/mysql/1582230220319-TTSMinAmountToShow.ts
src/bot/database/migration/postgres/1582230220319-TTSMinAmountToShow.ts
src/bot/database/migration/sqlite/1582230220319-TTSMinAmountToShow.ts
src/bot/ui.ts
src/overlay/views/alertsRegistry.vue
src/panel/views/registries/alerts/alerts-edit.vue
src/panel/views/registries/alerts/components/tts.vue

Fixes https://ideas.sogebot.xyz/posts/158/alerts-registry-add-min-amount-to-tts

feat(alerts): add minimum amount to play TTS

---

docs/_master/filters/all.md
locales/cs.json
locales/en.json
src/bot/api.ts
src/bot/message.js
src/bot/systems/customcommands.ts
src/panel/views/managers/commands/commands-edit.vue

Fixes https://ideas.sogebot.xyz/posts/123/language-as-global-variable-obtainable-through-twitch-api

feat(variables): add $language global variable

---

src/panel/components/navbar/menu.vue
src/panel/index.ts

fix(ui): menu dropdown to properly shown on correct position

---

src/panel/views/managers/highlights.vue

fix(ui): show icons in manage/highlights

---

src/bot/api.ts

perf(api): update subscribe status only on change

---

src/panel/views/managers/highlights.vue
src/panel/views/managers/songs/songs-bannedsongs.vue
src/panel/views/managers/songs/songs-playlist.vue

fix(ui): add link button, disable hover click

---

docs/_master/commands/ranks.md
docs/_master/filters/all.md
locales/cs.json
locales/cs/ui.systems.ranks.json
locales/en.json
src/bot/database/entity/rank.ts
src/bot/database/migration/mysql/1582546819777-RanksTypes.ts
src/bot/database/migration/postgres/1582546688571-RanksTypes.ts
src/bot/database/migration/sqlite/1582546530473-RanksTypes.ts
src/bot/message.js
src/bot/systems/customcommands.ts
src/bot/systems/ranks.ts
src/bot/systems/userinfo.ts
src/panel/views/managers/ranks/ranks-edit.vue
src/panel/views/managers/ranks/ranks-list.vue

Fixes https://ideas.sogebot.xyz/posts/3/rank-by-sub-lenght

feat(ranks): add ranks based on followage/subage

---

src/bot/_interface.ts
src/bot/general.ts
src/bot/helpers/register.ts
src/bot/panel.js
src/bot/parser.ts
src/bot/ui.ts

refactor(register): remove glob for system register

---

src/bot/currency.ts

fix(currency): use IP instead of domain

---

src/bot/currency.ts

refactor(currency): use axios instead of request

---

src/bot/socket.ts

fix(socket): use connection after db is connected

---

src/bot/api.ts
src/bot/database/entity/twitch.ts
src/bot/database/migration/mysql/1582678658728-tagIdAndLocaleUnique.ts
src/bot/database/migration/postgres/1582678534987-tagIdAndLocaleUnique.ts
src/bot/database/migration/sqlite/1582677505312-tagIdAndLocaleUnique.ts

fix(api): attach id to map localization names/descriptions

---

package.json

build: 10.7.0

---

package.json

build: 10.8.0-SNAPSHOT

---

src/bot/_interface.ts

fix(interface): properly save enabled state to db

---

src/bot/watchers.ts

fix(watchers): save core variables with type

---

package.json

build: 10.7.1

---

src/bot/oauth.ts

fix(oauth): hide access/refresh token in logs

---

src/bot/database/entity/moderation.ts
src/bot/database/migration/mysql/1583162282970-PermitByUserId.ts
src/bot/database/migration/postgres/1583162215893-PermitByUserId.ts
src/bot/database/migration/sqlite/1583162070570-PermitByUserId.ts
src/bot/systems/moderation.ts
test/tests/moderation/permitLink.js

Fixes: https://community.sogebot.xyz/t/rewrite-moderation-system-permit-to-use-userids/44

fix(moderation): use userId instead of username

---

locales/cs.json
locales/en.json
src/bot/systems/points.ts
test/tests/points/all.js
test/tests/points/get.js
test/tests/points/online.js
test/tests/points/set.js

Fixes https://community.sogebot.xyz/t/user-position-on-top-for-points-command/29

feat(points): !points show position of user

---

src/panel/widgets/components/eventlist.vue

Fixes https://discordapp.com/channels/317348946144002050/619437014001123338/684367725866385416

fix(eventlist): cleanup eventlist on button hold

---

src/bot/panel.js

fix(panel): import customvariables class

---

src/bot/systems/userinfo.ts
test/helpers/user.js
test/tests/userinfo/stats.js

refactor(userinfo): change expected error to ed2a26

---

package.json

build: 10.8.0

---

package.json

build: 10.9.0-SNAPSHOT

---

.github/FUNDING.yml
docs/README.md
docs/_master/README.md

docs: update README, FUNDING

---

src/bot/main.ts

fix(main): exit bot if db connection is incomplete on start

---

src/panel/widgets/components/raffles.vue

fix(raffles): save widget state to localStorage

---

src/bot/systems/raffles.ts
src/panel/widgets/components/raffles.vue
test/helpers/db.js
test/tests/raffles/pick.js
test/tests/raffles/ticketsBoundaries.js

fix(raffles): min tickets should be minimum of 1

---

.dockerignore
.eslintrc.json
.github/workflows/tests.yml
.npmrc
Makefile
package-lock.json

build(docker): fix node-sass error on bot build

---

src/bot/users.ts

refactor(users): implement getUserByUsername method

---

src/bot/_interface.ts

fix(interface): onChange should not trigger before onStartup

---

package-lock.json
package.json
src/bot/systems/songs.ts

feat(songs): remove default API key

---

.github/workflows/tests.yml

test: use webpack build as own test

---

locales/cs/ui.menu.json
locales/cs/ui/integrations/tipeeestream.json
locales/en/ui.menu.json
locales/en/ui/integrations/tipeeestream.json
src/bot/_interface.ts
src/bot/integrations/tipeeestream.ts
src/bot/users.ts

Fixes https://community.sogebot.xyz/t/tipeee-integration/57

feat(integrations): add tipeeestream

---

src/bot/integrations/streamlabs.ts

fix(streamlabs): parse correct donation currency 

---

locales/cs/ui/integrations/streamlabs.json
locales/en/ui/integrations/streamlabs.json
src/bot/integrations/streamlabs.ts
src/bot/watchers.ts

feat(streamlabs): add rest api fetching

---

src/bot/commons.ts
src/bot/customvariables.ts
src/bot/events.ts
src/bot/games/duel.ts
src/bot/games/fightme.ts
src/bot/games/seppuku.ts
src/bot/permissions.ts
src/bot/systems/customcommands.ts

Async/await have no point on such checks.

refactor(commons): do not use async function for simple "is" check

---

locales/cs/ui/integrations/streamlabs.json
locales/en/ui/integrations/streamlabs.json
src/bot/integrations/streamlabs.ts

feat(streamlabs): add link to streamlabs token generator

---

src/bot/currency.ts
src/bot/integrations/donationalerts.ts
src/bot/integrations/qiwi.ts
src/bot/integrations/streamelements.ts
src/bot/integrations/streamlabs.ts
src/bot/integrations/tipeeestream.ts
src/bot/users.ts
test/tests/top/tips.js

Fixes https://community.sogebot.xyz/t/top-tips-and-ui-users-list-shows-incorrect-users-tip-amount/81

fix(users): show correct tips in ui and !top tips

---

docs/README.md
docs/_master/README.md

docs: fix incorrect patreon link

---

webpack.config.js

fix(webpack): add necessary env for vuelidate

---

src/panel/views/registries/goals/goals-list.vue

fix(ui): fix incorrect locale path

---

src/panel/views/registries/alerts/components/tts.vue

fix(ui): load correct responsive voice api key

---

src/overlay/views/alertsRegistry.vue

refactor(overlay): add try/catch block

---

src/bot/currency.ts
src/bot/database/entity/user.ts
src/bot/database/migration/mysql/1584106270435-tipsExchangeRates.ts
src/bot/database/migration/postgres/1584106270435-tipsExchangeRates.ts
src/bot/database/migration/sqlite/1584106270435-tipsExchangeRates.ts
src/bot/integrations/donationalerts.ts
src/bot/integrations/qiwi.ts
src/bot/integrations/streamelements.ts
src/bot/integrations/streamlabs.ts
src/bot/integrations/tipeeestream.ts
test/tests/permissions/check.js
test/tests/top/tips.js

This will ensure correct currency exchange on main currency
change with historic accuracy. No more changing rates in time.
Fixes #3344

refactor(currency): save exchange rate on each tip

---

src/bot/registries/alerts.ts

fix(overlay): set alerts as public endpoint

---

src/bot/data/.env.mysql
src/bot/data/.env.postgres
src/bot/data/.env.sqlite

build(env): remove spaces from configurations

---

src/bot/database/migration/mysql/1584106270435-tipsExchangeRates.ts
src/bot/database/migration/postgres/1584106270435-tipsExchangeRates.ts
src/bot/database/migration/sqlite/1584106270435-tipsExchangeRates.ts

refactor(migration): add \ to quote marks in tip message

---

src/bot/database/entity/user.ts
src/bot/users.ts
src/panel/views/managers/viewers/viewers-edit.vue

fix(users): tips fixes

---

Makefile

build(make): fix copy of default config

---

src/bot/_interface.ts
src/bot/api.ts
src/bot/changelog.ts
src/bot/decorators.ts
src/bot/general.ts
src/bot/helpers/interface/triggers.ts
src/bot/ui.ts
src/bot/watchers.ts

refactor(require): remove dynamic require

---

src/bot/_interface.ts
src/bot/decorators.ts

refactor(interface): initialize commands inside loading process

---

package.json

build: 10.9.0

---

package.json

build: 10.10.0-SNAPSHOT

---

src/bot/api.ts

fix(api): remove unused count in api call

---

src/bot/watchers.ts

refactor(watchers): simplify module get

---

docs/_master/configuration/database.md
docs/configuration/database.md

docs(database): more detailed info to set dbs

---

src/panel/views/registries/alerts/alerts-edit.vue

Fixes https://discordapp.com/channels/317348946144002050/619437014001123338/689493604636426379

fix(ui): properly load alert for editation

---

src/bot/tmi.ts

fix(tmi): set properly TMI status on bot connect

---

package.json

build: 10.9.1

---

locales/cs/ui.menu.json
locales/en/ui.menu.json
src/bot/stats/tips.ts
src/panel/index.ts
src/panel/views/stats/tips.vue

feat(stats): add tip stats per year

---

Makefile
webpack.config.js

build(webpack): remove version from cache

---

docs/_master/filters/all.md
src/bot/customvariables.ts
src/bot/message.js
test/tests/message/cvars.js

Added possibility to use +value, -value to
extend functionality of +/-

fix(cvar): fix behavior of +/- on number

---

tools/release-master.sh

build(tools): skip husky hooks install on release

---

src/bot/microservices/getChannelChattersUnofficialAPI.ts

Fixes https://discordapp.com/channels/317348946144002050/619437014001123338/689775762475188270

fix(microservice): add isThreadingEnabled check

---

src/bot/main.ts
src/bot/microservices/getChannelChattersUnofficialAPI.ts

refactor(main): add slight wait to have all entities loaded

---

src/bot/permissions.ts

Fixes https://discordapp.com/channels/317348946144002050/619437014001123338/689826198393847856

fix(permissions): search by ID if is a number

---

locales/cs/ui.menu.json
locales/en/ui.menu.json
src/bot/stats/bits.ts
src/panel/index.ts
src/panel/views/stats/bits.vue

feat(stats): add bit stats per year

---

package-lock.json
scss/custom.scss
src/panel/views/stats/bits.vue
src/panel/views/stats/tips.vue

Fixes #3391
Fixes #3392
Fixes #3393

refactor(ui): tweaks to bits/tips stats ui

---

src/bot/oauth.ts

fix(oauth): clean permission cache on owner change

---

src/bot/database/entity/carousel.ts
src/bot/database/migration/mysql/1584634313840-carouselDataLongText carouselDataLongText.ts

Fixes https://discordapp.com/channels/317348946144002050/619437014001123338/690196040279654470

fix(carousel): set longtext data for mysql

---

package.json

build: 10.10.0

---

package.json

build: 10.11.0-SNAPSHOT

---

src/panel/views/registries/alerts/alerts-edit.vue

fix(ui): set correct event for alert delete

---

src/panel/views/registries/alerts/components/tts.vue

fix(ui): initialize tts only once

---

src/bot/games/heist.ts

Fixes https://discordapp.com/channels/317348946144002050/619437014001123338/690318611247923260

fix(heist): remove deprecated expects.check usage

---

src/panel/views/registries/text-overlay/text-overlay-list.vue

Fixes https://discordapp.com/channels/317348946144002050/619437014001123338/690323607259578695

fix(ui): show text overlay list data

---

package.json

build: 10.10.1

---

locales/cs/ui.systems.songs.json
locales/en/ui.systems.songs.json
package-lock.json
package.json
src/bot/systems/songs.ts
test/helpers/db.js
test/tests/songs/addSongToQueue.js

feat(songs): remove need of YouTube API key

---

src/bot/api.ts

fix(api): skip getChannelChattersUnofficialAPI on unset oAuth

---

src/bot/_interface.ts

refactor(interface): wait for ioServer

---

src/bot/panel.ts
src/panel/components/statsbar/statsbar.vue

refactor(ui): send correct currentSong values

---

src/bot/systems/songs.ts

fix(songs): nil check for currentSong

---

src/bot/overlays/gallery.ts
src/bot/registries/alerts.ts

refactor(ui): wait for express app init

---

src/bot/systems/raffles.ts
src/panel/widgets/components/raffles.vue

fix(raffles): show participants in UI

---

test/tests/songs/addSongToQueue.js

test(songs): update song name

---

src/panel/views/managers/quotes/quotes-list.vue
src/public/views/quotes.vue

Fixes https://discordapp.com/channels/317348946144002050/619437014001123338/690941251125772348

fix(quotes): word-wrap long quotes in table

---

src/panel/helpers/userById.ts
src/panel/views/managers/quotes/quotes-edit.vue
src/panel/views/managers/quotes/quotes-list.vue
src/public/views/quotes.vue

Fixes https://discordapp.com/channels/317348946144002050/619437014001123338/690942867736231946

fix(quotes): get proper name of quote user

---

locales/cs/ui.systems.raffles.json
locales/en/ui.systems.raffles.json
src/bot/systems/raffles.ts
test/tests/raffles/allowOverTicketing.js
test/tests/raffles/cumulativeTickets.js

feat(raffles): add allowOverTicketing toggle

---

scss/custom.scss
src/bot/widgets/eventlist.ts
src/panel/index.ts
src/panel/widgets/components/eventlist.vue
src/panel/widgets/components/raffles.vue

feat(eventlist): add replay button on hover

---

src/bot/database/entity/dashboard.ts
src/bot/database/migration/mysql/1584981805762-dashboardPerTypeAndUser.ts
src/bot/database/migration/postgres/1584981805762-dashboardPerTypeAndUser.ts
src/bot/database/migration/sqlite/1584981805762-dashboardPerTypeAndUser.ts
src/bot/panel.ts
src/bot/socket.ts
src/panel/views/dashboard/dashboard.vue
src/panel/widgets/components/dashboard_remove.vue
src/panel/widgets/components/widget_create.vue

refactor(dashboard): save dashboard per user and type

---

locales/cs/ui.menu.json
locales/en/ui.menu.json
src/bot/_interface.ts
src/bot/general.ts
src/bot/helpers/panel.ts
src/bot/panel.ts
src/bot/systems/quotes.ts
src/bot/systems/songs.ts
src/bot/widgets/chat.ts
src/panel/components/navbar/user.vue
src/panel/helpers/isUserLoggedIn.ts
src/panel/helpers/socket.ts
src/public/components/navbar/menu.vue
src/public/components/navbar/navbar.vue
src/public/components/twitch.vue
src/public/index.html
src/public/index.ts
src/public/views/dashboard.vue
src/public/views/playlist.vue
src/public/views/quotes.vue
src/public/views/songrequests.vue

feat(public): add stream and chat

---

src/panel/index.html
src/public/index.html

refactor(public): add loading progress

---

locales/cs.json
locales/cs/ui/core/ui.json
locales/en.json
locales/en/ui/core/ui.json
src/bot/ui.ts
src/panel/components/navbar/navbar.vue
src/panel/components/navbar/theme.vue
src/panel/index.ts
src/panel/popout.ts
src/panel/views/registries/alerts/components/form-cheers.vue
src/panel/views/registries/alerts/components/form-follow.vue
src/panel/views/registries/alerts/components/form-hosts.vue
src/panel/views/registries/alerts/components/form-resubs.vue
src/panel/views/registries/goals/goals-edit.vue
src/panel/widgets/components/chat.vue
src/public/components/navbar/navbar.vue
src/public/components/twitch.vue

Remove from settings and keep theme per user and browser cache
Fixes #3439

feat(theme): add change theme button

---

src/bot/socket.ts
src/bot/users.ts
src/panel/helpers/isUserLoggedIn.ts

Add this behavior to newAuthorization

refactor(isUserLoggedIn): remove updateId of logged viewer

---

src/login/views/login.vue
src/oauth/index.html

refactor(login): use referrer to go back to correct page

---

src/panel/components/navbar/user.vue

refactor(user): remove login dropdown

---

src/bot/database/migration/mysql/1584981805762-dashboardPerTypeAndUser.ts
src/bot/database/migration/postgres/1584981805762-dashboardPerTypeAndUser.ts

refactor(migration): fix incorrect sql queries

---

src/bot/socket.ts
src/panel/helpers/isUserLoggedIn.ts

refactor(socket): save user with userId if missing

---

src/bot/systems/songs.ts
test/tests/songs/addSongToQueue.js

refactor(songs): add more retries, err log on test

---

src/panel/helpers/isUserLoggedIn.ts
src/public/index.ts

refactor(isUserLoggedIn): check userType on user

---

src/bot/socket.ts
src/panel/components/navbar/user.vue

fix(user): invalidate socket connection after logout

---

src/panel/widgets/components/eventlist.vue

refactor(eventlist): add redoAlt icon to popout

---

LICENSE

chore: change to GPL3.0 license

---

src/bot/integrations/spotify.ts
src/bot/panel.ts
src/panel/components/statsbar/statsbar.vue

feat(spotify): show UI error if something went wrong

---

tools/release-docs.sh

build(release): simplify release of docs

---

src/bot/database/migration/mysql/1584981805762-dashboardPerTypeAndUser.ts

refactor(migration): fix migration deletion

---

package.json

build: 10.11.0

---

package.json

build: 10.12.0-SNAPSHOT

---

src/bot/panel.ts

fix(panel): remove spotify error generated on start

---

src/bot/systems/songs.ts

fix(songs): retry on getInfo error

---

package.json

build: 10.11.1

---

locales/cs.json
locales/cs/ui/core/ui.json
locales/en.json
locales/en/ui/core/ui.json
src/bot/ui.ts
src/panel/components/navbar/theme.vue
src/panel/popout.ts
src/panel/views/registries/alerts/components/form-cheers.vue
src/panel/views/registries/alerts/components/form-follow.vue
src/panel/views/registries/alerts/components/form-hosts.vue
src/panel/views/registries/alerts/components/form-resubs.vue
src/panel/views/registries/goals/goals-edit.vue
src/panel/widgets/components/chat.vue
src/public/components/twitch.vue
src/public/index.ts

feat(ui): add default theme settings

---

src/bot/api.ts

fix(api): run intervals one by one

---

src/bot/api.ts
src/bot/panel.ts
src/panel/components/dialog/changegamedialog.vue
src/panel/components/statsbar/statsbar.vue

perf(panel): save current tags as variable

---

src/panel/components/statsbar/statsbar.vue

fix(statsbar): simplify calls to get latest stream data

---

src/panel/widgets/components/chat.vue
src/public/components/twitch.vue

fix(chat): show properly admin chat widget

---

src/panel/components/statsbar/statsbar.vue

fix(statsbar): set correct format of numbers

---

src/bot/socket.ts
src/panel/helpers/socket.ts

fix(socket): reauth/auth only once

---

src/bot/socket.ts

refactor(socket): add more debug messages

---

src/bot/socket.ts
src/panel/helpers/socket.ts

refactor(socket): logging + userId update

---

src/bot/socket.ts
src/panel/helpers/socket.ts

refactor(socket): not asssume unauthorized without accessToken

---

src/bot/socket.ts

fix(socket): set as not authorized if refresh token is incorrect

---

src/bot/api.ts

fix(api): ignore fetch for 0 user

---

src/bot/general.ts

fix(general): debug should show proper systems

---

src/bot/customvariables.ts
src/bot/widgets/customvariables.ts
src/panel/helpers/socket.ts
src/panel/views/registries/custom-variables/custom-variables-edit.vue
src/panel/views/registries/custom-variables/custom-variables-list.vue
src/panel/widgets/components/customvariables.vue

Fixes https://discordapp.com/channels/317348946144002050/619437014001123338/693022576200384512

fix(customvariables): register socket endpoints

---

docs/_navbar.md

chore: update docs

---

package.json

build: 10.12.0

---

package.json

build: 10.13.0-SNAPSHOT

---

src/panel/helpers/socket.ts
src/panel/index.ts

fix(socket): authorize before admin page load

---

src/panel/views/registries/goals/goals-edit.vue

fix(goals): load theme in data

---

package.json

build: 10.12.1

---

src/overlay/views/alerts.vue

refactor(alerts): show element error in console

---

.github/workflows/dockerimage.yml

build: send image to docker

---

.github/workflows/dockerimage-release.yml
docs/_master/install-and-upgrade.md
docs/install-and-upgrade.md

build: send release image to docker

---

src/panel/components/navbar/user.vue

feat(user): add go to admin/public button

---

src/bot/systems/alias.ts
src/panel/views/managers/alias/alias-edit.vue

fix(alias): return alias data on save

---

scss/custom.scss
src/panel/components/footer.vue

fix(footer): change license to GPL-3.0

---

package.json

build: 10.13.0

---

package.json

build: 10.14.0-SNAPSHOT

---

package-lock.json
package.json
tools/mklogdir.js

fix(startup): make log dir before prestart
