sogebot/sogeBot

src/overlay/views/alerts.vue

fix(alerts): attempt to fix pause/play race condition

---

package.json

build: 10.13.1

---

docs/_master/install-and-upgrade.md
docs/install-and-upgrade.md

docs: remove config.json steps

---

src/bot/overlays/gallery.ts

feat(gallery): add proper media caching

---

src/bot/overlays/carousel.ts

Fixes https://discordapp.com/channels/317348946144002050/619437014001123338/694643092187512872

fix(carousel): return null error on correct save

---

src/bot/overlays/gallery.ts

refactor(gallery): check content size before full data load

---

locales/cs/ui/overlays/alerts.json
locales/en/ui/overlays/alerts.json
src/bot/overlays/alerts.ts
src/overlay/views/alerts.vue

feat(alerts): cache gallery items

---

package-lock.json
package.json
src/public/views/playlist.vue
src/public/views/quotes.vue
src/public/views/songrequests.vue

fix(playlist): add missing pagination

---

src/public/views/songrequests.vue

fix(public): songrequest should link to correct video

---

package.json

build: 10.14.0

---

package.json

build: 10.15.0-SNAPSHOT

---

package-lock.json
src/panel/views/managers/events/edit.vue

fix(ui): relod definition only on event change

---

test/tests/keywords/basic_workflow.js

test(keywords): enable commented tests

---

src/panel/views/registries/alerts/components/form-cheers.vue
src/panel/views/registries/alerts/components/form-follow.vue
src/panel/views/registries/alerts/components/form-hosts.vue
src/panel/views/registries/alerts/components/form-resubs.vue

fix(alerts): load theme in constructor

---

src/bot/api.ts
src/bot/cluster.ts
src/bot/microservices/getChannelChattersUnofficialAPI.ts
src/bot/systems/userinfo.ts

Fixes https://discordapp.com/channels/317348946144002050/689472699910717522/696495462831751188

fix(userinfo): fetch account age on demand

---

src/bot/systems/timers.ts

fix(timers): trigger timer only on online stream

---

package.json

build: 10.14.1

---

src/panel/components/media.vue
src/panel/views/registries/alerts/components/form-cheers.vue
src/panel/views/registries/alerts/components/form-follow.vue
src/panel/views/registries/alerts/components/form-hosts.vue
src/panel/views/registries/alerts/components/form-resubs.vue

fix(alerts): reload avline component on mount

---

src/panel/views/registries/alerts/alerts-edit.vue

fix(alerts): show advancedMode inputs on tab change

---

locales/cs/ui.errors.json
locales/en/ui.errors.json
src/panel/views/managers/keywords/keywords-edit.vue

feat(keywords): add simple regexp format validator

---

src/bot/integrations/spotify.ts

Fixes https://community.sogebot.xyz/t/spotify-playlist-return/93

fix(spotify): add retry to playNextSongFromPlaylist

---

src/bot/systems/raffles.ts
test/tests/raffles/bug#3547.js

fix(raffles): join with max tickets if bet more

---

test/tests/raffles/bug#3546.js

test(raffles): add test for #3546

---

locales/cs/ui/integrations/spotify.json
locales/en/ui/integrations/spotify.json

fix(spotify): add Spotify URI to playlist title

---

src/bot/integrations/qiwi.ts

Fixes https://discordapp.com/channels/317348946144002050/619437014001123338/699629533636198411

fix(qiwi): fire tip event with correct currency

---

src/bot/tmi.ts

This should prevent duplication of messages if
something unexpected happen during (re)connect
Fixes #3554

fix(tmi): remove all listeners on listener init

---

src/bot/_interface.ts
src/bot/integrations/spotify.ts

refactor(interface): fix incorrect enabled state

---

locales/cs/ui/integrations/qiwi.json
locales/en/ui/integrations/qiwi.json
src/bot/_interface.ts

refactor(interface): force null enabled state to be unsettable

---

src/bot/integrations/streamlabs.ts

fix(streamlabs): parse currency from API

---

package.json

build: 10.15.0

---

package.json

build: 10.16.0-SNAPSHOT

---

src/panel/components/media.vue

Fixes https://discordapp.com/channels/317348946144002050/619437014001123338/701812693706735719

fix(alerts): load correct media after new upload

---

src/bot/integrations/spotify.ts

Fixes https://discordapp.com/channels/317348946144002050/317348946144002050/702286391484350515

fix(spotify): use accessToken from client

---

src/bot/integrations/spotify.ts

fix(spotify): add success info for access token

---

src/bot/integrations/spotify.ts

refactor(spotify): refresh accessToken every hour

---

src/bot/database/entity/randomizer.ts
src/bot/database/migration/mysql/1587638890394-addTTSToRandomizer.ts
src/bot/database/migration/postgres/1587638203596-addTTSToRandomizer.ts
src/bot/database/migration/sqlite/1587636268054-addTTSToRandomizer.ts
src/overlay/views/randomizer.vue
src/panel/views/registries/alerts/components/tts.vue
src/panel/views/registries/randomizer/randomizer-edit.vue

feat(randomizer): add TTS for win item

---

.github/workflows/tests.yml
package.json
src/bot/main.ts

refactor(report): add report for uncaughtException and fatal crash

---

src/bot/systems/cooldown.ts
test/tests/cooldowns/check.js
test/tests/cooldowns/toggleModerators.js
test/tests/cooldowns/toggleOwners.js
test/tests/cooldowns/toggleSubscribers.js

refactor(cooldown): remove redundant user save

---

package.json

chore(package): add experimental report flag

---

src/bot/systems/raffles.ts
test/helpers/user.js
test/tests/raffles/bug#3587.js
test/tests/raffles/ticketsBoundaries.js

fix(raffles): decrement only new tickets

---

src/panel/widgets/components/raffles.vue

fix(raffles): show proper widget tickets if raffle is running

---

src/overlay/views/randomizer.vue
src/panel/views/registries/randomizer/randomizer-edit.vue

+ small fix for isShown when saving new wof
+ small fix to not redraw wof if nothing changed
Fixes #3588

refactor(randomizer): add debug for data

---

src/bot/customvariables.ts
src/bot/database/entity/variable.ts

fix(customvariable): POST should correctly update variable

---

src/bot/widgets/eventlist.ts
src/panel/widgets/components/eventlist.vue

feat(eventlist): add edit mode for deletion

---

Makefile
patches/twitch-js-types-2.patch
src/bot/tmi.ts

Fixes https://discordapp.com/channels/317348946144002050/619437014001123338/704307778801631232

fix(tmi): consider founder badge as subscriber

---

src/overlay/views/text.vue

fix(text): show warning message if text overlay not found

---

src/overlay/views/polls.vue

fix(polls): null check for poll in progress

---

src/bot/commons.ts

refactor(commons): fix incorrect message to be send through discord

---

src/bot/commons.ts

+ remove message if set to delete after while
Fixes #3607
[skip-tests]

refactor(commons): use opts.sender.discord in parserReply

---

.github/workflows/tests.yml

chore(tests): run tests on node14

---

src/bot/systems/timers.ts

refactor(timers): sort responses

---

src/bot/expects.ts
src/bot/integrations/discord.ts

refactor(discord): update error message for twitch !link

---

src/panel/views/registries/custom-variables/custom-variables-edit.vue

fix(customvariables): default permission to be highest permission

---

src/bot/api.ts

fix(api): trigger onStreamEnd when stream stop

---

crowdin.yml

chore(crowdin): add settings

---

crowdin.yml

chore(crowdin): add [skip-tests]

---

src/bot/commons.ts
test/tests/commons/#3620_announce_is_not_parsing_filters.js

refactor(commons): announce should parse message

---

src/bot/integrations/discord.ts

feat(integrations): add stream preview for discord embed

---

.github/workflows/tests.yml

chore(tests): skip tests if in commit message

---

src/bot/events.ts
src/bot/tmi.ts

fix(tmi): ban doesn't have reason in raw TMI

---

.github/workflows/tests.yml

chore(tests): add subject to skip-tests check

---

locales/en.json

chore(locales): remove unused merge

---

locales/en/ui/integrations/discord.json
src/bot/integrations/discord.ts
src/panel/views/settings/components/interface/btn-emit.vue

refactor(discord): add missing button locales

---

src/bot/integrations/discord.ts

refactor(discord): force 404 image on offline stream

---

src/bot/message.ts
test/helpers/db.js
test/tests/message/discord#706756329204613160_latest_variable_are_not_correct.js

Fixes https://discordapp.com/channels/317348946144002050/619437014001123338/706756329204613160

fix(message): show correct latest global variables

---

src/bot/registries/text.ts
src/overlay/views/text.vue
src/panel/views/registries/text-overlay/text-overlay-edit.vue

Fixes https://discordapp.com/channels/317348946144002050/619437014001123338/706752466221400106

fix(text): edit UI should not parse html

---

package-lock.json
package.json

chore(dependencies): revert moment to 2.24.0

---

locales/en.json
locales/en/ui/games/gamble.json
src/bot/games/gamble.ts
test/tests/commands/run.js
test/tests/events/cheer.js
test/tests/events/follow.js
test/tests/events/tip.js
test/tests/games/gambleWithJackpot.js

Fixes https://community.sogebot.xyz/t/jackpot-in-gamble/107

feat(gamble): add jackpot behavior

---

locales/en/ui.menu.json
locales/en/ui/overlays/texttospeech.json
src/bot/overlays/textToSpeech.ts
src/overlay/index.ts
src/overlay/views/tts.vue
src/panel/views/settings/components/interface/helpbox.vue
src/panel/views/settings/components/interface/voice.vue
src/panel/views/settings/interface.vue

Fixes https://community.sogebot.xyz/t/text-to-speech-messages/50

feat(tts): add text-to-speech overlay

---

locales/cs/ui/managers.json
locales/de/ui/managers.json
locales/en/ui/managers.json
locales/ru/ui/managers.json
locales/uk/ui/managers.json
src/bot/overlays/eventlist.ts
src/panel/views/managers/viewers/viewers-edit.vue

Fixes https://community.sogebot.xyz/t/log-user-subgifts-and-sub-recieve/52

feat(viewers): add event history into edit ui

---

src/bot/api.ts
src/bot/helpers/sql.ts
test/tests/api/getLatest100Followers.js

refactor(api): update followers in chunks

---

test/tests/message/discord#706782624416399422_sender_object_should_be_ignored.js
tools/runTests.js

should exclude(!#) as it runs 0 tests
should fail if 0 tests are running in rerun phase
fix timer check test

test(run): update rerun testing

---

src/bot/commons.ts
src/bot/systems/alias.ts

Fixes https://discordapp.com/channels/317348946144002050/619437014001123338/707718945515503748

fix(alias): parse alias response before send

---

src/bot/overlays/alerts.ts

fix(alerts): return empty response on !alert

---

src/bot/events.ts

fix(events): fireRunCommand should be properly parsed

---

src/bot/microservices/getChannelChattersUnofficialAPI.ts

refactor(getChannelChattersUnofficialAPI): cannot retrieve error stack

---

src/bot/microservices/getUserFromTwitch.ts

fix(getUserFromTwitch): use clientId properly

---

src/bot/decorators.ts

refactor(decorators): update load check for decorators

---

package.json

build: 11.0.0

---

package.json

build: 11.1.0-SNAPSHOT

---

src/panel/helpers/isUserLoggedIn.ts
src/panel/helpers/socket.ts

refactor(isUserLoggedIn): remove logging of clientId

---

test/tests/games/gambleWithJackpot.js

test(gamble): set chances to -1

---

test/tests/commons/#3620_announce_is_not_parsing_filters.js

test(3620): use announce directly

---

docs/_master/configuration/env.md
docs/configuration/env.md
docs/install-and-upgrade.md

chore(docs): add port to env list

---

locales/en/ui/overlays/texttospeech.json
src/bot/_interface.ts
src/panel/views/settings/components/interface/voice.vue
src/panel/views/settings/interface.vue

Fixes https://discordapp.com/channels/317348946144002050/619437014001123338/708003144344272916

fix(interface): hide settings as determinated with ui

---

src/bot/parser.ts
src/bot/systems/alias.ts
test/tests/alias/#3680_alias_should_override_command_permission.js

fix(alias): alias should overwrite command permission

---

package.json

build: 11.0.1

---

src/bot/_interface.ts
src/bot/commons.ts
src/bot/overlays/alerts.ts
src/bot/systems/alias.ts
test/helpers/messages.js
test/tests/alias/#3680_alias_should_override_command_permission.js
test/tests/alias/discord#707718945515503748_alias_should_parse_response.js
test/tests/alias/run.js

chore(test): extend alias permission and message filter tests

---

src/bot/message.ts
test/tests/message/discord#708371785157967873_permission_of_command_should_be_ignored.js

fix(message): honor (!#) filters mute and not check permission

---

src/panel/helpers/socket.ts

refactor(socket): use socket manager

---

docker.sh
package.json

chore(docker): add cpu profiling from docker

---

src/panel/widgets/components/raffles.vue

fix(raffles): remove interval if raffle widget is not visible

---

docker.sh

chore(docker): trap SIGTERM

---

Dockerfile
docker.sh

chore(docker): copy logs through cron

---

Dockerfile

chore(docker): remove cron install

---

docker.sh
package.json

chore(docker): add DEBUG env to docker.sh

---

src/bot/general.ts

fix(general): !_debug should return empty response

---

src/bot/api.ts

perf(api): process only new followers

---

src/bot/twitch.ts

Fixes https://discordapp.com/channels/317348946144002050/619437014001123338/708846965584297984

fix(twitch): set game return error if game not found

---

src/panel/popout.ts

fix(popout): authorize / socket on load

---

docker.sh

chore(docker): check DEBUG env correctly

---

src/bot/api.ts
src/bot/stats.ts

perf: save stream stats every 15min, check chatters every 10min

---

docs/_master/faq.md
docs/faq.md

docs(faq): add info about EAI_AGAIN

---

src/bot/integrations/streamlabs.ts

refactor(streamlabs): return only error stack

---

.vscode/launch.json
src/bot/api.ts
src/bot/integrations/streamlabs.ts
src/panel/views/stats/api.vue

changed TMI to OTHERS, this should be used for various api calls
[skip-tests]

refactor(streamlabs): add streamlabs to API stats

---

src/bot/integrations/discord.ts

refactor(discord): add logging if discord channel not found

---

package.json

build: 11.1.0

---

package.json

build: 11.2.0-SNAPSHOT

---

Dockerfile

chore(docker): expose 9229

---

src/bot/api.ts
src/bot/webhooks.ts

fix(webhooks): add oauth access token to request

---

test/tests/cooldowns/#3720_cooldown_should_be_properly_reverted.js

test(cooldown): check if global cooldown is reverted

---

src/bot/message.ts
src/bot/systems/points.ts
src/bot/systems/price.ts
test/tests/message/#3726_price_should_be_shown_alongside_alias_and_command_list.js
test/tests/message/api.js

feat(message): (list.#) will return prices for alias and commands

---

src/bot/systems/raffles.ts
src/panel/widgets/components/raffles.vue

fix(raffles): show last 5 messages of user in widget

---

locales/en/ui/integrations/discord.json
src/bot/integrations/discord.ts
src/panel/views/settings/components/interface/discord-channel.vue
src/panel/views/settings/interface.vue

Also added partials and intents to properly cache channels

fix(discord): add selector for channels in ui

---

src/bot/oauth.ts

fix(oauth): log proper error on validation

---

src/bot/message.ts
src/bot/systems/raffles.ts

refactor: remove console.log

---

src/bot/customvariables.ts
src/bot/registries/text.ts
src/bot/systems/alias.ts
test/tests/alias/#3738_alias_should_trigger_commands_by_variable.js

fix(alias): variables should be properly parsed as commands

---

locales/en/ui/integrations/discord.json
src/bot/database/entity/discord.ts
src/bot/database/migration/mysql/1589457395923-discordAddId.ts
src/bot/database/migration/postgres/1589457395923-discordAddId.ts
src/bot/database/migration/sqlite/1589457395923-discordAddId.ts
src/bot/database/migration/sqlite/1589457395923-discordNameToId.ts
src/bot/integrations/discord.ts
src/panel/components/loading.vue
src/panel/views/settings/components/interface/discord-mapping.vue
src/panel/views/settings/interface.vue

Fixes https://community.sogebot.xyz/t/add-group-mapping-on-discord/108

feat(discord): add permission to role mapping

---

src/bot/api.ts

perf(api): process full scale follower check in chunks

---

docs/_master/howto/run-bot-in-cluster.md
docs/howto/run-bot-in-cluster.md
src/bot/cluster.ts

fix(cluster): differentiate correctly between main and cluster

---

package.json

build: 11.2.0

---

package.json

build: 11.3.0-SNAPSHOT

---

src/bot/systems/bets.ts

fix(bets): !bet should have default viewers permission

---

src/panel/views/stats/commandcount.vue

fix(ui): load proper dates and commands to show in graph

---

src/panel/views/settings/interface.vue

fix(ui): toggle in permissions should properly change state

---

src/bot/parser.ts

refactor(parser): update debug messages

---

src/bot/tmi.ts

fix(tmi): reinitialize listeners on reconnect

---

src/bot/commons.ts

fix(commons): parser response should log discord

---

src/bot/integrations/discord.ts

fix(discord): simplify send online announcement to channel

---

src/bot/webhooks.ts

fix(webhooks): trigger onStreamStart properly

---

package.json

build: 11.2.1

---

src/bot/microservices/getChannelChattersUnofficialAPI.ts
src/bot/microservices/getUserFromTwitch.ts

fix(microservice): get unknown users in chunk

---

locales/en/ui/integrations/discord.json
src/bot/integrations/discord.ts
src/panel/views/settings/components/interface/discord-guild.vue
src/panel/views/settings/interface.vue

feat(discord): add guild selection where bot should work

---

src/bot/main.ts

fix(main): ignore parse error from twitchjs

---

docker.sh

 chore(docker): profiler is enable by env PROFILER

---

src/bot/customvariables.ts
test/helpers/messages.js
test/tests/customvariable/#3379_customvariable_command_reply.js
test/tests/customvariable/#3737_infinite_script_loop_should_not_lock_bot.js

fix(customvariables): set max operation count for eval

---

locales/en/ui/integrations/discord.json
src/bot/integrations/discord.ts
src/panel/helpers/isUserLoggedIn.ts
src/panel/views/settings/components/interface/toggle-enable.vue
src/panel/views/settings/interface.vue

Added translation and fixed toggle-enable translation title

refactor(discord): update behavior when guild not selected

---

src/bot/games/duel.ts

Fixes https://discordapp.com/channels/317348946144002050/619437014001123338/712345307291320359

fix(duel): new gambler should have correct username

---

src/bot/commons.ts

fix(commons): announce translate usernames to linked ids

---

scss/letter-animations.css
src/bot/data/templates/alerts-with-message.txt
src/bot/registries/alerts.ts
src/overlay/views/alertsRegistry.vue
src/panel/components/media.vue
src/panel/views/registries/alerts/components/animation-in.vue
src/panel/views/registries/alerts/components/animation-out.vue
src/panel/views/registries/alerts/components/form-cheers.vue
src/panel/views/registries/alerts/components/form-follow.vue
src/panel/views/registries/alerts/components/form-hosts.vue
src/panel/views/registries/alerts/components/form-resubs.vue
src/panel/views/registries/alerts/components/text-animation.vue
src/panel/views/registries/alerts/components/tts.vue

Also several fixes to alerts animations after update of animate.css.
Added several new animations in and out
Also fix for media volume.
And fix for opening accordions
Fixes #3783

fix(alerts): add tts to resub message

---

package.json

build: 11.3.0

---

package.json

build: 11.4.0-SNAPSHOT

---

src/panel/components/navbar/menu.vue
src/panel/views/dashboard/dashboard.vue

refactor(ui): reinit socket for menu and dashboard load

---

src/bot/socket.ts
src/panel/helpers/isUserLoggedIn.ts
src/panel/helpers/socket.ts
src/panel/index.ts
src/panel/popout.ts

fix(ui): prevent potential login loop

---

package.json

build: 11.3.1

---

src/bot/systems/moderation.ts
test/tests/moderation/containsLink.js

Fixes https://discordapp.com/channels/317348946144002050/619437014001123338/713323104574898186

fix(moderation): add twitch.tv/<user>/clip/ to clip exclude

---

src/panel/views/settings/components/interface/toggle-enable.vue
src/panel/views/settings/interface.vue

fix(ui): permission based toggles should have correct translation

---

src/overlay/views/alertsRegistry.vue

Fixes https://discordapp.com/channels/317348946144002050/317349069024395264/713333977758433331

fix(overlay): alerts should trigger only available onStarted/onEnded

---

src/overlay/views/alertsRegistry.vue

fix(overlay): add missing bracket

---

src/panel/views/managers/alias/alias-list.vue

fix(alias): accordion should be properly switched

---

docs/_master/howto/connection-to-socket.md

docs: update socket connection

---

src/panel/components/navbar/menu.vue
src/panel/helpers/socket.ts
src/panel/views/dashboard/dashboard.vue

fix(ui): reload full page to load widgets/menu

---

src/panel/views/dashboard/dashboard.vue

refactor(ui): remove interval clear

---

src/panel/components/navbar/menu.vue

refactor(ui): add missing resolve

---

src/panel/helpers/socket.ts

refactor(socket): forceDisconnect reload whole page

---

src/panel/helpers/socket.ts

refactor(socket): reload page if refresh token is incorrect

---

src/bot/socket.ts

refactor(socket): remove listener on init, not on use

---

src/bot/systems/customcommands.ts

This is part of #3702 investigation and try to found cpu usage issue

perf(commands): cache command search

---

d.ts/index.d.ts
src/bot/database/entity/cooldown.ts
src/bot/database/migration/mysql/1590334525683-cooldownRemoveLastTimestamp.ts
src/bot/database/migration/postgres/1590334525683-cooldownRemoveLastTimestamp.ts
src/bot/database/migration/sqlite/1590334525683-cooldownRemoveLastTimestamp.ts
src/bot/parser.ts
src/bot/systems/cooldown.ts
src/panel/views/managers/cooldowns/cooldowns-edit.vue
test/helpers/user.js
test/tests/cooldowns/#3720_cooldown_should_be_properly_reverted.js

This is part of #3702 investigation and try to found cpu usage issue

perf(cooldown): affected cooldowns should be cached for rollback

---

src/bot/socket.ts

[skip-tests]
This was added by 82c3566e959ea3878599836745f25c2b020603a0

refactor(socket): remove additional removeAllListeners

---

src/bot/integrations/spotify.ts

refactor(spotify): emit api.stats for refreshTokens

---

src/panel/views/settings/components/interface/command-input-with-permission.vue
src/panel/views/settings/components/interface/discord-mapping.vue
src/panel/views/settings/components/permissions/list.vue
src/panel/views/settings/permissions.vue

refactor(ui): add missing err

---

package-lock.json
package.json
src/bot/customvariables.ts
test/tests/customvariable/#3820_for_loop_should_work_correctly.js

fix(customvariables): ensure opCounter after end ; only

---

src/panel/views/registries/custom-variables/custom-variables-edit.vue

Fixes https://discordapp.com/channels/317348946144002050/619437014001123338/715106004894744588
[skip-tests]

refactor(ui): fix incorrect emit nsp

---

src/panel/views/settings/components/interface/btn-emit.vue

[skip-tests]
Fixes https://discordapp.com/channels/317348946144002050/619437014001123338/715489046419210271

fix(ui): btn-emit should have proper callback

---

src/bot/message.ts
src/bot/systems/customcommands.ts
test/tests/commands/discord#715206737908465775_custom_commands_can_be_called_from_custom_command.js

fix(customcommands): run custom command in custom command

---

package.json

build: 11.3.2

---

package.json

build: 11.3.3

---

package-lock.json
package.json

chore(package): revert webpack-cli+clean-webpack-plugin deletion

---

webpack.config.js

chore(webpack): remove progress plugin

---

src/bot/systems/cooldown.ts
test/tests/cooldowns/check_should_not_loop.js

perf(cooldown): add additional check to not fall into endless loop

---

locales/en/integrations/discord.json
src/bot/integrations/discord.ts

fix(discord): responses to locales

---

src/bot/microservices/getChannelChattersUnofficialAPI.ts
src/bot/oauth.ts
src/bot/tmi.ts

refactor(tmi): remove listeners before part/reconnect

---

src/bot/oauth.ts

refactor(oauth): fix incorrect refresh token check

---

src/bot/integrations/discord.ts

refactor(discord): fix incorrect locale path

---

src/bot/_interface.ts

refactor(interface): fix null check for perm-based settings

---

src/bot/registries/text.ts
src/panel/views/registries/text-overlay/text-overlay-edit.vue

Fixes https://discordapp.com/channels/317348946144002050/619437014001123338/715985526087483453

fix(ui): load proper item by id

---

locales/cs/integrations/discord.json
locales/de/integrations/discord.json
locales/en/integrations/discord.json
locales/ru/integrations/discord.json
locales/uk/integrations/discord.json
src/bot/integrations/discord.ts

Fixes https://cdn.discordapp.com/attachments/619437014001123338/715964288581500959/unknown.png

refactor(discord): fix incorrect locales

---

src/bot/cluster.ts
src/bot/commons.ts
src/bot/decorators.ts
src/bot/games/fightme.ts
src/bot/games/roulette.ts
src/bot/games/seppuku.ts
src/bot/systems/moderation.ts
src/bot/systems/songs.ts
src/panel/views/settings/interface.vue

fix(moderation): remove CASTERS and timeout MODS as broadcaster

---

src/bot/api.ts
src/bot/cluster.ts
src/bot/twitch.ts

fix(cluster): run several API in cluster mode

---

src/bot/socket.ts

Fixes https://discordapp.com/channels/317348946144002050/619437014001123338/717326051025616928

fix(socket): on incorrect authorize disconnect only affected socket

---

src/panel/helpers/translate.ts

Fixes https://discordapp.com/channels/317348946144002050/619437014001123338/716087581065871411

fix(ui): return correct translation

---

package.json

build: 11.4.0

---

package.json

build: 11.5.0-SNAPSHOT

---

locales/en/ui/core/permissions.json
src/bot/database/entity/permissions.ts
src/bot/helpers/permissions.ts
src/bot/permissions.ts
src/bot/users.ts
src/panel/views/settings/components/permissions/filters.vue

Fixes #3855
Fixes https://community.sogebot.xyz/t/add-followtime-to-permissions-filters/116

feat(permissions): add followTime filter

---

src/bot/socket.ts

fix(socket): check caster permission directly

---

src/bot/users.ts
src/panel/components/navbar/user.vue

fix(ui): return proper permission group for user

---

src/bot/_interface.ts
src/bot/parser.ts

fix(interface): inherit proper values for permission based settings

---

package.json

build: 11.5.0

---

src/bot/integrations/spotify.ts
src/oauth/spotify.vue

Fixes https://discordapp.com/channels/317348946144002050/317349069024395264/718370052247912498

fix(spotify): set correct emit events to user auth

---

package.json

build: 11.6.0

---

package.json

build: 11.7.0-SNAPSHOT

---

src/bot/panel.ts

Fixes https://discordapp.com/channels/317348946144002050/619437014001123338/719219951617179700

fix(panel): show public menu

---

src/bot/games/heist.ts

fix(heist): show correct number of count of more winners

---

src/overlay/views/randomizer.vue

fix(randomizer): trigger TTS after simple random

---

src/bot/customvariables.ts
src/panel/views/registries/custom-variables/custom-variables-edit.vue
test/helpers/user.js
test/tests/customvariable/#3879_eval_should_trigger_with_param.js

fix(customvariables): add permcheck to eval script get

---

src/panel/views/registries/randomizer/randomizer-edit.vue

fix(randomizer): command is optional

---

scss/custom.scss
src/panel/views/registries/randomizer/randomizer-edit.vue

feat(randomizer): add button to generate new color

---

locales/en/ui/registry/goals.json
src/bot/database/entity/goal.ts
src/bot/database/entity/randomizer.ts
src/overlay/views/goals.vue
src/overlay/views/randomizer.vue
src/panel/components/font.vue
src/panel/views/registries/alerts/components/form-cheers.vue
src/panel/views/registries/alerts/components/form-follow.vue
src/panel/views/registries/alerts/components/form-hosts.vue
src/panel/views/registries/alerts/components/form-resubs.vue
src/panel/views/registries/goals/goals-edit.vue
src/panel/views/registries/randomizer/randomizer-edit.vue

refactor(ui): make common font component

---

src/overlay/views/randomizer.vue

fix(randomizer): use correct font in wheel

---

package-lock.json
src/panel/widgets/components/chat.vue
src/panel/widgets/components/twitch.vue

fix(ui): add parent for twitch embed

---

package.json

build: 11.7.0

---

package.json

build: 11.8.0-SNAPSHOT

---

src/panel/widgets/components/chat.vue
src/panel/widgets/components/twitch.vue
src/public/components/twitch.vue

fix(ui): add https warning for twitch embeds

---

src/panel/components/font.vue

feat(ui): add font example

---

locales/en/ui.dialog.json
src/bot/database/entity/randomizer.ts
src/bot/database/migration/mysql/1592306602058-addPositionToRandomizer.ts
src/bot/database/migration/postgres/1592306602058-addPositionToRandomizer.ts
src/bot/database/migration/sqlite/1592306602058-addPositionToRandomizer.ts
src/overlay/views/randomizer.vue
src/panel/components/position.vue
src/panel/views/registries/randomizer/randomizer-edit.vue

feat(ui): add position to simple randomizer

---

src/overlay/views/randomizer.vue

refactor(overlay): add null check for element child

---

src/overlay/views/alertsRegistry.vue
src/overlay/views/goals.vue
src/overlay/views/randomizer.vue
src/panel/components/font.vue
src/panel/helpers/text.ts

refactor(ui): merge duplicated functions

---

src/bot/database/migration/mysql/1592557005213-fontMissingShadow.ts
src/bot/database/migration/postgres/1592557005213-fontMissingShadow.ts
src/bot/database/migration/sqlite/1592557005213-fontMissingShadow.ts

chore(migration): add font shadow where missing

---

src/bot/widgets/eventlist.ts

fix(eventlist): resend event should trigger correct alert

---

src/bot/api.ts

refactor(api): search game with new api

---

docs/_master/faq.md
docs/faq.md
src/bot/message.ts

refactor(message): use new search channel api

---

src/panel/views/stats/api.vue

refactor(stats): remove kraken from stats

---

src/bot/api.ts
src/bot/events.ts
src/bot/message.ts
src/bot/oauth.ts
src/bot/systems/commercial.ts
src/bot/webhooks.ts
src/panel/components/statsbar/statsbar.vue

refactor(api): use new channel helix api

---

src/bot/api.ts

refactor(api): call getChannelInformation only when offline

---

test/tests/alias/run.js
test/tests/cooldowns/check.js
test/tests/games/duel.js

test: disable systems after use

---

src/bot/helpers/panel.ts
src/bot/panel.ts

refactor(ui): error on self-signed generate and disable https init

---

package.json

build: 11.8.0

---

package.json

build: 11.9.0-SNAPSHOT

---

src/panel/index.ts
src/panel/views/dashboard/empty.vue

fix(dashboard): page change should not refresh board

---

src/bot/database/migration/mysql/1592557005214-fontMissingShadow.ts
src/bot/database/migration/postgres/1592557005214-fontMissingShadow.ts
src/bot/database/migration/sqlite/1592557005214-fontMissingShadow.ts

fix(migration): add missing shadow property for goal

---

package.json

build: 11.8.1

---

src/bot/customvariables.ts
src/bot/message.ts

fix(customvariables): set value should contain source

---

locales/en.json
src/bot/api.ts

fix(api): trigger game/title change on new API

---

package.json

build: 11.8.2

---

src/panel/widgets/components/eventlist.vue

Fixes https://discordapp.com/channels/317348946144002050/619437014001123338/727037960226340936

fix(ui): eventlist community gift should have replaced $count

---

src/bot/integrations/discord.ts

fix(discord): !unlink should comply to deleteMessagesAfterWhile

---

package.json

build: 11.8.3

---

locales/en/integrations/discord.json

fix(locales): typo in discord linking

---

d.ts/eventlist.d.ts
src/bot/database/entity/eventList.ts
src/bot/database/migration/mysql/1593591475193-eventlistIsTestAttr.ts
src/bot/database/migration/postgres/1593591475193-eventlistIsTestAttr.ts
src/bot/database/migration/sqlite/1593591475193-eventlistIsTestAttr.ts
src/bot/integrations/streamlabs.ts
src/bot/message.ts
src/bot/overlays/eventlist.ts
src/panel/widgets/components/eventlist.vue
test/tests/message/discord#706756329204613160_latest_variable_are_not_correct.js

fix(eventlist): add isTest attribute to exclude from lists

---

src/bot/tmi.ts

Fixes https://community.sogebot.xyz/t/event-listener-triggered-on-command-not-firing/134/2

fix(tmi): trigger keyword/command send x times every time

---

package.json

build: 11.8.4

---

src/bot/integrations/discord.ts

fix(discord): persist embed on restart

---

src/bot/systems/songs.ts

fix(songs): update deprecated object attributes

---

src/panel/components/statsbar/statsbar.vue

feat(ui): statsbar remember hideStats state

---

scss/custom.scss
src/bot/api.ts
src/bot/integrations/spotify.ts
src/bot/integrations/streamlabs.ts
src/bot/systems/commercial.ts
src/bot/systems/highlights.ts
src/panel/views/stats/api.vue

feat(ui): add request data to api stats table

---

.eslintrc.json
src/bot/database/entity/randomizer.ts
src/bot/database/migration/mysql/1594219451231-randomizerItemOrderAttribute.ts
src/bot/database/migration/postgres/1594219451231-randomizerItemOrderAttribute.ts
src/bot/database/migration/sqlite/1594219451231-randomizerItemOrderAttribute.ts
src/bot/helpers/socket.ts
src/bot/registries/alerts.ts
src/overlay/views/randomizer.vue
src/panel/views/registries/alerts/alerts-list.vue
src/panel/views/registries/custom-variables/custom-variables-list.vue
src/panel/views/registries/goals/goals-list.vue
src/panel/views/registries/randomizer/randomizer-edit.vue
src/panel/views/registries/randomizer/randomizer-list.vue
src/panel/views/registries/text-overlay/text-overlay-list.vue

Cloning for registries WIP

---

src/bot/commons.ts

fix(commons): announce should not send test message

---

package.json

build: 11.9.0

---

package.json

build: 11.10.0-SNAPSHOT

---

src/bot/systems/alias.ts

Fixes https://discordapp.com/channels/317348946144002050/619437014001123338/731028981201109004

fix(alias): properly run aliased custom command

---

src/panel/views/settings/components/interface/toggle-enable.vue

fix(ui): missing title translation for toggle-enable component

---

src/bot/games/heist.ts

fix(heist): add more responses to general announce

---

src/bot/commons.ts

fix(commons): uncomment discord announce

---

package.json

build: 11.9.1

---

docs/_master/filters/all.md
docs/_master/systems/custom-commands.md
locales/en.json
src/bot/events.ts
src/bot/integrations/discord.ts
src/bot/message.ts
src/bot/systems/customcommands.ts
src/bot/tmi.ts
src/panel/views/managers/commands/commands-edit.vue

Community 146

---

src/bot/events.ts
src/bot/integrations/twitter.ts

when used with other operations
Fixes https://community.sogebot.xyz/t/event-listener-operations-issues/151

fix(events): twitter message should be properly parsed

---

docs/_master/install-and-upgrade.md
docs/install-and-upgrade.md

docs(install): add bot as editor in steps

---

src/bot/integrations/twitter.ts

Fixes https://discordapp.com/channels/317348946144002050/619437014001123338/735813554732531724

fix(twitter): unshadow error variable

---

src/bot/oauth.ts

fix(oauth): add channel:edit:commercial scope for bot & broadcaster

---

src/bot/oauth.ts

fix(oauth): add channel:edit:commercial scope for broadcaster

---

src/bot/api.ts
src/bot/events.ts
src/bot/systems/commercial.ts

This is workaround for editor not working in new API.
Fixes https://discordapp.com/channels/317348946144002050/619437014001123338/735813017908019222

fix(commercial): use broadcaster account to run commercial

---

package.json

build: 11.10.0

---

package.json

build: 11.11.0-SNAPSHOT

---

docs/_master/integrations/twitter.md
docs/integrations/twitter.md

docs(twitter): fix link

---

src/overlay/views/eventlist.vue

fix(eventlist): display GET attribute should not be ignored

---

src/bot/integrations/twitter.ts

refactor(twitter): revert missing secretToken

---

locales/en/ui/integrations/spotify.json
src/bot/integrations/spotify.ts
src/bot/systems/customcommands.ts

feat(spotify): toggle queue when offline

---

src/bot/integrations/spotify.ts

fix(spotify): use next track endpoint for skip

---

docs/integrations/spotify.md
locales/en/integrations/spotify.json
locales/en/ui.menu.json
src/bot/database/entity/spotify.ts
src/bot/database/migration/mysql/1596014060721-spotifyBanList.ts
src/bot/database/migration/postgres/1596014156038-spotifyBanList.ts
src/bot/database/migration/sqlite/1595974777207-spotifyBanList.ts
src/bot/integrations/spotify.ts
src/panel/index.ts
src/panel/views/managers/spotify/spotify-bannedsongs.vue

feat(spotify): add ban and unban commands

---

package.json

build: 11.11.0

---

package.json

build: 11.12.0-SNAPSHOT

---

src/bot/helpers/socket.ts
src/panel/views/dashboard/dashboard.vue

Fixes issue introduced by ccb3429498900f14d182e0b9bc0b7a6f2a56f7ac after vue-grid-layout dependency update

refactor(dashboard): fix widget duplication on page load

---

src/bot/registries/alerts.ts

refactor(alerts): update send(status) to sendStatus(status)

---

package-lock.json
package.json

Fixes #4025
Fixes #4023
Fixes #4022

refactor: revert css-loader dependency

---

src/login/index.ts

perf(login): remove unused imports

---

src/panel/helpers/text.ts

fix(text): shadowGenerator should work with undefined shadow

---

src/login/index.ts
src/login/views/login.vue
src/overlay/index.ts
src/overlay/views/clips.vue
src/overlay/views/credits.vue
src/overlay/views/goals.vue
src/overlay/views/randomizer.vue
src/overlay/views/stats.vue
tsconfig.json
webpack.config.js

perf(ui): tree-shaking for webpack

---

locales/en.json
src/bot/events.ts
src/bot/main.ts
src/bot/oauth.ts
src/bot/pubsub.ts
src/bot/tmi.ts

feat(pubsub): add channel points redemption listener

---

locales/en.json
locales/en/ui/integrations/discord.json
src/bot/integrations/discord.ts

added discord status change depends on stream status
added toogle for this feature
added dropdown for default bot status

feat(discord): add change online status on stream live and event listener

---

src/bot/games/gamble.ts
test/tests/games/gambleWithJackpot.js

Fixes https://community.sogebot.xyz/t/points-after-the-decimal-point/158

fix(gamble): properly compute jackpotValue

---

src/bot/twitch.ts

Fixes https://community.sogebot.xyz/t/wrong-time-format/163

fix(time): bot lang set locale of time

---

src/bot/systems/moderation.ts

Fixes https://community.sogebot.xyz/t/no-messages-after-translation/168

fix(moderation): delete messages even if announce is silent

---

src/panel/views/settings/interface.vue

fix(settings): show inherited value if changed

---

src/bot/systems/points.ts

Fixes https://community.sogebot.xyz/t/wrong-sorting-top-points/166

fix(points): remove broadcaster from order

---

package.json

build: 11.12.0

---

package.json

build: 11.13.0-SNAPSHOT

---

src/bot/pubsub.ts

fix(pubsub): throw correct error if bad auth is triggered

---

package.json

build: 11.12.1

---

src/bot/pubsub.ts

fix(pubsub): register change in auth and reconnect

---

src/panel/views/managers/alias/alias-list.vue

Fixes https://community.sogebot.xyz/t/unsaved-visibility/174

fix(alias): propagate alias change on list page

---

locales/en.json
locales/en/ui.errors.json
src/panel/components/navbar/navbar.vue
src/panel/components/navbar/user.vue
src/panel/components/statsbar/statsbar.vue
src/panel/widgets/components/bets.vue
src/panel/widgets/components/chat.vue
src/panel/widgets/components/cmdboard.vue
src/panel/widgets/components/commercial.vue
src/panel/widgets/components/customvariables.vue
src/panel/widgets/components/eventlist.vue
src/panel/widgets/components/join.vue
src/panel/widgets/components/part.vue
src/panel/widgets/components/queue.vue
src/panel/widgets/components/raffles.vue
src/panel/widgets/components/randomizer.vue
src/panel/widgets/components/social.vue
src/panel/widgets/components/soundboard.vue
src/panel/widgets/components/spotify.vue
src/panel/widgets/components/twitch.vue
src/panel/widgets/components/ytplayer.vue

Fixes https://community.sogebot.xyz/t/missing-translation/172

chore(locale): add several missing strings

---

locales/en.json

refactor(locales): revert removed strings

---

package.json

build: 11.12.2

---

src/bot/integrations/spotify.ts

fix(spotify): use correct locale if requested song is banned

---

src/bot/oauth.ts

Fixes https://community.sogebot.xyz/t/hype-train-api-scope-not-authenticating-properly/175

fix(oauth): remove hype train from expected scopes

---

package.json

build: 11.12.3

---

src/bot/commons.ts
src/bot/integrations/discord.ts
src/bot/tsconfig.json

Fixes https://discordapp.com/channels/317348946144002050/317349069024395264/749271927582883850

fix(discord): parse attributes in event

---

src/panel/components/loading.vue
src/panel/index.ts
src/panel/popout.ts

refactor(loading): move to composition api

---

src/bot/customvariables.ts
test/tests/customvariable/#4083_get_url_on_eval_should_return_correct_value.js

fix(customvariables): ignore empty opts on eval

---

locales/en.json
src/bot/games/gamble.ts
test/tests/games/gamble.js
test/tests/games/gambleWithJackpot.js

Fixes https://community.sogebot.xyz/t/jackpot-command/170

feat(gamble): add !gamble jackpot command

---

src/bot/message.ts

Fixes https://discordapp.com/channels/317348946144002050/317349069024395264/752506646944546868

fix(message): parse correctly stream response filter

---

package.json

build: 11.13.0

---

package.json

build: 11.14.0-SNAPSHOT

---

src/bot/events.ts
src/bot/helpers/attributesReplace.ts
src/bot/integrations/discord.ts
src/bot/integrations/twitter.ts
test/tests/events/discord#752632256270696478_incorrect_parse_of_attrs.js

Fixes https://discordapp.com/channels/317348946144002050/317349069024395264/752630164248199249

fix(events): swap sort order for attributes

---

src/panel/views/managers/events/edit.vue

Fixes https://discordapp.com/channels/317348946144002050/317349069024395264/752656766634033154

fix(events): show editation if operations missing

---

package.json

build: 11.13.1

---

src/panel/views/managers/commands/commands-list.vue

Fixes https://community.sogebot.xyz/t/sort-the-chat-commands/180

fix(commands): table should sort by count

---

src/panel/components/statsbar/statsbar.vue

Fixes https://discordapp.com/channels/317348946144002050/317349069024395264/752680563051331584

fix(statsbar): toast content should be displayed

---

docs/_master/integrations/spotify.md
locales/en/integrations/spotify.json
src/bot/helpers/commandError.ts
src/bot/integrations/spotify.ts

Fixes https://community.sogebot.xyz/t/view-spotify-song-history/181

feat(spotify): add !spotify history command

---

src/panel/views/managers/alias/alias-list.vue

Fixes https://discordapp.com/channels/317348946144002050/317349069024395264/752671511235657839

feat(alias): disband whole group button

---

d.ts/index.d.ts
locales/en/ui/integrations/discord.json
src/bot/_interface.ts
src/bot/commons.ts
src/bot/customvariables.ts
src/bot/events.ts
src/bot/games/duel.ts
src/bot/games/heist.ts
src/bot/integrations/discord.ts
src/bot/systems/bets.ts
src/bot/systems/polls.ts
src/bot/systems/raffles.ts
src/bot/systems/scrim.ts
src/bot/systems/songs.ts
src/bot/systems/timers.ts
src/panel/views/settings/components/interface/discord-channel.vue

Fixes https://discordapp.com/channels/317348946144002050/317349069024395264/752897684469448754

feat(discord): granular announces channel settings

---

locales/en/integrations/discord.json
src/bot/integrations/discord.ts

!link and !unlink is dynamically get to get proper command
set in UI settings.
Fixes #4103

fix(discord): add locale and dynamic command

---

src/bot/integrations/spotify.ts

feat(spotify): expose search request to api stats

---

src/bot/api.ts

fix(api): encode game names to work in URI

---

src/bot/database/entity/dashboard.ts
src/bot/database/migration/mysql/1600098861779-dashboardUniqueIndice.ts
src/bot/database/migration/postgres/1600098861779-dashboardUniqueIndice.ts
src/bot/database/migration/sqlite/1600098861779-dashboardUniqueIndice.ts

fix(dashboard): add unique indice to prevent duplicates

---

src/panel/components/dialog/changegamedialog.vue

refactor(ui): fix undefined titles send to cleanup

---

src/panel/components/stateButton.vue
src/panel/components/textareaWithTags.vue
src/panel/views/managers/alias/alias-edit.vue
src/panel/views/managers/alias/alias-list.vue

refactor(alias): move to composition api

---

src/panel/components/textWithTags.vue
src/panel/helpers/getPermissionName.ts
src/panel/helpers/socket.ts
src/panel/views/managers/alias/alias-edit.vue
src/panel/views/managers/alias/alias-list.vue
src/panel/views/managers/commands/commands-edit.vue
src/panel/views/managers/commands/commands-list.vue

refactor(commands): move to composition api

---

src/panel/components/statsbar/statsbar.vue
src/panel/helpers/error.ts
src/panel/views/managers/alias/alias-edit.vue
src/panel/views/managers/alias/alias-list.vue
src/panel/views/managers/commands/commands-edit.vue
src/panel/views/managers/commands/commands-list.vue
src/panel/views/managers/cooldowns/cooldowns-edit.vue
src/panel/views/managers/cooldowns/cooldowns-list.vue

refactor(cooldowns): move to composition api

---

src/panel/components/panel.vue
src/panel/components/stateButton.vue
src/panel/views/managers/events/edit.vue
src/panel/views/managers/events/list.vue

refactor(events): move to composition api

---

src/login/index.ts
src/login/views/login.vue
src/oauth/index.html

fix(oauth): redirect should point to correct url if logged in popout

---

src/public/index.ts

fix(public): login should be voluntary

---

src/panel/views/managers/songs/songs-playlist.vue

fix(ui): show correct import/skip information

---

src/bot/systems/moderation.ts
test/tests/moderation/containsLink.js

Fixes https://community.sogebot.xyz/t/links-detection/183

fix(moderation): use unicode word boundary for link regex

---

docs/_master/filters/all.md
locales/en/ui.menu.json
locales/en/ui/integrations/pubg.json
src/bot/helpers/socket.ts
src/bot/integrations/pubg.ts
src/bot/message.ts
src/panel/components/statsbar/statsbar.vue
src/panel/helpers/variant.ts
src/panel/views/settings/components/interface/pubg-customization.vue
src/panel/views/settings/components/interface/pubg-player-id.vue
src/panel/views/settings/components/interface/pubg-season-id.vue
src/panel/views/settings/components/interface/pubg-stats.vue
src/panel/views/settings/interface.vue
test/tests/message/discord#706756329204613160_latest_variable_are_not_correct.js
test/tests/message/random.js
test/tests/message/toFloat.js
test/tests/message/toPercent.js

feat(pubg): add new pubg integration

---

locales/en/integrations/pubg.json
src/bot/integrations/pubg.ts

refactor(pubg): missing expected parameter locale

---

src/panel/components/font.vue

fix(ui): properly populate font list

---

src/overlay/views/alertsRegistry.vue

fix(alerts): cast amount to string

---

src/overlay/views/alertsRegistry.vue

fix(alerts): guard undefined alert

---

src/overlay/views/alertsRegistry.vue

fix(alerts): missing " after setting image style

---

src/login/views/login.vue
src/panel/components/navbar/user.vue
src/panel/helpers/isUserLoggedIn.ts
src/panel/helpers/socket.ts

refactor(login): use assign instead of replace to keep history

---

src/bot/oauth.ts

fix(oauth): add retry on validation if different than 401

---

src/bot/twitch.ts

Fixes https://discordapp.com/channels/317348946144002050/619437014001123338/759142040834670624

fix(twitch): !game set should pick exact match if available

---

locales/en/ui.systems.raffles.json
src/bot/systems/raffles.ts

feat(raffles): add raffle announce message interval

---

locales/en/ui.systems.cooldown.json
src/bot/systems/cooldown.ts
test/tests/cooldowns/check_default_values.js

Fixes https://community.sogebot.xyz/t/add-input-what-will-set-default-cooldown-for-all-commands-but-leave-the-opportunity-to-change/66

feat(cooldown): add default cooldowns settings

---

src/bot/systems/moderation.ts

fix(moderation): purge warnings by correct timestamp

---

src/bot/commons.ts
src/bot/customvariables.ts
src/bot/helpers/getTime.ts
src/bot/helpers/socket.ts
src/bot/overlays/stats.ts
src/bot/panel.ts
src/bot/twitch.ts
src/panel/components/dialog/changegamedialog.vue
src/panel/components/statsbar/statsbar.vue
src/panel/helpers/store.ts

fix(panel): send stats only on change

---

src/bot/api.ts

refactor(api): update errors logging

---

d.ts/eventlist.d.ts
src/bot/api.ts
src/bot/database/entity/eventList.ts
src/bot/database/migration/mysql/1601124530399-eventListUserId.ts
src/bot/database/migration/postgres/1601124530399-eventListUserId.ts
src/bot/database/migration/sqlite/1601124530399-eventListUserId.ts
src/bot/integrations/donationalerts.ts
src/bot/integrations/qiwi.ts
src/bot/integrations/streamelements.ts
src/bot/integrations/streamlabs.ts
src/bot/integrations/tipeeestream.ts
src/bot/message.ts
src/bot/overlays/eventlist.ts
src/bot/tmi.ts
src/bot/twitch.ts
src/bot/users.ts
src/bot/webhooks.ts
src/bot/widgets/eventlist.ts
src/panel/views/managers/viewers/viewers-edit.vue
test/tests/message/discord#706756329204613160_latest_variable_are_not_correct.js
test/tests/twitch/followers.js
test/tests/twitch/subs.js

Fixes #3650
missing migrations for postgre and mysql

fix(eventlist): use userId instead of username

---

src/bot/database/entity/eventList.ts
src/bot/database/migration/mysql/1601297968526-eventListIsHiddenAttr.ts
src/bot/database/migration/postgres/1601297968526-eventListIsHiddenAttr.ts
src/bot/database/migration/sqlite/1601297968526-eventListIsHiddenAttr.ts
src/bot/widgets/eventlist.ts

This will ensure we still keep all data for users
Fixes #3653

fix(eventlist): cleanup of events just hides from widget

---

src/panel/views/managers/alias.vue

Fixes https://discordapp.com/channels/317348946144002050/317348946144002050/760315087042248714

fix(alias): fix link to create new alias

---

src/panel/views/settings/interface.vue

fix(ui): sort settings list menu

---

locales/en.json
src/bot/expects.ts
src/bot/systems/raffles.ts
test/helpers/messages.js
test/tests/raffles/allowOverTicketing.js
test/tests/raffles/bug#3546.js
test/tests/raffles/bug#3547.js
test/tests/raffles/community#32.js
test/tests/raffles/community#38.js
test/tests/raffles/cumulativeTickets.js
test/tests/raffles/feat#4175_raffleAnnounceShouldContainTotalEntries.js
test/tests/raffles/pick.js
test/tests/raffles/ticketsBoundaries.js

feat(raffles): add entries count to announcement

---

locales/en.json
locales/en/ui.systems.raffles.json
src/bot/cluster.ts
src/bot/systems/raffles.ts
src/panel/widgets/components/raffles.vue
test/tests/raffles/allowOverTicketing.js
test/tests/raffles/bug#3546.js
test/tests/raffles/bug#3547.js
test/tests/raffles/bug#3587.js
test/tests/raffles/community#32.js
test/tests/raffles/community#38.js
test/tests/raffles/cumulativeTickets.js
test/tests/raffles/feat#4176_raffleAnnounceShouldContainDeleteInfo.js
test/tests/raffles/pick.js
test/tests/raffles/ticketsBoundaries.js

If enabled, join commands will be deleted
Fixes #4176

feat(raffles): toggle raffle command chat delete

---

src/bot/pubsub.ts

fix(pubsub): add error for failed ping

---

src/bot/helpers/socket.ts
src/bot/registries/alerts.ts
src/panel/views/registries/alerts/alerts-list.vue
src/panel/widgets/components/eventlist.vue

Added toggle to enable/disable alerts
Fixes #4179

feat(alerts): add alert toggle to registry and eventlist

---

src/overlay/views/alertsRegistry.vue

Discord 762472195536060438

---

src/bot/systems/raffles.ts
test/tests/raffles/feat#4174_announceEntriesIfSet.js

fix(raffles): use correct locale for entries

---

src/bot/database/migration/mysql/1601124530399-eventListUserId.ts

Fixes https://discordapp.com/channels/317348946144002050/317349069024395264/763026097565728798

fix(migration): use correct object types in data insert

---

src/bot/database/entity/poll.ts
src/bot/database/migration/mysql/1602070380846-pollIsOpenedIdx.ts
src/bot/database/migration/postgres/1602070380846-pollIsOpenedIdx.ts
src/bot/database/migration/sqlite/1602070380846-pollIsOpenedIdx.ts

refactor(poll): add index to isOpened

---

docs/_master/systems/polls.md
locales/en/systems/polls.json
locales/en/ui/systems/polls.json
src/bot/database/entity/poll.ts
src/bot/database/migration/mysql/1602070380846-pollIsOpenedIdx.ts
src/bot/database/migration/postgres/1602070380846-pollIsOpenedIdx.ts
src/bot/database/migration/sqlite/1602070380846-pollIsOpenedIdx.ts
src/bot/systems/polls.ts
src/overlay/views/polls.vue
src/panel/views/managers/polls.vue
test/tests/polls/numbers.js

feat(polls): add voting by numbers

---

src/panel/widgets/components/eventlist.vue

fix(eventlist): show 100 items by default in widget

---

docs/_master/systems/custom-commands.md
docs/_master/systems/keywords.md
locales/en.json
locales/en/ui.systems.customcommands.json
locales/en/ui/systems/keywords.json
src/bot/database/entity/keyword.ts
src/bot/database/migration/mysql/1602413333619-keywordMultipleResponses.ts
src/bot/database/migration/postgres/1602413333619-keywordMultipleResponses.ts
src/bot/database/migration/sqlite/1602413333619-keywordMultipleResponses.ts
src/bot/helpers/checkFilter.ts
src/bot/systems/customcommands.ts
src/bot/systems/keywords.ts
src/panel/index.ts
src/panel/views/managers/commands.vue
src/panel/views/managers/keyword.vue
test/tests/keywords/basic_workflow.js
test/tests/keywords/list.js

Fixes https://community.sogebot.xyz/t/filter-option-in-keyswords/190

feat(keywords): multiple responses and filters per keyword

---

src/bot/commons.ts
src/bot/systems/timers.ts
test/tests/timers/bug#4209_custom_command_filter_is_not_triggered.js

fix(commons): use bot data for announce

---

src/bot/api.ts

fix(api): trigger game-changed event on unmatched games

---

package-lock.json
src/panel/views/registries/alerts/alerts-edit.vue
src/panel/views/registries/alerts/components/form-hosts.vue

fix(alerts): remove autohost toggle from alert raid edit

---

src/bot/systems/howlongtobeat.ts

Reset on stream start
Fixes #4217

fix(hltb): search game retry only once

---

src/bot/overlays/emotes.ts

fix(emotes): remove own caching of simple emotes

---

src/overlay/views/emotes.vue

fix(emotes): facebook animation should not end outside of window

---

src/bot/api.ts
src/bot/commons.ts
src/bot/events.ts
src/bot/systems/ranks.ts
src/bot/systems/userinfo.ts
src/bot/tmi.ts

refactor: replace momentjs with dayjs library

---

src/bot/general.ts
src/bot/integrations/discord.ts
src/bot/systems/top.ts
src/bot/systems/userinfo.ts
src/bot/twitch.ts

refactor(dayjs): set global locale on lang load/change

---

src/panel/views/managers/quotes.vue

fix(quotes): expose filteredTags variable

---

d.ts/index.d.ts
src/bot/commons.ts
src/bot/events.ts
src/bot/integrations/discord.ts
src/bot/integrations/pubg.ts
src/bot/message.ts
src/bot/tmi.ts
src/bot/widgets/chat.ts

Fixes https://discordapp.com/channels/317348946144002050/317349069024395264/768216463977873428

fix(events): undefined sender used in runCommand operation

---

src/bot/events.ts
src/bot/systems/commercial.ts

fix(commercial): fix typo in error

---

src/bot/api.ts

fix(api): ignore missing response data

---

src/bot/events.ts

fix(events): trigger only expected reward event

---

locales/en.json
src/bot/events.ts
src/bot/pubsub.ts

Fixes https://community.sogebot.xyz/t/reward-redeemed-user-input/195

feat(events): add userInput to reward-redeemed

---

src/bot/systems/polls.ts

fix(polls): ignore numbers if poll is not running

---

package-lock.json
src/panel/components/loading.vue
src/panel/components/navbar/menu.vue
src/panel/components/navbar/user.vue
src/public/components/navbar/menu.vue
src/public/components/navbar/navbar.vue
src/public/components/twitch.vue
src/public/index.ts
src/public/views/playlist.vue
src/public/views/quotes.vue
src/public/views/songrequests.vue

refactor(public): move to composition api

---

locales/en.json
src/bot/systems/songs.ts
test/tests/songs/addSongToQueue.js

fix(songs): add error locale on unexpected response from YT

---

locales/en.json
src/bot/events.ts
src/bot/helpers/socket.ts
src/bot/pubsub.ts
src/panel/views/managers/events/edit.vue

fix(events): remember redeems and use select input

---

src/bot/helpers/log.ts
src/bot/pubsub.ts

fix(log): log redeem events

---

src/bot/panel.ts
src/bot/systems/top.ts
src/bot/systems/userinfo.ts
src/bot/tsconfig.json
src/overlay/views/credits.vue
src/overlay/views/eventlist.vue
src/overlay/views/goals.vue
src/panel/components/navbar/user.vue
src/panel/components/statsbar/statsbar.vue
src/panel/helpers/socket.ts
src/panel/views/managers/polls.vue
src/panel/views/managers/viewers/viewers-edit.vue
src/panel/views/managers/viewers/viewers-list.vue
src/panel/views/settings/components/permissions/edit.vue
src/panel/views/stats/bits.vue
src/panel/views/stats/tips.vue
src/panel/widgets/components/eventlist.vue
test/tests/keywords/basic_workflow.js
test/tests/permissions/check.js
test/tests/top/time.js
test/tests/top/tips.js
test/tests/userinfo/stats.js
tsconfig.json
webpack.config.js

refactor(intl): use Intl to format currencies and numbers

---

src/panel/components/statsbar/statsbar.vue

refactor(statsbar): fix incorrect formatting and percentage

---

src/bot/stats.ts

fix(stats): send correct initial values for views/flw/sub

---

locales/en/ui/registry/overlays.json
src/bot/database/entity/overlay.ts
src/bot/database/migration/mysql/1604326861945-overlayMapper.ts
src/bot/database/migration/postgres/1604326861945-overlayMapper.ts
src/bot/database/migration/sqlite/1604326861945-overlayMapper.ts
src/bot/overlays/alerts.ts
src/bot/overlays/bets.ts
src/bot/overlays/carousel.ts
src/bot/overlays/clips.ts
src/bot/overlays/clipscarousel.ts
src/bot/overlays/credits.ts
src/bot/overlays/emotes.ts
src/bot/overlays/eventlist.ts
src/bot/overlays/polls.ts
src/bot/overlays/stats.ts
src/bot/overlays/textToSpeech.ts
src/bot/registries/overlays.ts
src/overlay/index.ts
src/overlay/views/_mapper.vue
src/overlay/views/text.vue
src/panel/index.ts
src/panel/views/managers/alias.vue
src/panel/views/registries/overlays.vue
src/panel/views/registries/randomizer/randomizer-edit.vue
src/panel/views/registries/randomizer/randomizer-list.vue
src/panel/views/registries/text-overlay/text-overlay-list.vue

Replaces direct links like /overlays/alert with hashed link to improve
security on public overlays
Fixes #4259

feat(overlays): add overlay link mapping

---

src/panel/views/registries/overlays.vue

refactor(overlays): add link and copy buttons

---

package-lock.json
package.json
src/panel/views/settings/components/interface/uuid-generator.vue

refactor(dependency): remove v-clipboard dependency

---

src/bot/stats.ts

refactor(stats): register as core module

---

locales/en/integrations/spotify.json
locales/en/ui/integrations/spotify.json
src/bot/integrations/spotify.ts
src/bot/translate.ts

Fixes https://community.sogebot.xyz/t/spotify-song-announcement/191

feat(spotify): add toggle notify on song change

---

src/panel/views/registries/randomizer/randomizer-edit.vue

Fixes https://community.sogebot.xyz/t/handler-for-change-ordering-on-randomizer-registry/46

feat(randomizer): add dragging to items to change order

---

src/panel/views/settings/components/interface/textarea-from-array.vue

Fixes https://discordapp.com/channels/317348946144002050/317348946144002050/774583474261721091

fix(ui): expose translate for textarea component

---

package.json
tools/migration.js
tools/mklogdir.js

fix(tools): prestart should properly fail on migration error

---

src/bot/systems/howlongtobeat.ts

After successfull HLTB poll, we should not exclude game from tracking
Fixes #4283

fix(hltb): correctly track new games

---

src/bot/api.ts
src/bot/microservices/getChannelChattersUnofficialAPI.ts

feat(api): use Get Moderators endpoint

---

src/overlay/views/polls.vue
src/panel/views/managers/polls.vue

fix(polls): active for time should have correct format

---

src/bot/systems/polls.ts

fix(polls): send corect message on open/close from UI

---

locales/en/ui.systems.songs.json
src/panel/views/managers/songs/songs-bannedsongs.vue
src/panel/views/managers/songs/songs-playlist.vue
src/panel/views/managers/spotify/spotify-bannedsongs.vue

refactor(spotify): move to composition api

---

src/bot/data/globalIgnoreList.ts

fix(ignorelist): add letsdothis_hostraffle

---

src/bot/helpers/log.ts
src/bot/helpers/socket.ts
src/bot/main.ts
src/bot/panel.ts
src/panel/components/footer.vue

refactor(debug): add debug dialog

---

src/login/views/login.vue

fix(login): fix public page button not redirecting

---

src/bot/microservices/getChannelChattersUnofficialAPI.ts

fix(getChannelChattersUnofficialAPI): correctly exclude ignored users

---

src/bot/api.ts

fix(api): expose getChannelChattersUnofficialAPI to api stats

---

src/bot/message.ts
test/tests/message/random_number.js

Fixes https://discordapp.com/channels/317348946144002050/689472699910717522/776164636533063680

fix(message): fix (random.number-#-to-#) returning only 0

---

Makefile
patches/spotify-http-manager-error-handling.patch

fix(spotify): patch library handle http errors

---

src/bot/tmi.ts

fix(tmi): use correct attribute for month streak

---

src/panel/views/managers/events.vue

refactor(events): clean editationItem on sidebar open

---

src/bot/tmi.ts

fix(tmi): fix subgift being parsed as subscription

---

src/panel/views/registries/alerts/alerts-edit.vue
src/panel/views/registries/alerts/components/form-cheers.vue
src/panel/views/registries/alerts/components/form-follow.vue
src/panel/views/registries/alerts/components/form-hosts.vue
src/panel/views/registries/alerts/components/form-resubs.vue
src/panel/views/registries/alerts/components/form-reward.vue

fix(alerts): properly hook rewards to validation

---

src/overlay/views/alertsRegistry.vue
src/panel/views/registries/alerts/components/tts.vue

fix(tts): handle / as pause when speaking

---

src/panel/components/font.vue
src/panel/components/position.vue
src/panel/views/registries/alerts/alerts-edit.vue
src/panel/views/registries/alerts/components/form-cheers.vue
src/panel/views/registries/alerts/components/form-follow.vue
src/panel/views/registries/alerts/components/form-hosts.vue
src/panel/views/registries/alerts/components/form-resubs.vue
src/panel/views/registries/alerts/components/form-reward.vue
src/panel/views/registries/alerts/components/text-animation.vue
src/panel/views/registries/alerts/components/tts.vue

refactor(alerts): change event tab pills into header pills

---

src/bot/integrations/spotify.ts

fix(spotify): getMe() only if authorized

---

src/panel/views/managers/events.vue

Fixes https://discord.com/channels/317348946144002050/619437014001123338/776963274210017291

fix(events): fix infinite loop on empty events

---

src/bot/integrations/spotify.ts
src/panel/widgets/components/ytplayer.vue

fix(ytplayer): fix missing draggable handler

---

src/bot/api.ts
src/bot/events.ts
src/bot/microservices/getCustomRewards.ts

refactor(getCustomRewards): move to microservice

---

src/bot/systems/ranks.ts
test/tests/ranks/custom.js

Fixes https://discord.com/channels/317348946144002050/619437014001123338/778263373950353429

fix(ranks): fix setting custom rank by username

---

src/bot/database/entity/howLongToBeatGame.ts
src/bot/database/migration/mysql/1605640986450-hltbIdFix.ts
src/bot/database/migration/postgres/1605640986450-hltbIdFix.ts
src/bot/database/migration/sqlite/1605640986450-hltbIdFix.ts

Fixes https://discord.com/channels/317348946144002050/317348946144002050/778314152778792990

fix(hltb): set hltb_id as uuid

---

src/bot/helpers/log.ts
src/bot/helpers/logTypeorm.ts
src/bot/main.ts

refactor(log): add custom typeorm error logger

---

src/panel/helpers/isUserLoggedIn.ts

refactor(isUserLoggedIn): set goto url before login

---

src/login/views/login.vue
src/oauth/index.html
src/panel/helpers/isUserLoggedIn.ts

refactor(login): assign location at login

---

locales/en/ui/core/permissions.json
src/bot/database/entity/permissions.ts
src/bot/database/migration/mysql/1605794954571-changeFilterToString.ts
src/bot/database/migration/postgres/1605794954571-changeFilterToString.ts
src/bot/database/migration/sqlite/1605794954571-changeFilterToString.ts
src/bot/permissions.ts
src/panel/views/settings/components/permissions/filters.vue
test/tests/permissions/check.js

feat(permissions): add filter for ranks

---

src/bot/overlays/eventlist.ts
src/bot/tmi.ts
src/bot/widgets/eventlist.ts
src/panel/views/managers/viewers/viewers-edit.vue
src/panel/widgets/components/eventlist.vue

fix(eventlist): properly link subgift to gifter

---

src/panel/helpers/isUserLoggedIn.ts

fix(isUserLoggedIn): ignore network issues

---

docs/install-and-upgrade.md

docs: update node version

---

src/panel/helpers/isUserLoggedIn.ts

fix(isUserLoggedIn): fix incorrect error check

---

src/panel/views/registries/goals/goals-edit.vue

fix(goals): fix ui locale typo

---

docs/_master/systems/alias.md
locales/en.json
src/bot/systems/alias.ts

feat(alias): add enable/disable by alias group

---

src/bot/integrations/streamlabs.ts

fix(streamlabs): better error message on rest check fail

---

src/bot/stats.ts

fix(stats): persistent cache for some initial values

---

src/bot/inspector.ts
src/bot/main.ts

can be enabled by DEBUG=profiler.<minutes>

refactor: add manual cpu profiler

---

src/panel/views/settings/interface.vue

fix(interface): refresh tab key on change not on input

---

src/panel/views/settings/components/interface/number-input.vue

Fixes https://discord.com/channels/317348946144002050/317349069024395264/780415188192591892

fix(ui): trigger change when using arrow in number input

---

src/bot/systems/bets.ts

Fixes https://discord.com/channels/317348946144002050/619437014001123338/780421574238535730

fix(bets): properly loop bet expire check

---

src/bot/database/entity/user.ts
src/bot/users.ts
src/panel/components/navbar/theme.vue
src/panel/popout.html
src/panel/popout.ts

refactor(popout): save preferred theme of user and save it

---

package-lock.json
package.json
tools/migration.js

refactor(tools): add min semver check for node

---

src/bot/_interface.ts
src/bot/decorators.ts
src/panel/views/settings/components/interface/number-input.vue
src/panel/views/settings/components/interface/text-input.vue
src/panel/views/settings/interface.vue

feat(ui): add several revert to default in settings

---

src/bot/systems/bets.ts
test/tests/bets/discord#781585551005319199_closed_bet_shows_as_opened.js

Fixes https://discord.com/channels/317348946144002050/317349069024395264/781585551005319199

fix(bets): check correctly if bet is running for info and participate

---

src/bot/systems/bets.ts
test/tests/bets/bet_is_properly_closed_with_participants.js
test/tests/bets/bet_is_properly_closed_without_participants.js

Fixes https://discord.com/channels/317348946144002050/317349069024395264/781592601895108668

fix(bets): properly lock bet with participants

---

src/bot/api.ts
src/bot/events.ts
src/bot/microservices/getChannelChattersUnofficialAPI.ts
src/bot/microservices/getCustomRewards.ts
src/bot/oauth.ts

Fixes https://discord.com/channels/317348946144002050/317349069024395264/782072182142140430

fix(getCustomReward): properly persistent channelId

---

d.ts/missingTypes.d.ts
package-lock.json
package.json
src/bot/integrations/streamelements.ts

Fixes https://discord.com/channels/317348946144002050/317349069024395264/782180298698784769

fix(streamelements): fix crash of bot when using socket.io 3

---

src/panel/views/managers/events.vue

fix(events): properly show pending changes dialog

---

locales/en/ui/core/permissions.json

Fixes https://discord.com/channels/317348946144002050/619437014001123338/782947136987463702

fix(permissions): fix typo aceces -> access

---

src/bot/panel.ts
src/panel/components/footer.vue
src/panel/components/navbar/navbar.vue

Fixes https://community.sogebot.xyz/t/name-of-channel-in-top-of-webpage/203

feat(navbar): add channel name

---

src/panel/views/settings/components/interface/command-input-with-permission.vue
src/panel/views/settings/components/interface/cron.vue
src/panel/views/settings/components/interface/text-input.vue
src/panel/views/settings/components/interface/textarea-from-array.vue

fix(ui): properly trigger change on several inputs

---

src/panel/widgets/components/bets.vue
src/panel/widgets/components/cmdboard.vue
src/panel/widgets/components/queue.vue
src/panel/widgets/components/spotify.vue

fix(ui): fix settings emitters use set values

---

src/panel/views/managers/songs/songs-playlist.vue

Fixes https://discord.com/channels/317348946144002050/619437014001123338/783844993747255299

fix(ui): properly remove song from playlist

---

src/bot/expects.ts
src/bot/helpers/parameterError.ts
src/bot/systems/points.ts

Fixes https://discord.com/channels/317348946144002050/619437014001123338/784010409103065090

fix(points): differentiate between parameterError and regular Error

---

locales/en.json
src/bot/systems/customcommands.ts
test/tests/commands/add.js
test/tests/commands/edit.js
test/tests/commands/remove.js
test/tests/commands/run.js
test/tests/commands/toggle.js
test/tests/commands/toggleVisibility.js

Fixes https://discord.com/channels/317348946144002050/619437014001123338/783981744549789706

fix(customcommands): '!command remove' should behave as documented

---

src/bot/api.ts
src/bot/events.ts
src/bot/integrations/discord.ts

refactor(api): getIdFromTwitch return ID or throw Error

---

src/panel/views/settings/translations.vue

Fixes https://discord.com/channels/317348946144002050/317349069024395264/784122959270248488

fix(ui): expose translate() for translation page

---

src/bot/customvariables.ts
src/bot/registries/text.ts
src/overlay/views/text.vue

fix(textoverlay): sort variables by length before replace

---

src/panel/views/settings/components/interface/number-input.vue
src/panel/views/settings/interface.vue

fix(ui):  permission settings should revert correctly

---

locales/en/ui.errors.json
locales/en/ui/registry/textoverlay.json
src/bot/database/entity/text.ts
src/bot/database/migration/mysql/1607215601801-textOverlayRefreshRate.ts
src/bot/database/migration/postgres/1607215601801-textOverlayRefreshRate.ts
src/bot/database/migration/sqlite/1607215601801-textOverlayRefreshRate.ts
src/bot/registries/text.ts
src/overlay/views/text.vue
src/panel/views/registries/text-overlay/text-overlay-edit.vue
src/panel/views/registries/text-overlay/text-overlay-list.vue

feat(textoverlay): adjustable refresh rate of overlay

---

src/bot/decorators.ts
src/bot/systems/moderation.ts
src/panel/views/settings/interface.vue

Unless manually set they should.

feat(moderation): by default moderators are not enforced to obey rules

---

src/bot/commons.ts

fix(commons): mods will be mods again if bot timeout them

---

src/bot/decorators.ts
src/bot/games/gamble.ts

Fixes https://community.sogebot.xyz/t/different-chances-of-winning-for-gamble/212

feat(gamble): set minimal bet, chances to win per permission group

---

src/bot/systems/points.ts

Fixes https://discord.com/channels/317348946144002050/619437014001123338/785586816153550918

fix(points): get points by userId

---

.github/workflows/tests.yml
.gitignore
codecov.yml
package-lock.json
package.json
tools/runTests.js

build: add codecov report

---

src/bot/games/fightme.ts
test/tests/games/fightme.js

test(fightme): add coverage for double challenge

---

src/bot/helpers/sql.ts
test/tests/helpers/sql.js

test(sql): check SQLVariableLimit code coverage

---

src/bot/games/duel.ts
test/helpers/user.js
test/tests/games/duel.js

test(duel): improve duel code coverage

---

Makefile
src/bot/games/duel.ts
src/bot/games/fightme.ts
src/bot/games/gamble.ts
test/tests/games/duel.js
test/tests/games/fightme.js
test/tests/games/seppuku.js

test: extending test coverage

---

src/bot/database/migration/sqlite/1602413333619-keywordMultipleResponses.ts

fix(migration): fix keyword response migration

---

src/bot/registries/alerts.ts
src/panel/components/media.vue

Fixes https://discord.com/channels/317348946144002050/317349069024395264/788481679043592192

fix(ui): alert registry should properly upload media

---

Makefile

Fixes https://discord.com/channels/317348946144002050/619437014001123338/788471974434308177

fix(build): png files should not be gzipped

---

src/panel/views/registries/alerts/alerts-edit.vue

fix(alerts): disable test button if pending changes

---

test/tests/games/gamble.js

test(gamble): add test for all and not enough points

---

src/panel/views/managers/price.vue

Fixes https://discord.com/channels/317348946144002050/619437014001123338/788954717224697887

fix(ui): update configuration path for price list

---

locales/en/ui/registry/alerts.json
src/bot/database/entity/alert.ts
src/bot/database/migration/mysql/1608158764205-messageAlignmentForAlerts.ts
src/bot/database/migration/postgres/1608158764205-messageAlignmentForAlerts.ts
src/bot/database/migration/sqlite/1608158764205-messageAlignmentForAlerts.ts
src/overlay/views/alertsRegistry.vue
src/panel/components/font.vue
src/panel/views/registries/alerts/alerts-edit.vue
src/panel/views/registries/alerts/components/form-cheers.vue
src/panel/views/registries/alerts/components/form-resubs.vue
src/panel/views/registries/alerts/components/form-reward.vue

Fixes https://discord.com/channels/317348946144002050/619437014001123338/788891711618547732

feat(alerts): add align settings

---

scss/custom.scss
src/panel/components/title-divider.vue
src/panel/views/managers/commands.vue
src/panel/views/settings/components/interface/pubg-stats.vue

Fixes https://discord.com/channels/317348946144002050/619437014001123338/788966269583097926

fix(ui): update commands editation to be usable on thinner screens

---

locales/en.json
src/bot/_interface.ts
src/bot/general.ts
src/bot/helpers/socket.ts
src/bot/main.ts
src/bot/panel.ts
src/bot/watchers.ts
src/panel/components/statsbar/statsbar.vue

fix(settings): trigger variable watcher on save

---

src/bot/translate.ts
src/panel/views/settings/translations.vue

Fixes https://discord.com/channels/317348946144002050/317349069024395264/789967635680329751

fix(ui): custom translations should be properly reverted

---

src/panel/views/managers/events-edit.vue
src/panel/views/managers/events.vue

Fixes https://discord.com/channels/317348946144002050/619437014001123338/790299708152872982

fix(ui): events should not hang on loading

---

locales/en.json
src/bot/systems/points.ts
test/tests/points/give.js

fix(points): '!points give' 0 points error message

---

locales/en/ui/overlays/emotes.json
src/bot/overlays/emotes.ts
src/overlay/views/emotescombo.vue

feat(emotes): add inactivity hide for combo emote

---

package-lock.json
src/bot/_interface.ts
src/bot/integrations/streamelements.ts
src/bot/watchers.ts
src/panel/views/settings/components/interface/streamelements-jwt.vue

refactor(streamelements): check jwt token before websocket connection

---

src/bot/message.ts

…line
Fixes https://discord.com/channels/317348946144002050/619437014001123338/790900629303328790

fix(message): stream context variables should force 0 if offline

---

package-lock.json
package.json
src/panel/views/managers/alias.vue
src/panel/views/managers/commands.vue
src/panel/views/managers/cooldowns.vue
src/panel/views/managers/events-edit.vue
src/panel/views/managers/events.vue
src/panel/views/managers/keyword.vue
src/panel/views/managers/price.vue
src/panel/views/managers/quotes.vue
src/panel/views/managers/ranks.vue
src/panel/views/managers/viewers.vue

chore: dependency update

---

locales/en/games.heist.json
src/bot/expects.ts
src/bot/games/heist.ts
test/helpers/db.js
test/helpers/user.js
test/tests/games/heist.js

test(heist): added bankheist tests

---

src/bot/games/heist.ts
test/helpers/messages.js
test/tests/games/heist.js

test(heist): update bankheist tests to extend coverage

---

src/panel/index.ts
src/panel/views/managers/events-edit.vue
src/panel/views/managers/events.vue
src/panel/views/managers/timers/timers-edit.vue
src/panel/views/managers/timers/timers-list.vue

refactor(timers): update to composition API

---

src/bot/overlays/gallery.ts
src/panel/components/button.vue
src/panel/components/navbar/theme.vue
src/panel/views/managers/events-edit.vue
src/panel/views/registries/gallery/gallery-list.vue

Added multiple files to upload
Fixes https://community.sogebot.xyz/t/multiply-gallery-file-upload/103
Fixes https://discord.com/channels/317348946144002050/619437014001123338/791558723155394590

fix(gallery): upload files in chunks

---

src/bot/systems/points.ts

fix(points): properly add points to user by calculated modifier

---

src/bot/database/migration/mysql/1608945825341-extraLevelsReset.ts
src/bot/database/migration/postgres/1608945825341-extraLevelsReset.ts
src/bot/database/migration/sqlite/1608945825341-extraLevelsReset.ts
src/bot/systems/levels.ts

fix(levels): properly initiate levels in database

---

locales/en/systems/commercial.json
src/bot/events.ts
src/bot/systems/commercial.ts

fix(commercial): log error given from Twitch API

---

docs/_master/filters/all.md
src/bot/api.ts
src/bot/events.ts
src/bot/helpers/checkFilter.ts
src/bot/helpers/isBot.ts
src/bot/message.ts

Fixes https://community.sogebot.xyz/t/add-command-filter-is-bot-sub/225

feat(filters): add $isBotSubscriber to global variables

---

src/bot/api.ts
src/bot/helpers/isBot.ts
src/bot/helpers/isBroadcaster.ts

Fixes https://discord.com/channels/317348946144002050/619437014001123338/792563945776480286

fix(api): check properly bot sub status by userId

---

locales/en/ui.dialog.json
locales/en/ui/registry/alerts.json
src/panel/components/media.vue

Fixes https://community.sogebot.xyz/t/video-volume-control/230

fix(ui): set volume for video in media component

---

src/panel/views/managers/commands.vue

Fixes https://discord.com/channels/317348946144002050/619437014001123338/793299179731812383

fix(ui): reflect command responses changes

---

docs/_master/filters/all.md
src/bot/message.ts

feat(message): add $youtube filters

---

src/bot/commons.ts
src/bot/events.ts
src/bot/games/duel.ts
src/bot/helpers/array/sample.ts
src/bot/helpers/array/shuffle.ts
src/bot/main.ts
src/bot/message.ts
src/bot/permissions.ts
src/bot/systems/alias.ts
src/bot/systems/commercial.ts
src/bot/systems/cooldown.ts
src/bot/systems/customcommands.ts
src/bot/systems/keywords.ts
src/bot/systems/moderation.ts
src/bot/systems/points.ts
src/bot/systems/price.ts
src/bot/systems/queue.ts
src/bot/systems/quotes.ts
src/bot/systems/raffles.ts
src/bot/systems/ranks.ts
src/bot/systems/timers.ts
src/bot/systems/userinfo.ts
src/bot/translate.ts

refactor(lodash): replace some functions with native alternatives

---

src/bot/message.ts
test/tests/message/discord#706756329204613160_latest_variable_are_not_correct.js

Fixes https://discord.com/channels/317348946144002050/619437014001123338/795004815696592906

fix(message): get correct bits amount with $latestCheerAmount

---

src/bot/filters/command.ts
src/bot/filters/custom.ts
src/bot/filters/evaluate.ts
src/bot/filters/ifp.ts
src/bot/filters/index.ts
src/bot/filters/info.ts
src/bot/filters/list.ts
src/bot/filters/math.ts
src/bot/filters/online.ts
src/bot/filters/param.ts
src/bot/filters/price.ts
src/bot/filters/qs.ts
src/bot/filters/random.ts
src/bot/filters/stream.ts
src/bot/filters/youtube.ts
src/bot/message.ts

refactor(message): move filters from message.ts

---

src/bot/users.ts

refactor(users): add more debug messages and try/catch/finally

---

src/bot/events.ts
src/bot/microservices/getCustomRewards.ts

fix(getCustomRewards): catch error if user don't have points enabled

---

src/bot/filters/evaluate.ts
src/bot/message.ts

fix(filters): properly parse eval

---

scss/custom.scss
src/bot/panel.ts
src/panel/helpers/isBotStarted.ts
src/panel/index.html
src/panel/index.ts
src/panel/popout.html
src/panel/popout.ts
src/public/index.html
src/public/index.ts

feat(ui): show information when UI loads if bot is still starting

---

src/panel/views/managers/keyword.vue

Fixes https://discord.com/channels/317348946144002050/619437014001123338/798212353517813790

fix(ui): move and delete keyword responses properly

---

src/bot/tmi.ts
src/panel/views/managers/viewers.vue

Fixes https://discord.com/channels/317348946144002050/619437014001123338/797823767001825300

fix(tmi): subgifts should be properly incremented

---

src/bot/helpers/socket.ts
src/bot/users.ts
src/panel/views/managers/viewers.vue

Fixes https://discord.com/channels/317348946144002050/619437014001123338/798325744404398080

feat(ui): add subgift reset

---

src/bot/api.ts

Fixes https://discord.com/channels/317348946144002050/619437014001123338/798746751372623913

fix(api): remove cursor for subscriber check to load full list

---

src/panel/views/settings/components/interface/sortable-list.vue

refactor(ui): move sortable-list to composition api

---

src/bot/integrations/discord.ts
src/panel/views/settings/components/interface/discord-channel.vue

Fixes https://community.sogebot.xyz/t/multiple-discord-channels/237

feat(discord): add multiple channels to listen

---

src/bot/decorators.ts
src/bot/helpers/api/cache.ts
src/bot/helpers/api/isStreamOnline.ts
src/bot/helpers/api/stats.ts
src/bot/helpers/api/streamId.ts
src/bot/helpers/api/streamStatusChangeSince.ts
src/bot/helpers/api/streamType.ts
src/bot/helpers/core/persistent.ts
src/bot/helpers/oauth/channelId.ts

refactor: create helper for creation of persistent variables

---

src/bot/users.ts

If database have duplicate usernames, try to recheck usernames
by userId.
Fixes https://discord.com/channels/317348946144002050/619437014001123338/801201878763175966

fix(users): periodically check for duplicate usernames

---

src/overlay/views/alertsRegistry.vue
src/panel/views/registries/alerts/components/query-filter.vue

FIxes https://discord.com/channels/317348946144002050/317349069024395264/801277941568372746

fix(alerts): cast Prime tier as number to fix filtering

---

src/bot/events.ts
src/panel/views/managers/events.vue

fix(events): fix incorrect condition to run test event

---

src/bot/helpers/commons/announce.ts
src/bot/helpers/customvariables/getURL.ts
src/bot/helpers/customvariables/postURL.ts
src/bot/message.ts
test/tests/customvariable/getURL.js
test/tests/customvariable/postURL.js

fix(customvariables): send correct response on POST change

---

src/bot/integrations/tipeeestream.ts

Fixes https://community.sogebot.xyz/t/tipeeestream-com-error-while-connecting/243

fix(tipeeestream): use legacy socket.io connection

---

src/bot/api.ts

Fixes https://discord.com/channels/317348946144002050/619437014001123338/802382633592946698

fix(api): remove helper variable to count subscribers

---

src/bot/api.ts
src/bot/events.ts
src/bot/helpers/commons/announce.ts
src/bot/oauth.ts
src/bot/pubsub.ts
src/bot/widgets/chat.ts

Fixes https://discord.com/channels/317348946144002050/619437014001123338/801173858223783936

fix(oauth): save botId to helper variable

---

src/bot/users.ts
src/panel/components/statsbar/statsbar.vue
src/panel/helpers/error.ts
src/panel/views/managers/viewers.vue

Fixes https://community.sogebot.xyz/t/option-to-delete-users-in-database/238

feat(ui): add user deletion

---

src/bot/database/entity/alert.ts
src/bot/microservices/getCustomRewards.ts
src/bot/tmi.ts
src/panel/components/rewardDropdown.vue
src/panel/views/registries/alerts/alerts-edit.vue
src/panel/views/registries/alerts/alerts-test.vue
src/panel/views/registries/alerts/components/form-cheers.vue
src/panel/views/registries/alerts/components/form-follow.vue
src/panel/views/registries/alerts/components/form-resubs.vue
src/panel/views/registries/alerts/components/form-reward.vue

Not sending event will cause ignore of event during api chat list call
Fixes https://discord.com/channels/317348946144002050/317349069024395264/803935611487780865

fix(tmi): trigger join event if offline user send message

---

package-lock.json
package.json
src/bot/panel.ts

refactor(ui): add rate limit to express endpoints

---

package-lock.json
package.json
src/bot/panel.ts

refactor(ui): sanitize path access

---

src/bot/currency.ts
src/bot/main.ts
src/bot/systems/userinfo.ts
src/panel/views/registries/randomizer/randomizer-list.vue
tools/backup.js
tools/changelog.js
tools/migration.js

refactor: LGTM fixes

---

src/bot/panel.ts

refactor(panel): fix sanitize and rate-limit

---

src/overlay/views/alertsRegistry.vue

Fixes https://discord.com/channels/317348946144002050/797838809609666590/806924547244032072

fix(alerts): show alert properly if anim durations set to 0

---

tools/migrationCheck.js

refactor: update migrationCheck env

---

src/bot/webhooks.ts

https://lgtm.com/rules/1506011407937/

refactor(webhooks): add escape for hub.challenge

---

locales/en/ui/registry/textoverlay.json
src/bot/database/entity/text.ts
src/bot/database/migration/mysql/12.6.x/1612655255728-removeTextOverlayRefreshRate.ts
src/bot/database/migration/postgres/12.6.x/1612655255728-removeTextOverlayRefreshRate.ts
src/bot/database/migration/sqlite/12.6.x/1612655255728-removeTextOverlayRefreshRate.ts
src/bot/helpers/customvariables/emitter.ts
src/bot/helpers/customvariables/setValueOf.ts
src/bot/registries/text.ts
src/overlay/views/text.vue
src/panel/views/registries/text-overlay/text-overlay-edit.vue
src/panel/views/registries/text-overlay/text-overlay-list.vue

fix(text): remove refresh rate and update overlay on change

---

src/bot/integrations/tipeeestream.ts

Fixes https://discord.com/channels/317348946144002050/619437014001123338/807955149149437952

fix(tipeeestream): full connect after connect_error

---

locales/en/ui/registry/overlays.json
package-lock.json
src/overlay/views/clipscarousel.vue
src/panel/index.ts
src/panel/views/registries/overlays/components/clipscarousel.vue
src/panel/views/registries/overlays/components/obswebsocket.vue
src/panel/views/registries/overlays/overlays.vue

Fixes https://community.sogebot.xyz/t/clipcarousel-no-auto-mute-option/247

feat(overlay): add volume setting for clipscarousel

---

locales/en.json
src/bot/expects.ts
src/bot/systems/moderation.ts
test/tests/message/list.js
test/tests/moderation/caps.js
test/tests/moderation/containsLink.js
test/tests/moderation/emotes.js
test/tests/moderation/longMessage.js
test/tests/moderation/spam.js
test/tests/moderation/symbols.js
test/tests/moderation/whitelist.js

Grants immunity for user for certain period of time
Fixes https://community.sogebot.xyz/t/moderation-immune-system/71

feat(moderation): add !immune command

---

src/bot/helpers/core/persistent.ts
test/tests/helpers/persistent_null.js
test/tests/helpers/persistent_number.js
test/tests/helpers/persistent_object.js
test/tests/helpers/persistent_string.js

+ debug info and basic set of tests

fix(persistent): trigger onChange properly on all changes

---

package-lock.json
src/bot/api.ts
src/bot/helpers/core/persistent.ts
src/bot/integrations/donationalerts.ts
src/bot/integrations/qiwi.ts
src/bot/integrations/streamelements.ts
src/bot/integrations/streamlabs.ts
src/bot/integrations/tipeeestream.ts
src/bot/microservices/updateChannelViewsAndBroadcasterType.ts
src/bot/tmi.ts
src/bot/users.ts
src/bot/webhooks.ts

fix(persistent): consistent behaviour on JSON.stringify

---

Makefile
package-lock.json
package.json
src/bot/api.ts
src/bot/helpers/core/stream.ts
src/bot/main.ts
src/bot/tsconfig.json
src/bot/webhooks.ts
webpack.config.js

fix(stream): trigger stop stream if started quickly after last stream

---

Makefile
d.ts/missingTypes.d.ts
package-lock.json
package.json
patches/hltb-htmlscraper-headers.patch
src/bot/systems/howlongtobeat.ts

fix(hltb): patch howlongtobeat dependency to return correct data

---

src/bot/integrations/discord.ts

fix(discord): show simpler error message if embed doesn't exist

---

src/bot/database/entity/alert.ts
src/bot/database/entity/randomizer.ts
src/bot/database/migration/mysql/12.7.x/1613659461852-globalTTSForAlerts.ts
src/bot/database/migration/postgres/12.7.x/1613659461852-globalTTSForAlerts.ts
src/bot/database/migration/sqlite/12.7.x/1613659461852-globalTTSForAlerts.ts
src/overlay/views/alertsRegistry.vue
src/panel/views/registries/alerts/alerts-edit.vue
src/panel/views/registries/alerts/components/tts-global.vue

feat(alerts): add global tts settings

---

.github/workflows/dockerimage-release.yml
.github/workflows/dockerimage.yml
.github/workflows/pullrequest-artifact.yml
.github/workflows/tests.yml
src/bot/commons.ts
src/bot/helpers/commons/announce.ts
src/bot/helpers/commons/getBot.ts
src/bot/helpers/commons/prepare.ts
src/bot/helpers/commons/round5.ts
src/bot/systems/scrim.ts
test/tests/commons/round5.js
test/tests/scrim/workflow.js
tools/runTests.js

test(scrim): update scrim tests

---

d.ts/index.d.ts
src/bot/_interface.ts
src/bot/decorators.ts
src/bot/parser.ts
src/bot/systems/cooldown.ts
src/bot/systems/points.ts
src/bot/systems/price.ts
test/tests/events/discord#814270704161652766_run_command_should_skip_pricing_and_cooldown.js

Fixes https://discord.com/channels/317348946144002050/619437014001123338/814270704161652766

fix(parser): several parsers should be fully skippable

---

test/tests/tmi/subcommunitygift_after_gifts_should_be_ignored.js

test(tmi): wait a while to have propagated increment

---

d.ts/events.d.ts
src/bot/events.ts

Fixes https://community.sogebot.xyz/t/redeem-a-channel-reward/252

fix(events): userId attribute should be string

---

src/bot/systems/songs.ts

Fixes https://discord.com/channels/317348946144002050/619437014001123338/814784954968965150

fix(songs): do mod check on request user and not sender with !bansong

---

d.ts/index.d.ts
src/bot/database/migration/mysql/12.5.x/1582230220319-TTSMinAmountToShow.ts
src/bot/database/migration/mysql/12.5.x/1584106270435-tipsExchangeRates.ts
src/bot/database/migration/mysql/12.5.x/1592557005214-fontMissingShadow.ts
src/bot/database/migration/mysql/12.5.x/1601124530399-eventListUserId.ts
src/bot/database/migration/mysql/12.5.x/1608158764205-messageAlignmentForAlerts.ts
src/bot/database/migration/mysql/12.5.x/1608945825341-extraLevelsReset.ts
src/bot/database/migration/postgres/12.5.x/1582230220319-TTSMinAmountToShow.ts
src/bot/database/migration/postgres/12.5.x/1584106270435-tipsExchangeRates.ts
src/bot/database/migration/postgres/12.5.x/1592557005214-fontMissingShadow.ts
src/bot/database/migration/postgres/12.5.x/1601124530399-eventListUserId.ts
src/bot/database/migration/postgres/12.5.x/1608158764205-messageAlignmentForAlerts.ts
src/bot/database/migration/postgres/12.5.x/1608945825341-extraLevelsReset.ts
src/bot/database/migration/sqlite/12.5.x/1582230220319-TTSMinAmountToShow.ts
src/bot/database/migration/sqlite/12.5.x/1584106270435-tipsExchangeRates.ts
src/bot/database/migration/sqlite/12.5.x/1592557005214-fontMissingShadow.ts
src/bot/database/migration/sqlite/12.5.x/1601124530399-eventListUserId.ts
src/bot/database/migration/sqlite/12.5.x/1608158764205-messageAlignmentForAlerts.ts
src/bot/database/migration/sqlite/12.5.x/1608945825341-extraLevelsReset.ts
src/bot/database/migration/sqlite/12.7.x/1613738901696-globalFontForAlerts.ts
src/bot/integrations/spotify.ts
src/bot/message.ts
src/bot/pubsub.ts
src/bot/systems/songs.ts

Fixes https://discord.com/channels/317348946144002050/619437014001123338/814778916308779018

fix(songs): ban song correct videoId if parameter missing

---

src/bot/helpers/core/stream.ts

fix(stream): reset chat messages on stream start

---

src/bot/api.ts

refactor(api): remove chatMessage reset from API

---

src/bot/events.ts
src/bot/helpers/checkFilter.ts
src/bot/systems/customcommands.ts
test/tests/events/discord#812872046077411328_run_command_should_be_able_trigger_caster_perm_command.js
test/tests/events/discord#814270704161652766_run_command_should_skip_pricing_and_cooldown.js
test/tests/events/discord#815733350039158795_run_command_should_correctly_check_filters.js

fix(commands): skip permission check if running through event

---

docs/_master/systems/timers.md
locales/en.json
src/bot/database/entity/timer.ts
src/bot/database/migration/mysql/12.9.x/1614604739140-timersTickOffline.ts
src/bot/database/migration/postgres/12.9.x/1614604739140-timersTickOffline.ts
src/bot/database/migration/sqlite/12.9.x/1614510825911-userIdToString.ts
src/bot/database/migration/sqlite/12.9.x/1614604739140-timersTickOffline.ts
src/bot/systems/timers.ts
src/panel/views/managers/timers/timers-edit.vue
src/panel/views/managers/timers/timers-list.vue
test/tests/timers/community#254_timer_tickOffline.js
test/tests/timers/set.js

Fixes https://community.sogebot.xyz/t/timers-offline-mode/254

feat(timers): add toggle for ticking offline

---

tools/migration.js

added documentation notice of database setup to console and logfile

fix(migration): added documentation notice to error message

---

tools/migration.js

adds a check for read write permission to bots root folder

feat(permissions): check for read/write permission

---

src/bot/tmi.ts

fix(tmi): add manual PING/PONG

---

locales/en.json
src/bot/helpers/api/stats.ts
src/bot/stats.ts
src/panel/components/textareaWithTags.vue
src/panel/views/managers/commands.vue
src/panel/views/managers/keyword.vue

fix(ui): remove hosts filter

---

src/panel/views/registries/overlays/overlays.vue

fix(ui): overlay copy link should use current protocol

---

src/panel/views/managers/keyword.vue

fix(ui): use xregexp to validate

---

src/bot/systems/alias.ts
test/tests/events/discord#812872046077411328_run_command_should_be_able_trigger_caster_perm_command.js
test/tests/events/discord#814270704161652766_run_command_should_skip_pricing_and_cooldown.js

fix(alias): event ignore permission alias setting

---

src/bot/integrations/streamelements.ts

Fixes https://discord.com/channels/317348946144002050/619437014001123338/823297936355360769

fix(streamelements): allow tips with non twitch usernames

---

src/bot/overlays/eventlist.ts
test/tests/message/discord#706756329204613160_latest_variable_are_not_correct.js

test: change ids of some users to not interfere with botId

---

package-lock.json
src/bot/database/entity/user.ts
src/bot/database/migration/mysql/12.9.x/1618939162326-removeTipsAndBitsRelation.ts
src/bot/database/migration/postgres/12.9.x/1618939162326-removeTipsAndBitsRelation.ts
src/bot/database/migration/sqlite/12.9.x/1614510825911-userIdToString.ts
src/bot/database/migration/sqlite/12.9.x/1618939162326-removeTipsAndBitsRelation.ts
src/bot/helpers/permissions/filters.ts
src/bot/helpers/socket.ts
src/bot/integrations/donationalerts.ts
src/bot/integrations/qiwi.ts
src/bot/integrations/streamelements.ts
src/bot/integrations/streamlabs.ts
src/bot/integrations/tipeeestream.ts
src/bot/stats/bits.ts
src/bot/stats/tips.ts
src/bot/systems/top.ts
src/bot/systems/userinfo.ts
src/bot/tmi.ts
src/bot/users.ts
src/panel/views/managers/viewers.vue
src/panel/views/stats/bits.vue
src/panel/views/stats/tips.vue
test/tests/permissions/check.js
test/tests/top/bits.js
test/tests/top/tips.js

This is often causing data loss when doing migration. Relations are strong and fast,
but sqlite migration can cause damage to relations. We should use manual joins,
where applicable.
Fixes #4687

refactor(user): remove relation from tips and bits

---

src/bot/integrations/tipeeestream.ts

And force reconnect on socket disconnection
Fixes https://community.sogebot.xyz/t/tipeeestream-parse/265/

fix(integrations): handle anonymous twitch users

---

locales/en.json
src/bot/users.ts
src/panel/views/managers/viewers.vue

Fixes https://community.sogebot.xyz/t/level-in-viewer-overview/267

feat(viewers): add level sort and info into viewers table

---

src/bot/api.ts

fix(api): fix pagination infinite loop on several endpoints

---

docs/_master/install-and-upgrade.md

docs(install): added unofficial installer to docs

---

src/bot/overlays/emotes.ts

fix(emotes): use official API endpoints

---

src/bot/api.ts
src/bot/oauth.ts

fix(api): validate token before any interval api call

---

src/database/migration/mysql/13.0.x/1626398375128-migrateOverlaySettings.ts
src/database/migration/postgres/13.0.x/1626398375128-migrateOverlaySettings.ts
src/database/migration/sqlite/13.0.x/1622378375128-migrateOverlaySettings.ts

fix(migration): add migration of several overlays

---

src/database/entity/dashboard.ts

feat(quickactions): add customvariable support

---

src/api/quickaction.ts
src/database/entity/dashboard.ts

Fixes https://github.com/sogehige/sogeBot/issues/4730

fix(quickactions): add customvariable support

---

src/customvariables.ts

fix(customvariables): trigger variable change on ui change

---

package-lock.json
package.json
src/main.ts
tools/runTests.js

build(tests): skip ui update check when testing

---

d.ts/eventlist.d.ts
locales/en.json
src/overlays/eventlist.ts
src/pubsub.ts
src/widgets/eventlist.ts

Fixes https://community.sogebot.xyz/t/add-reward-redeems-in-eventlist/291

feat(eventlist): add reward redeems support

---

src/systems/userinfo.ts

Fixes https://community.sogebot.xyz/t/me-subscribing-in-months/273

feat(userinfo): add submonths to !me command

---

src/api/registries/overlay.ts
src/database/entity/overlay.ts
src/overlays/eventlist.ts

feat(overlay): add eventlist settings

---

package-lock.json
src/tmi.ts
test/tests/moderation/discord#868236481406324747_manually_included_users_with_link_disabled.js

test: add test to check manually included user

---

test/tests/moderation/discord#868236481406324747_manually_included_users_with_link_disabled.js
tools/runTests.js

test: add db cleanup before rerun

---

src/parser.ts
src/systems/alias.ts
src/systems/customcommands.ts
tsconfig.json

fix(parser): exclude fireAndForget parser from thread

---

src/message.ts
test/tests/message/discord#706756329204613160_latest_variable_are_not_correct.js

test: fix timestamp issue with big number

---

src/api.ts
src/helpers/api/hypeTrain.ts

fix(hypeTrain): fix triggering start/end of hypeTrain

---

package-lock.json
src/integrations/discord.ts

fix(discord): warn and unlink nonexisting member

---

.ncurc.json
src/integrations/streamelements.ts

fix(streamelements): use API polling and remove legacy socket.io

---

d.ts/missingTypes.d.ts
locales/en/ui/integrations/tipeeestream.json
package-lock.json
package.json
src/integrations/streamelements.ts
src/integrations/tipeeestream.ts

Tipeee stream fix

---

locales/en/ui.menu.json
package-lock.json
package.json
src/api.ts
src/eventsub.ts
src/helpers/api/hypeTrain.ts
src/helpers/events/emitter.ts
src/main.ts
src/panel.ts

feat(eventsub): add hypetrain support

---

src/systems/polls.ts
test/tests/polls/bits.js
test/tests/polls/normal.js
test/tests/polls/numbers.js
test/tests/polls/tips.js

Fixes https://discord.com/channels/317348946144002050/619437014001123338/879842583566778378

fix(polls): show correct message when numbers are used

---

src/database/entity/alert.ts

fix(entity): move tts outside of common attributes

---

locales/en/ui.menu.json
src/systems/cooldown.ts
test/tests/cooldowns/set.js
test/tests/cooldowns/toggleEnabled.js
test/tests/cooldowns/toggleFollowers.js
test/tests/cooldowns/toggleModerators.js
test/tests/cooldowns/toggleOwners.js
test/tests/cooldowns/toggleSubscribers.js

fix(cooldown): fix typo in help response

---

locales/en/ui/registry/alerts.json
src/database/entity/alert.ts
src/database/migration/mysql/12.0.x/1613738901696-globalFontForAlerts.ts
src/database/migration/mysql/13.0.x/1630924716945-addAlertParries.ts
src/database/migration/postgres/12.0.x/1613738901696-globalFontForAlerts.ts
src/database/migration/postgres/13.0.x/1630924716945-addAlertParries.ts
src/database/migration/sqlite/12.0.x/1613738901696-globalFontForAlerts.ts
src/database/migration/sqlite/13.0.x/1630924716945-addAlertParries.ts

Fixes https://community.sogebot.xyz/t/alert-parries/270

feat(alerts): add alert parries

---

d.ts/index.d.ts
src/api/quickaction.ts
src/commons.ts
src/decorators.ts
src/filters/command.ts
src/helpers/checkFilter.ts
src/helpers/commands/count.ts
src/helpers/commons/sendMessage.ts
src/helpers/log.ts
src/helpers/parser/emitter.ts
src/helpers/tmi/ignoreList.ts
src/helpers/user/isIgnored.ts
src/parser.ts
src/systems/alias.ts
src/systems/bets.ts
src/systems/cooldown.ts
src/systems/customcommands.ts
src/systems/keywords.ts
src/systems/polls.ts
src/systems/price.ts
src/tmi.ts
test/tests/events/discord#814270704161652766_run_command_should_skip_pricing_and_cooldown.js

fix(performance): add various fixes to speed up parsing

---

src/users.ts

Fixes https://discord.com/channels/317348946144002050/619437014001123338/887929717863358506

fix(users): remove incorrect join

---

locales/en.json
locales/en/ui.systems.songs.json
package-lock.json
src/systems/songs.ts
test/tests/songs/addSongToQueue.js

Fixes https://community.sogebot.xyz/t/whitelist-for-songrequest/307

feat(songs): allow song request only from actual playlist

---

src/api/registries/overlay.ts
src/database/entity/dashboard.ts
src/database/entity/overlay.ts
src/helpers/socket.ts
src/overlays/marathon.ts

feat(marathon): add marathon support

---

locales/en/ui/registry/randomizer.json
src/database/entity/randomizer.ts

Fixes https://community.sogebot.xyz/t/tape-type-for-random-registry/129

feat(randomizer): add tape type

---

package-lock.json
package.json
src/database/entity/checklist.ts
src/database/migration/mysql/14.0.x/1635599216109-changeChecklistId.ts
src/database/migration/postgres/14.0.x/1635599216109-changeChecklistId.ts
src/database/migration/sqlite/14.0.x/1635599216109-changeChecklistId.ts

fix(checklist): save correct values for checklist

---

package-lock.json
package.json
src/database/entity/goal.ts
src/database/migration/mysql/14.0.x/1635631125261-setIntervalAsString.ts
src/database/migration/postgres/14.0.x/1635631125261-setIntervalAsString.ts
src/database/migration/sqlite/14.0.x/1635631125261-setIntervalAsString.ts
src/graphql/schema/goals/goal.ts
src/helpers/goals/recountIntervals.ts

fix(goals): use interval as string

---

package-lock.json
package.json
src/dashboard.ts
src/main.ts
src/panel.ts
src/ui.ts

feat(dashboard): add editable µWidgets

---

src/helpers/tmi/message.ts

fix(twitch): send message to correct channel with /me mode

---

src/services/twitch/chat.ts

fix(twitch): remove redutant self check on whispers

---

src/graphql/resolvers/quickActionsResolver.ts

fix(quickAction): run alias and custom commands on command trigger

---

assets/custom-variables-code.txt
src/filters/evaluate.ts
src/helpers/customvariables/runScript.ts
src/helpers/user/random.ts
test/tests/customvariable/return_random_user.js

- Added new functions which will return only one user in db
- Merge evaluate with runScript to share same code
Fixes #4910

fix(runScript): remove loading full user set on script run

---

locales/en.json
package-lock.json
package.json
src/database/migration/mysql/14.0.x/1641559036883-mergeClipEvents.ts
src/database/migration/postgres/14.0.x/1641559036883-mergeClipEvents.ts
src/database/migration/sqlite/14.0.x/1641559036883-mergeClipEvents.ts
src/events.ts

feat(events): merge clips creation events to single event

---

.github/workflows/crowdin.yml
crowdin.yml

chore(crowdin): add crowdin action

---

docs/_master/systems/queue.md
package-lock.json
package.json
src/database/entity/queue.ts
src/database/migration/mysql/14.0.x/1642423183106-addOptionalQueueMessage.ts
src/database/migration/postgres/14.0.x/1642423183106-addOptionalQueueMessage.ts
src/database/migration/sqlite/14.0.x/1642423183106-addOptionalQueueMessage.ts
src/systems/queue.ts

Fixes https://community.sogebot.xyz/t/queue-modules-msg-for-command-join/330

feat(queue): add optional join message

---

src/filters/evaluate.ts
src/services/twitch/calls/getGameIdFromName.ts
src/services/twitch/calls/getGameNameFromId.ts
test/helpers/messages.js

chore: deepscan fixes

---

src/database/entity/gallery.ts
src/database/migration/mysql/14.0.x/1645091113387-allowShortId.ts
src/database/migration/postgres/14.0.x/1645091113387-allowShortId.ts
test/tests/gallery/#4969_id_can_be_shortid.js

fix(gallery): allow shortIds for primary column

---

Dockerfile
package-lock.json
package.json
src/integrations/protondb.ts

fix(protondb): remove puppeteer and chromium dependency

---

.husky/commit-msg
.husky/pre-commit
test/tests/alias/#3680_alias_should_override_command_permission.js
tools/pre-commit-message.js
tools/pre-commit-tests.sh

chore: add describe.only pre-commit check

---

bin/install.sh
bin/startup.sh

Added a bit of bash scripting best practices. Mostly recommended by shellcheck and the weird new line. 
https://github.com/koalaman/shellcheck/wiki/SC1017).

Fix: Added a bit of bash scripting best practices

---

src/services/twitch/token/refresh.ts
src/services/twitch/token/validate.ts

refactor(services): remove duplication of code

---

assets/presets/textOverlay/pause1/css.txt

fix(overlay): add better style for smaller resolutions

---

locales/en.json
src/database/migration/mysql/14.0.x/1645019207861-addMissingAttributesToCommandOperations.ts
src/database/migration/postgres/14.0.x/1645019207861-addMissingAttributesToCommandOperations.ts
src/database/migration/sqlite/14.0.x/1645019207861-addMissingAttributesToCommandOperations.ts
src/events.ts
src/helpers/events/run-command.ts

feat(events): add timeout to run command operation

---

locales/en.json
src/events.ts
src/helpers/events/command-redeem.ts
src/registries/alerts.ts

feat(events): add command redeem operation

---

src/message.ts

fix(message): change regexp to parse as \w

---

src/filters/stream.ts
src/helpers/checkFilter.ts
src/message.ts
test/tests/helpers/discord#963386192089460767.js

Fixes https://discord.com/channels/317348946144002050/317349069024395264/963386192089460767

fix(checkFilter): handle $param and $touser edge-case in filters

---

.github/workflows/crowdin.yml
.gitignore

try to remove gitignore

---

d.ts/src/helpers/socket.d.ts
locales/en/ui/registry/alerts.json
src/database/entity/alert.ts
src/database/entity/goal.ts
src/database/migration/mysql/14.0.x/1650542961119-tiltifyCampaign.ts
src/database/migration/postgres/14.0.x/1650542961119-tiltifyCampaign.ts
src/database/migration/sqlite/14.0.x/1650542961119-tiltifyCampaign.ts
src/graphql/schema/goals/goal.ts
src/integrations/donationalerts.ts
src/integrations/kofi.ts
src/integrations/qiwi.ts
src/integrations/streamelements.ts
src/integrations/streamlabs.ts
src/integrations/tiltify.ts
src/integrations/tipeeestream.ts

feat(goals): add tiltify goal

---

src/filters/stream.ts
src/message.ts
test/tests/message/discord#968557749908701245_stream_username_with_at_not_parsed.js

Fixes https://discord.com/channels/317348946144002050/317349069024395264/968557749908701245

fix(message): add at to be parsed correctly with username

---

src/database/entity/howLongToBeatGame.ts
src/database/insertItemIntoTable.ts
src/database/migration/mysql/14.0.x/1651843397006-changeHLTBTimestamps.ts
src/database/migration/postgres/14.0.x/1651843397006-changeHLTBTimestamps.ts
src/database/migration/sqlite/14.0.x/1651843397006-changeHLTBTimestamps.ts
src/systems/howlongtobeat.ts
tools/migrationCheck.js

fix(hltb): update game times once in a while

---

locales/en/ui/registry/plugins.json
src/plugins.ts
src/plugins/nodes/twitchSendMessage.ts

feat(plugins): add botStarted listener

---

.github/workflows/dockerimage-release.yml
.github/workflows/dockerimage.yml
.github/workflows/pullrequest-artifact.yml
.github/workflows/tests-generic.yml
.github/workflows/tests-mysql.yml
.github/workflows/tests-postgres.yml
.github/workflows/tests-sqlite.yml
Dockerfile
Makefile

chore: artifact build

---

package-lock.json
src/database/entity/user.ts
src/database/migration/mysql/15.0.x/1651843397008-retypeUserDates.ts
src/database/migration/postgres/15.0.x/1651843397008-retypeUserDates.ts
src/database/migration/sqlite/15.0.x/1651843397008-retypeUserDates.ts

fix(entity): expand varchar to 30 chars to handle more precise dates

---

Makefile
d.ts/src/helpers/socket.d.ts
package-lock.json
src/database/entity/cooldown.ts
src/database/migration/mysql/15.0.x/1659639416172-retypeTimestampAttribute.ts
src/database/migration/postgres/15.0.x/1659639416172-retypeTimestampAttribute.ts
src/database/migration/sqlite/15.0.x/1659639416172-retypeTimestampAttribute.ts
src/systems/cooldown.ts
test/helpers/db.js
test/tests/cooldowns/#3720_cooldown_should_be_properly_reverted.js
test/tests/cooldowns/check.js
tools/migrationCheck.js

chore: update cooldown to api

---

d.ts/src/helpers/socket.d.ts
src/database/entity/keyword.ts
src/systems/keywords.ts
test/tests/keywords/#4860_group_filter_and_permissions.js
test/tests/keywords/basic_workflow.js

chore: keywords rest api

---

d.ts/src/helpers/socket.d.ts
package.json
src/database/entity/commands.ts
src/database/migration/mysql/16.0.x/1659639416174-updateCommands.ts
src/database/migration/postgres/16.0.x/1659639416174-updateCommands.ts
src/database/migration/sqlite/16.0.x/1659639416174-updateCommands.ts
src/helpers/commands/count.ts
src/systems/customcommands.ts
test/tests/commands/#4860_group_filter_and_permissions.js
test/tests/commands/discord#794732878595752016_param_should_be_properly_filtered.js.js
test/tests/commands/run.js
test/tests/events/discord#815733350039158795_run_command_should_correctly_check_filters.js

chore: commands to rest api

---

d.ts/src/helpers/socket.d.ts
package.json
src/database/entity/timer.ts
src/database/migration/mysql/16.0.x/1661765436386-timerAttrChange.ts
src/database/migration/postgres/16.0.x/1661765436386-timerAttrChange.ts
src/database/migration/sqlite/16.0.x/1661765436386-timerAttrChange.ts
src/stats.ts
src/systems/timers.ts
test/tests/timers/add.js
test/tests/timers/bug#4209_custom_command_filter_is_not_triggered.js
test/tests/timers/community#254_timer_tickOffline.js
test/tests/timers/discord#794910249910796288_disabled_response_should_not_be_sent_to_chat.js
test/tests/timers/list.js
test/tests/timers/set.js
test/tests/timers/toggle.js
test/tests/timers/unset.js

chore: timers entity

---

d.ts/src/helpers/socket.d.ts
src/database/entity/cacheGames.ts
src/database/migration/mysql/16.0.x/1661348421631-cacheTitleChangeToIdAddThumbnail.ts
src/database/migration/postgres/16.0.x/1661348421631-cacheTitleChangeToIdAddThumbnail.ts
src/database/migration/sqlite/16.0.x/1661348421631-cacheTitleChangeToIdAddThumbnail.ts
src/panel.ts
src/services/twitch/calls/getGameNameFromId.ts
src/services/twitch/calls/getGameThumbnailFromName.ts
src/services/twitch/calls/searchCategoriesPaginated.ts

feat(cache): cache game thumbnails

---

.eslintrc.json
d.ts/src/helpers/socket.d.ts
package.json
src/database/entity/quotes.ts
src/database/entity/timer.ts
src/database/migration/mysql/16.0.x/1662119547477-quoteCreatedAtChange.ts
src/database/migration/postgres/16.0.x/1662119547477-quoteCreatedAtChange.ts
src/database/migration/sqlite/16.0.x/1662119547477-quoteCreatedAtChange.ts
src/systems/quotes.ts

chore: change quotes to entity

---

package.json
src/database/entity/plugins.ts
src/database/migration/mysql/16.0.x/1663675337188-addPluginsSettings.ts
src/database/migration/postgres/16.0.x/1663675337188-addPluginsSettings.ts
src/database/migration/sqlite/16.0.x/1663675337188-addPluginsSettings.ts
src/plugins.ts

feat(plugins): add plugin settings

---

d.ts/src/helpers/socket.d.ts
src/database/entity/_botEntity.ts
src/database/entity/rank.ts
src/systems/ranks.ts

chore: change rank to entity

---

src/database/entity/song.ts
src/database/migration/mysql/16.0.x/1666167883933-updateSongs.ts
src/database/migration/postgres/16.0.x/1666167883933-updateSongs.ts
src/database/migration/sqlite/16.0.x/1666167883933-updateSongs.ts
src/systems/songs.ts

chore: change songs to entity

---

src/_interface.ts
src/database/entity/permissions.ts
src/database/migration/mysql/16.0.x/1666167883934-updatePermissions.ts
src/database/migration/postgres/16.0.x/1666167883934-updatePermissions.ts
src/database/migration/sqlite/16.0.x/1666167883934-updatePermissions.ts
src/general.ts
src/helpers/cache.ts
src/helpers/permissions/check.ts
src/helpers/permissions/filters.ts
src/helpers/permissions/get.ts
src/helpers/permissions/getCommandPermission.ts
src/helpers/permissions/getUserHighestPermission.ts
src/integrations/discord.ts
src/parser.ts
src/permissions.ts
src/users.ts

chore: permissions entity

---

src/services/google.ts

Youtube api

---

locales/en/ui.registry.customvariables.json
src/database/entity/variable.ts
src/database/migration/mysql/16.0.x/1666167883936-updateCustomVariables.ts
src/database/migration/postgres/16.0.x/1666167883936-updateCustomVariables.ts
src/database/migration/sqlite/16.0.x/1666167883936-updateCustomVariables.ts
src/helpers/customvariables/getValueOf.ts
test/tests/customvariable/#3879_eval_should_trigger_with_param.js

chore: remove custom variable unused variables

---

d.ts/src/helpers/socket.d.ts
package.json
src/database/entity/overlay.ts
src/database/migration/mysql/13.0.x/1626398375128-migrateOverlaySettings.ts
src/database/migration/mysql/13.0.x/1626478375129-attachCanvasToGroupOverlay.ts
src/database/migration/mysql/13.0.x/1634053219263-stringifyOverlayGroup.ts
src/database/migration/mysql/16.0.x/1675089806897-updateOverlayToGroup.ts
src/database/migration/postgres/13.0.x/1626398375128-migrateOverlaySettings.ts
src/database/migration/postgres/13.0.x/1626478375129-attachCanvasToGroupOverlay.ts
src/database/migration/postgres/13.0.x/1634053219263-stringifyOverlayGroup.ts
src/database/migration/postgres/16.0.x/1675089806897-updateOverlayToGroup.ts
src/database/migration/sqlite/13.0.x/1622378375128-migrateOverlaySettings.ts
src/database/migration/sqlite/13.0.x/1626478375129-attachCanvasToGroupOverlay.ts
src/database/migration/sqlite/13.0.x/1634053219263-stringifyOverlayGroup.ts
src/database/migration/sqlite/16.0.x/1675089806897-updateOverlayToGroup.ts
src/helpers/overlaysDefaultValues.ts
src/overlays/clipscarousel.ts
src/overlays/countdown.ts
src/overlays/marathon.ts
src/overlays/stopwatch.ts
src/registries/overlays.ts
src/services/twitch.ts

refactor: overlays to groups only

---

src/database/entity/commands.ts
src/database/migration/mysql/16.0.x/1678892044029-addRandomResponsesToggle.ts
src/database/migration/postgres/16.0.x/1678892044029-addRandomResponsesToggle.ts
src/database/migration/sqlite/16.0.x/1678892044029-addRandomResponsesToggle.ts
src/systems/customcommands.ts

feat(customcommands): add randomizing of responses

---

src/database/entity/alert.ts
src/filters/operation.ts
src/message.ts

feat: support $triggerAlert with options

---

src/services/twitch.ts
src/services/twitch/eventsub.ts

chore: revert disconnect

---

src/helpers/events/emitter.ts
src/helpers/events/subscription.ts
src/plugins.ts
src/plugins/ListenTo.ts
src/registries/alerts.ts
src/services/twitch/chat.ts
src/services/twitch/eventSubLongPolling.ts
src/services/twitch/eventSubWebsocket.ts

feat(events): add all usable EventSub events

---

.github/workflows/dockerimage-pr.yml
d.ts/src/helpers/socket.d.ts
package.json
src/customvariables.ts
src/database/BotEntity.ts
src/database/entity/event.ts
src/database/entity/howLongToBeatGame.ts
src/database/entity/variable.ts
src/database/migration/mysql/21.x/1678892044036-eventsUpdate.ts
src/database/migration/postgres/21.x/1678892044036-eventsUpdate.ts
src/database/migration/sqlite/21.x/1678892044036-eventsUpdate.ts
src/database/validators/IsCommand.ts
src/database/validators/isCustomVariable.ts
src/events.ts
src/helpers/attributesReplace.ts
src/helpers/events/run-command.ts
src/integrations/discord.ts
src/integrations/obswebsocket.ts
src/systems/howlongtobeat.ts

Events to entity and validation

---

package.json
src/database/entity/overlay.ts
src/helpers/overlaysDefaultValues.ts
src/helpers/parseTextWithEmotes.ts
src/overlays/chat.ts
src/services/google.ts

feat(google): add initial youtube chat integration

---

src/database/entity/keyword.ts
src/database/migration/mysql/22.x/1678892044040-changeKeywordsResponses.ts
src/database/migration/postgres/22.x/1678892044040-changeKeywordsResponses.ts
src/database/migration/sqlite/22.x/1678892044040-changeKeywordsResponses.ts
src/systems/keywords.ts
test/tests/cooldowns/check.js
test/tests/cooldowns/check_default_values.js
test/tests/cooldowns/default_cooldown_can_be_overrided.js
test/tests/keywords/#4860_group_filter_and_permissions.js

chore(keywords): update entity response

---

locales/en/games.heist.json

fix: update locales
