sogebot/sogeBot

config.ini, libs/systems/points.js, libs/twitch.js, main.js, package.json
There's no need to specify a cluster, join/part events have a simplification for detecting itself, API requests are automatically set for JSON, and tmi.js already sends the capability requests to Twitch [here](https://github.com/tmijs/tmi.js/blob/3ab4ab20db32299ccfd4e98b957077df90f5a671/lib/client.js#L900).
[Documentation for tmi.js v1.1.1 can be found here.](https://docs.tmijs.org/v1.1.1/)
=> Update to tmi.js v1.1.1

libs/users.js, locales/cs.json, locales/en.json
`!merge` is updated with new syntax and is simpler. It will not basically merge all data, just 'rename' user to a new one
New syntax to use `!merge`:
`!merge -from user1 -to user2`
_ref: #496, #418
=> users: re-add !merge

libs/twitch.js, libs/users.js, libs/webhooks.js, locales/cs.json, locales/en.json, main.js
Removed API sub length check, as `created_at` was not correct (always less than month because it got reset on resub), so we will need to get data from sub/resub events
Also added `!followers`, `!subs` commands #334
=> twitch, users: sub length fixes, !subs and !followers

libs/message.js
- Force return empty qs if param is null
=> lib/message: Force return empty qs if param is null

libs/api.js
Fix sending error message on 400 error when channel desn't have affiliate or partner
#1070
=> lib/api: Send correct cli error if channel is not affiliate/partner

src/bot/oauth.js
Prevents connection to undefined channelId, which may cause some
future issues with connections (would not reconnect if channelId
is changed)
=> oauth: disable reconnect on undefined channelid

src/bot/commons.js, test/helpers/db.js, test/tests/commons/compactDb.js
This was causing users with too much points where decrements were
ignored
=> commons: fix compactDb() compacting only >0 values

src/bot/commons.js
=> commons: fix timeouting when broadcaster oauth is not set

src/bot/api.js, src/bot/oauth.js
Fixes #1823
This will update subscriber endpoint from kraken to new helix. Broadcasters account oauth **needs** to be updated to be able to use new endpoint.
**New broadcaster scopes:** 
- chat:read
- chat:edit
- channel:moderate
- channel:read:subscriptions
=>  api: update subscribers endpoint to helix

src/bot/systems/polls.ts
Extend timeout for sending several messages should help tests to
have correct order of messages. If we still have some issues with this,
we shuld consider to add proper message queue
=> fix(polls): extend timeout for sending several messages

docs/_master/howto/write-own-system.md, src/bot/_interface.js
=> fix: throw warning message if non retroactive object is used

docs/_master/integrations/spotify.md, src/bot/integrations/spotify.js, src/panel/widgets/components/spotify.vue
Added into widget and as command
Unfortunately this seems to be bugged with https://github.com/spotify/web-api/issues/ 1040
I'll keep a code and feature but some users may experience 500 errors and not working functionality, skipping through desktop, mobile is **recommended**
=> feat(spotify): add skip for spotify

src/bot/systems/points.js
=> fix(points): use expects for get()

src/panel/widgets/components/ytplayer.vue
Fixes issue where ytplayer is muted when start time is custom
=> fix(ui): YT player should not be muted on some occasions

locales/cs/ui/core/twitch.json, locales/en/ui/core/twitch.json, src/bot/api.js, src/bot/twitch.js
This toggle will ensure that bot will try to keep set games/title
forced (rewriting changes from other bots, dashboard)
Fixes #1714
=> feat(twitch): add force game/title toggle

src/bot/api.js, src/bot/tmi.js
Replace owner check with broadcaster check as owners
could be nonbroadcaster users, but still subscribers
Fixes #2416
=> fix(api): exclude broadcaster from subscribers

src/bot/api.js
=> fix(api): set correct subscriber data on getChannelSubscribers

public/index.html
Chrome is causing bug, where
invisible (display or visibility) YT player
does not trigger play. Workaround
is to move whole dashboard out of visible
frame
Fixes #2410
=> fix(ui): move dashboard out of frame

src/bot/api.js
Fixes #2482
This should help to prevent reset of title when title is not succesfully
changed. Title is not overridden by title without variable
=> fix(api): skip change on raw status on update fail

src/panel/views/settings/interface.vue
_permissions can be null as it means disabled
Fixes #2547
=> fix(ui): skip null filter on _permissions

src/panel/views/settings/interface.vue
=> fix(ui): keep ordered settings without lose of initial data

src/bot/systems/customCommands.ts, test/tests/commands/run.js
Update behavior to run all custom commands which have similar names
e.g.
!test qwerty
---
!test with $param - OK
!test - NG
!test qwerty - OK
Fixes #2566
=> fix(commands): run similar commands only if expecting $param

src/bot/tmi.js
Removing handling of RITUAL doesn't make new chatter less useful,
we have backup code for new_chatter and determiting of new chatters.
This will need to be adressed when changed back to tmi.js
Closes #2581
=> fix(tmi): remove RITUAL handling

d.ts/registry.d.ts, src/bot/registries/alerts.ts, src/overlay/views/alertsRegistry.vue, src/panel/views/registries/alerts/alerts-edit.vue
Added updatedAt to alerts to determinate, if alert was changed
and should be loaded again.
=> fix(alerts): remove 1s polling of alerts causing high heap allocation

src/panel/helpers/isUserLoggedIn.ts
=> fix(auth): catch error on invalid auth code

public/oauth.html, src/login/views/login.vue
=> fix(oauth): redirect back to popout url if needed

src/bot/commons.ts, src/bot/systems/scrim.ts, test/helpers/db.js, test/helpers/messages.js, test/tests/scrim/workflow.js
This should help with robustness of scrim system
where we don't fetch sender data unnecessarily
Fixes #2669
=> fix(scrim): send cooldown messages as bot

src/bot/oauth.ts
Right now error is very long.
I reworked it to:
If it was twitch exception, it will show data object, what is: `data: { status: 401, message: 'invalid access token' }`, for example. If it's http server error it will show status and statusText
=> refactor(oauth): simplify error on token validate

src/bot/api.ts, src/bot/webhooks.ts
If twitch lost connection to bot, bot may reset stats too soon
before stream is really offline.
FIxes #2819
=> fix(api): reset stats on stream start

src/bot/tmi.ts
Self hosting should not be alerted
=> fix(tmi): don't trigger alert on hosting event

src/bot/_interface.ts, src/bot/socket.ts
=> refactor(socket): send admin/viewer errors if not access by default

src/panel/index.ts
This was causing page bumping, also added
dropdownVue.show() to reinstate correct dropdown state
Fixes #2940
=> fix(ui): use setTimeout to wait more than nextTick

docs/_master/howto/connection-to-socket.md, src/bot/socket.ts, src/panel/components/navbar/user.vue, src/panel/helpers/isUserLoggedIn.ts, src/panel/helpers/socket.ts
1. accessToken is sent to bot, if everything is OK, we have access
2. refreshToken with userId is sent after accessToken failed
3. user is unauthorized if steps above failed -> forced to login
=> fix(sockets): split access/refresh token authorization

docs/_master/commands/points.md, locales/cs.json, locales/en.json, src/bot/expects.js, src/bot/systems/points.ts, test/tests/points/all.js, test/tests/points/give.js, test/tests/points/online.js
Also added possibility to use negative points for all and online
Fixes https://community.sogebot.xyz/t/remove-n-points-from-all-users/34
=> feat(points): add online subcommand

.github/workflows/tests.yml, npm-shrinkwrap.json, package.json, src/panel/views/registries/alerts/components/form-cheers.vue, src/panel/views/registries/alerts/components/form-follow.vue, src/panel/views/registries/alerts/components/form-hosts.vue, src/panel/views/registries/alerts/components/form-resubs.vue, webpack.config.js
This should fix webpack alias issue.
Updated to TypeScript 3.8
=> build: import only types

d.ts/index.d.ts, locales/cs.json, locales/en.json, src/bot/parser.ts, src/bot/systems/customcommands.ts, src/panel/views/managers/commands/commands-edit.vue, test/tests/commands/run.js
This commit changes current behavior, where responses without $param are
ignored if command is sent with param.
Now user need to add filter if he want to block responses without param
=> feat(customcommands): add $haveParam filter

docs/_master/commands/miscellaneous.md, src/bot/systems/userinfo.ts
This command behavior is same as !me except it can have param to check
other users as well by theirs username
By default it is disabled
Fixes https://ideas.sogebot.xyz/posts/120/similar-command-as-me-for-check-other-user
=> feat(userinfo): add !stats command

src/bot/commons.ts, test/tests/commons/sendMessage.js
Fixes https://community.sogebot.xyz/t/replace-me-when-bot-already-in-color-mode/54/7
=> fix(commons): replace /me if bot is in color-mode

src/bot/database/migration/mysql/1582546819777-RanksTypes.ts, src/bot/database/migration/postgres/1582546688571-RanksTypes.ts
=> refactor(migration): update ranks migration to include viewer default

src/bot/parser.ts, src/bot/systems/customcommands.ts
Fixes https://community.sogebot.xyz/t/warning-on-disabled-command-usage/45
=> feat(parser): warn on disabled command use

src/bot/message.js, test/tests/customvariable/customvariable_command_reply#3379.js
=> fix(message): return correct cvar value on command reply

src/bot/integrations/spotify.ts
Fixes https://community.sogebot.xyz/t/integrations-spotify-authorization-reseting-after-while/27
=> fix(spotify): remove unnecessary scopes info

package.json
We will have proper logs in logs/migration.log
and bot will start when migration is done
=> chore: run migration before bot start

locales/cs.json, locales/en.json, src/panel/widgets/components/raffles.vue, test/tests/raffles/pick.js
=> fix(raffles): show correct winner in widget after reroll

src/bot/api.ts
If API call is taking more than 10minutes, something has probably happen.
Unblocking and adding warning message to be able to track what may cause
freeze.
Fixes #3568
=> fix(api): forcefully free api call if taking long time

src/bot/api.ts
=> fix(api): update logic of unlock api

src/bot/message.ts, test/tests/commons/#3620_announce_is_not_parsing_filters.js, test/tests/message/discord#706782624416399422_sender_object_should_be_ignored.js
Fixes https://discordapp.com/channels/317348946144002050/619437014001123338/706782624416399422
=> fix(message): remove $sender replace in (!#) and (!!#)

src/bot/api.ts, src/bot/message.ts, src/bot/microservices/getUserFromTwitch.ts, src/bot/oauth.ts, src/bot/systems/highlights.ts, src/bot/users.ts, src/bot/webhooks.ts, src/panel/helpers/isUserLoggedIn.ts
per https://discuss.dev.twitch.tv/t/requiring-oauth-for-helix-twitch-api-endpoints/23916
we need to append clientId just because.
=> fix(api): add clientId to all Bearer requests

src/bot/message.ts
=> fix(message): (!#) and (!!#) filters should be properly parsed

Makefile, d.ts/index.d.ts, locales/en/ui/overlays/texttospeech.json, package-lock.json, patches/twitch-js-add-highlight-msgId.patch, src/bot/overlays/textToSpeech.ts, src/panel/views/managers/commands/commands-list.vue, src/panel/views/registries/text-overlay/text-overlay-list.vue, src/panel/views/settings/components/interface/toggle-enable.vue, src/panel/views/settings/interface.vue
=> feat(tts): trigger TTS on higlighted message

Dockerfile
We are changing to stretch-slim as alpine may have some issues
with dns resolving
[skip-tests]
=> chore(docker): use stretch-slim instead of alpine

package.json
This should enable us to use it as NODE_OPTIONS env variable
if needed to be manually tweaked
=> refactor(package): remove --max_old_space_size

docs/_master/filters/all.md, docs/_master/systems/alias.md, locales/en.json, src/bot/database/entity/alias.ts, src/bot/database/migration/mysql/1589290695701-aliasGroup.ts, src/bot/database/migration/postgres/1589290567071-aliasGroup.ts, src/bot/database/migration/sqlite/1589283262462-aliasGroup.ts, src/bot/message.ts, src/bot/systems/alias.ts, src/bot/systems/keywords.ts, src/bot/systems/ranks.ts, src/bot/systems/timers.ts, src/panel/views/managers/alias/alias-edit.vue, src/panel/views/managers/alias/alias-list.vue
Alias grouping is done through `!alias group` command
e.g.
!alias group -set group -a !test
!alias group -unset !test
!alias group -list
!alias group -list group
also added message filter to filter aliases with groups
(list.alias|group)
(list.!alias|group)
Fixes #3721
=> feat(alias): add alias grouping

.github/workflows/tests.yml, docs/_master/configuration/database.md, docs/configuration/database.md, src/bot/main.ts
Fixes https://community.sogebot.xyz/t/mysql-custom-alerts-not-saving/110
=> docs: update preferred charset for mysql

package-lock.json, src/bot/_interface.ts, src/bot/helpers/commands/pCache.ts, src/bot/parser.ts, src/bot/twitch.ts
getCommandsList should not query for each command permission. This
can lead to some performance issues during loop on end of stream.
I also added error stack to find what might be calling getCommandsList so much after stream ended and there is no traffic.
=> perf(parser): getCommandsList use cached permission

src/bot/helpers/panel.ts, src/bot/socket.ts, src/oauth/index.html, src/panel/helpers/isUserLoggedIn.ts, src/panel/helpers/socket.ts
Seems like manager was not good at keeping several sockets running in
background. I moved back to mapping sockets and forcing new connections
to each socket. This should remove issues with infinite loading of several pages
Fixes #3763
=> fix(ui): use sockets directly and remove manager

src/bot/integrations/discord.ts
I do not think viewers on first alert will be useful.
However, viewers in edited embed is very useful, but we need change interval from 10 minutes to 1.
=> feat(discord): add viewers in edited discord embed

src/bot/commons.ts, src/bot/customvariables.ts, src/bot/message.ts, src/bot/registries/text.ts, src/bot/systems/alias.ts, src/panel/views/registries/custom-variables/custom-variables-code.txt
Source attribute can contain twitch or discord value dependant on
source of user command
Fixes https://community.sogebot.xyz/t/get-custom-variable-script-trigger-source/128
=> feat(customvariables): add source attribute to sender

package-lock.json, src/bot/integrations/spotify.ts
New endpoint was introduced on spotify web api and we can
now directly request songs into queue. Removed playlist swapping
which was used to mitigate queue behavior.
Fixes #3964
=> feat(spotify): use queue endpoint for song request

src/overlay/views/alertsRegistry.vue, src/panel/components/media.vue, src/panel/views/registries/alerts/components/form-cheers.vue, src/panel/views/registries/alerts/components/form-follow.vue, src/panel/views/registries/alerts/components/form-hosts.vue, src/panel/views/registries/alerts/components/form-resubs.vue
Fixes https://community.sogebot.xyz/t/let-alerts-upload-webm-file-type/145
=> feat(alerts): add support for webm

.github/workflows/tests.yml, Makefile, package-lock.json, package.json, src/bot/integrations/spotify.ts, src/oauth/spotify.ts, src/oauth/spotify.vue, webpack.config.js
Somehow webpack is tree shaking getSocket from spotify entry. We are using
io socket directly as we don't actually need getSocket capabilities
=> fix(spotify): use socket.io directly

src/bot/api.ts, src/bot/oauth.ts
Due to bug on Twitch side, modify of channel informations are not
propagated correctly through Twitch. We need to use currently old API
as well to be sure that game is changed across Twitch
=> fix(api): use old API as well to change game

src/bot/message.ts
We need to remove entities decode (don't remember why we need it) as it
strips out e.g. api calls like &lang=de
=> fix(message): remove entities decode

locales/en.json, src/bot/api.ts, src/bot/events.ts, src/bot/helpers/socket.ts, src/bot/oauth.ts, src/bot/pubsub.ts, src/panel/components/rewardDropdown.vue
=> feat(api): add Get Custom Rewards endpoint

src/bot/helpers/checkFilter.ts, src/panel/views/managers/commands.vue, test/tests/commands/discord#794732878595752016_param_should_be_properly_filtered.js.js
Fixes https://discord.com/channels/317348946144002050/317349069024395264/794732878595752016
=> feat(commands): add $param to be parsed in filters

src/bot/systems/timers.ts, test/tests/timers/discord#794910249910796288_disabled_response_should_not_be_sent_to_chat.js
Fixes https://discord.com/channels/317348946144002050/619437014001123338/794910249910796288
=> fix(timers): filter out disabled response

src/bot/customvariables.ts, src/bot/microservices/getUserFromTwitch.ts, src/bot/users.ts, src/panel/views/registries/custom-variables/custom-variables-code.txt
Fixes https://discord.com/channels/317348946144002050/689472699910717522/795723169239531540
=> feat(customvariables): add displayname to user function

src/bot/pubsub.ts, src/bot/tmi.ts
Also removed handling by TMI which doesn't provide such informations
Fixes #4590
=> fix(pubsub): log moderation_actions with moderator username and id

.github/workflows/tests.yml, locales/en.json, src/bot/helpers/commons/getUserSender.ts, src/bot/systems/price.ts, src/bot/tmi.ts, test/helpers/db.js, test/helpers/user.js, test/tests/permissions/check.js, test/tests/price/check.js, test/tests/tmi/redeem_command.js
… event
Fixes #4641
Fixes #4640
=> fix(price): cheer event trigger alias/custom/core commands

src/bot/helpers/parser.ts, src/bot/tmi.ts, src/panel/components/footer.vue
=> fix(parser): remove response time

src/bot/api.ts, src/bot/helpers/api/retries.ts, src/bot/microservices/setTitleAndGame.ts
Before this change we rely on getCurrentStreamData, but
this caused several issues, namely with getting title outside of a bot and
trigger proper updates
Fixes https://discord.com/channels/317348946144002050/619437014001123338/821164843406852167
=> fix(api): use getChannelInformation on online stream

locales/en.json, src/database/entity/user.ts, src/games/gamble.ts
Fixes https://community.sogebot.xyz/t/jackpot-win/217
=> feat(gamble): add !gamble wins to see how many jackpots user won

docs/_master/filters/all.md, src/filters/count.ts, src/filters/index.ts, src/message.ts, test/tests/message/count.js
=> feat(count): add count filter with time interval

locales/en/ui/registry/goals.json, src/api/registries/goals.ts, src/database/entity/goal.ts, src/database/migration/mysql/12.0.x/1592557005214-fontMissingShadow.ts, src/database/migration/mysql/13.0.x/1626478375130-addIntervalToGoals.ts, src/database/migration/postgres/12.0.x/1592557005214-fontMissingShadow.ts, src/database/migration/postgres/13.0.x/1626478375130-addIntervalToGoals.ts, src/database/migration/sqlite/12.0.x/1592557005214-fontMissingShadow.ts, src/database/migration/sqlite/13.0.x/1622378375126-goalsUpdate.ts, src/database/migration/sqlite/13.0.x/1626478375130-addIntervalToGoals.ts, src/helpers/goals/recountIntervals.ts, src/overlays/goals.ts
=> feat(goals): add support for interval goals subs/follow/tips/bits

src/database/migration/mysql/12.0.x/1613738901696-globalFontForAlerts.ts, src/database/migration/postgres/12.0.x/1613738901696-globalFontForAlerts.ts, src/database/migration/sqlite/12.0.x/1613738901696-globalFontForAlerts.ts
=> fix(migration): fix incorrect migration naming

package-lock.json, src/helpers/checkFilter.ts, src/message.ts
=> fix(checkFilter): properly set all available global variables

src/filters/evaluate.ts
Hi,
Axios might have already parsed the response as JSON if the response had the proper headers. Old code would return `"[object Object]"` for some responses.
=> fix(filters/evaluate): do not always parse JSON

src/helpers/panel.ts
Some TLS Ciphers which are used are known to be weak, this should exclude them.
Also adds the ca_bundle file to be added to .env file, as its needed to have complete certificate chain (if not self-signed anyway) without merging intermediates to ca_cert the dirty way.
=> Excluding weak TLS ciphers and adding CA_BUNDLE

src/helpers/panel.ts
Passing ciphers to be allowed not working as intended on master, this fixes TLS to work again. Also improving fallback for all that don't need to provide ca_bundle or just integrated them to .crt-file. TLSv1 and TLSv1.1 keep disabled for security reasons as this part work as intended.
=> Improving TLS CA_Bundle fix and undo cipher-excluding

d.ts/src/helpers/socket.d.ts, src/database/entity/overlay.ts, src/database/entity/randomizer.ts, src/database/migration/mysql/21.x/1678892044038-updateTTSSettings.ts, src/database/migration/postgres/21.x/1678892044038-updateTTSSettings.ts, src/database/migration/sqlite/21.x/1678892044038-updateTTSSettings.ts, src/overlays/texttospeech.ts, src/registries/alerts.ts, src/registries/randomizer.ts, src/tts.ts
=> feat: update TTS configuration
