sogebot/sogeBot

libs/systems/raffles.js
libs/widgets/raffles.js
locales/cs.json
locales/en.json
main.js
package.json
public/dist/css/custom.css
public/index.html
public/widgets/raffles.html

- removed timer
- added widget

raffles: widget add; updates and simplifications of raffle

---

config.ini
libs/panel.js
libs/twitch.js
libs/watcher.js
locales/cs.json
locales/en.json
main.js
public/dist/css/custom.css
public/index.html

Idea was to easily change game and title through dashboard
For this you need to update oauth to include privileges to change title/game (oauth.sogehige.tv is used now, you can check sogeauth on github if you want to generate oauth itself and don't believe me :))
Done:
Game and Title is updated through dashboard
Game and Title is updated through commands !game and !title
Data persistence on bot

Game and title changing

---

libs/commons.js
libs/configuration.js
libs/parser.js
package.json

Added
(random.online.viewer)
(random.online.follower)
(random.viewer)
(random.follower)
(random.number-x-to-y)

parser: add random filters (#106)

---

libs/systems/alias.js
libs/systems/customCommands.js
libs/systems/keywords.js
libs/systems/notice.js
libs/systems/price.js
libs/watcher.js
locales/cs.json
locales/en.json
migrate.js
public/pages/alias.html
public/pages/customCommands.html
public/pages/keywords.html
public/pages/notice.html
public/pages/price.html

Functionality added for prices, notices, custom commands, aliases and keywords

Simply enable/disable from dashboard

---

config.ini
libs/systems/highlights.js
locales/cs.json
locales/en.json
public/dist/css/custom.css
public/index.html
public/pages/highlights.html
test/general.js
test/moderation.js

**DONE:**
Systems/Highlight: add !highlight system #195
**TBD:**
Webpanel/Highlight: add !highlight support #196

Add Highlights system

---

libs/systems/raffles.js
libs/widgets/raffles.js
locales/cs.json
locales/en.json
public/widgets/raffles.html

Raffle ticket extension

---

libs/systems/cooldown.js
locales/cs.json
locales/en.json
public/pages/cooldown.html

Issue: https://github.com/sogehige/sogeBot/issues/335

systems/cooldown - toggle cooldown and edit in webpanel

---

libs/events.js
libs/logging.js
locales/cs.json
locales/en.json
main.js
public/index.html
public/pages/logger.html

**SERVER SIDE**
- Filtering
---
**PANEL SIDE**

Dashboard Logger

---

README.md
config.ini
libs/systems/phillipsHue.js
locales/cs.json
locales/en.json
package.json

Phillips hue support

---

libs/overlays/stats.js
libs/twitch.js
libs/users.js
locales/cs.json
locales/en.json
main.js
public/dist/css/custom.css
public/index.html
public/overlays/stats.html

Subscribers, bits in quick stats

---

libs/systems/timers.js
public/pages/timers.html

Fixing timers name renaming through UI, which was kind of forgotten
_ref: #497

timers: fix edit name through UI

---

package.json

emotes: change twitch-emoticons to my git repo until fixed

---

libs/panel.js
libs/translate.js
libs/twitch.js
locales/cs.json
locales/en.json
main.js
public/index.html
public/pages/alias.html
public/pages/cooldown.html
public/pages/customCommands.html
public/pages/keywords.html
public/pages/price.html
public/pages/ranks.html
public/pages/songs.html
public/pages/timers.html
public/pages/translations.html
public/pages/viewers.html
scss/custom.scss

Remove bot responses from systems

translate: added custom translation page

---

public/overlays/alerts.html

alerts: add support for html

---

config.example.json
libs/databases/mongodb.js
libs/databases/nedb.js
libs/events.js
libs/overlays/eventlist.js
libs/overlays/stats.js
libs/twitch.js
libs/users.js
locales/cs.json
locales/en.json
main.js
public/overlays/alerts.html
public/pages/events.html
public/pages/systems.html
public/widgets/eventlist.html
scss/custom.scss
test/helpers/messages.js
test/tests/alias/run.js
tools/migrate.js

Broadcaster oauth

---

libs/systems/songs.js

Added in a currentsong type for both playlist and song requests to
differentiate them.

Fix for bug 623

---

public/index.html

ui: fix menu blocked active state

---

libs/systems/highlights.js

highlights: fix saving highlights

---

libs/twitch.js
libs/webhooks.js

webhooks: if follows enabled, don't fire event from API

---

libs/systems/songs.js
locales/cs.json
locales/en.json
public/pages/systems.html

songs_notify will enable notification on start of each song from sr and playlist
_ref #619

songs: add songs_notify settings

---

public/index.html

ui: fix new title creation through dialog

---

libs/twitch.js

twitch: move !top to 3 commands

---

libs/panel.js
libs/twitch.js
libs/webhooks.js

webhooks: stream start/stop topic

---

libs/panel.js

panel: domains will work with `www` even if not defined

---

public/pages/alias.html
public/pages/cooldown.html
public/pages/customCommands.html
public/pages/keywords.html
public/pages/timers.html

ui: fix renaming may contain html tags

---

public/index.html
public/pages/timers.html

ui: fixes for not proper save of abbr contenteditable

---

locales/cs.json
locales/en.json
public/overlays/eventlist.html

Added display _GET to specify what and how to show lines
default value is username,event
Updated behavior of count, where with order asc returns first->count lines
which was not expected, should show count->last with asc order
Added subgift support
Added more classes to events for better customization
_ref: #720

overlays: eventlist update

---

libs/events.js
public/index.html
public/pages/events.html
scss/custom.scss

ui: change inputs to abbr

---

libs/systems/moderation.js
package.json
test/helpers/tmi.js
test/tests/moderation/blacklist.js
test/tests/moderation/whitelist.js

\+ => at least 1 more char -> +test === atest, btest, 1test
\* => no additional chars are required -> *test === test, atest, btest
#690 - Request: some more for blacklist.

[WIP] moderation: add + and * support for blacklist and whitelist

---

libs/events.js
libs/twitch.js
locales/cs.json
locales/en.json
main.js
public/pages/events.html
public/pages/systems.html
scss/custom.scss
tools/migrate.js

Before it was globally set and not intuitive
_ref #771

events: Moved hosted triggers to events

---

libs/twitch.js

twitch: Added retries to status check

---

libs/overlays/credits.js
public/overlays/credits.html
public/pages/overlays.html

overlays: Added dynamic socials to credits

---

libs/events.js
locales/cs.json
locales/en.json

Events: Added fade out option to command-send-x-times

---

main.js
public/pages/viewers.html

Users: Added bits to user stats

---

config.example.json
libs/events.js
libs/integrations/streamlabs.js
libs/overlays/eventlist.js
libs/widgets/eventlist.js
locales/cs.json
locales/en.json
public/widgets/eventlist.html

Added 'tip' event, updated eventlist with 'tip' event

Integrations, Streamlabs: Added streamlabs integration

---

config.example.json
libs/integrations/donationalerts.js

Integrations, DonationAlerts.ru: Added DonationAlerts.ru integration

---

package.json
public/index.html
public/pages/viewers.html
tools/copy-dist-files.js

UI, Routers: Added simple routing

---

libs/commons.js
libs/systems/moderation.js

Message for each moderation will be sent only every 60s
_ref: #765

Moderation: Added cooldown for moderation messages

---

libs/overlays/credits.js
locales/cs.json
locales/en.json
public/overlays/credits.html
public/pages/overlays.html

Overlays, Credits: Added aggregation

---

dist/js/commons.js
libs/panel.js
package.json
public/dist/js/commons/commons.js
public/index.html
public/popout.html
public/widgets/chat.html
public/widgets/eventlist.html
tools/copy-dist-files.js

UI, Widgets: Added popout option to eventlist and chat

---

libs/logging.js
package.json

Log, Winston: Added log rotation

---

public/widgets/eventlist.html
scss/colors.scss
scss/custom.scss
scss/themes/dark.scss
scss/themes/light.scss

ui/css: Fix colors and simplify theme coloring

---

cluster.js
libs/games/heist.js
libs/systems/bets.js
libs/systems/gambling.js
libs/systems/points.js
libs/systems/price.js
libs/systems/raffles.js
libs/twitch.js
libs/users.js
test/helpers/db.js
test/tests/points/getPointsFromUser.js
test/tests/raffles/pick.js
tools/migrate.js

system/points: Add user.points collection

---

libs/expects.js
libs/overlays/bets.js
libs/systems/bets.js
libs/widgets/bets.js
locales/cs.json
locales/en.json
public/overlays/bets.html
public/pages/overlays.html
public/widgets/bets.html
scss/themes/dark.scss

- bets should have adjustable starting bet message - Can be done through custom translations
- possibility to create bet from widget - Widget will be used only for bet closing, bet opening can be done through cmdboard widget

Refactor of bets system

---

dist/js/commons.js
libs/overlays/imageCarousel.js
locales/cs/ui.page.settings.overlays.carousel.json
locales/en/ui.page.settings.overlays.carousel.json
public/overlays/carousel.html
public/pages/overlays.html
public/settings/overlays/carousel.html
scss/custom.scss

- order, duration, waitBefore, waitAfter, animationIn, animationInDuration, animationOut, animationOutDuration
- https://github.com/sogehige/sogeBot/issues/697
- https://ideas.sogehige.tv/ideas/23/allow-image-carousel-to-have-a-timer
Files uploaded are not used anymore, as image is saved as base64 directly to database

overlay/imageCarousel: Function extension

---

cluster.js
libs/api.js
libs/events.js
libs/webhooks.js
locales/cs.json
locales/en.json

- This will allow to trigger events for example by spamming emotes
#996

lib/events: Add keyword-send-x-times event

---

libs/api.js
libs/events.js
locales/cs.json
locales/cs/api.clips.json
locales/en.json
locales/en/api.clips.json

lib/events: Add create-a-clip and create-a-clip-and-play-replay events 

---

main.js

- 1 cpu by default if not specified in config

main: 1 cpu by default if not specified in config

---

libs/api.js
libs/message.js
libs/overlays/alerts.js
libs/overlays/credits.js
libs/systems/commercial.js
libs/systems/highlights.js
libs/webhooks.js
libs/widgets/chat.js
package.json

various: Make bot snekfetch 4.0.0 compatible

---

README.md
libs/games/wheelOfFortune.js
locales/cs/ui.games.wheeloffortune.json
locales/en/ui.games.wheeloffortune.json
package.json
public/index.html
public/overlays/wheeloffortune.html
public/pages/games.html
public/pages/overlays.html
public/settings/games/wheeloffortune.html
scss/custom.scss
tools/copy-dist-files.js

https://github.com/sogehige/sogeBot/issues/139

Wheel of fortune

---

libs/api.js
libs/events.js
libs/overlays/credits.js
libs/widgets/eventlist.js
locales/cs.json
locales/en.json
main.js
public/overlays/credits.html
public/widgets/eventlist.html

https://github.com/sogehige/sogeBot/issues/1012

main: Add raid support

---

main.js

main: Add new_chatter ritual

---

.gitignore
libs/panel.js

Add custom endpoint for custom html files (for alerts, etc)

lib/panel: Add custom subfolder

---

libs/systems/highlights.js

system/highlight: Use axios instead of tmi api call

---

libs/customvariables.js

lib/customvariable: Return full axios object on url()

---

libs/systems/points.js

Removed calculation of points and adding points manually

system/points: Force set points in setPoints

---

libs/panel.js
public/index.html

Quick stats updates - sticky, shorten numbers

---

libs/events.js

lib/events: Reorder atrributes by length

---

libs/databases/mongodb.js
libs/databases/nedb.js
main.js

These changes should fix errors on unique index.
Removal of join/part tmi listeners is due to theirs unpredictibility and as they are not working on bigger channels. Current implementation of online check should be enough, even though its used through unofficial API currently
#1046

Fixes for #1046

---

libs/cache.js
libs/panel.js
public/index.html

lib/cache, lib/panel: Access game titles cache directly

---

docs/_sidebar.md
docs/commands/quotes.md
libs/commons.js
libs/configuration.js
libs/expects.js
libs/panel.js
libs/parser.js
libs/permissions.js
libs/systems/quotes.js
libs/users.js
locales/cs/systems.quotes.json
locales/cs/ui.dialog.json
locales/cs/ui.menu.json
locales/cs/ui.systems.quotes.json
locales/en/systems.quotes.json
locales/en/ui.dialog.json
locales/en/ui.menu.json
locales/en/ui.systems.quotes.json
public/pages/quotes.html
public/pages/quotes/edit.html
public/public/quotes.html
test/helpers/db.js
test/helpers/messages.js
test/tests/permissions/override.js
test/tests/quotes/add.js
test/tests/quotes/remove.js
test/tests/quotes/set.js
test/tests/quotes/show.js

- `!quote add -quote "<text>"` - default tag is general
- `!quote add -tag some_tag, tag2 -quote <text>`
- `$sender, quote <id> '<text>' was added (tags: ...)`
- `!quote set -tag some_tag -id <id>`
- tag and quote parameters are optional
- `!system enable/disable quotes`?
- `!quote some_tag` - random quote from tag
- `!quote id` - direct quote
#368

[WIP] system/quotes

---

libs/api.js

lib/api: Add retry for getChannelSubscribersOldAPI

---

libs/api.js

Retry get channel subscribers old api

---

libs/api.js
libs/logging.js

lib/logging: Add stream start/stop logging

---

libs/events.js

lib/events: Fix atUsername ignore for usernames

---

libs/api.js

lib/api: Fix log.stop Promise error

---

dist/js/components.js

js/component: Fixed sending undefined onUpdate

---

docs/howto/write-own-system.md

docs: Updated missing exports in howto

---

src/bot/_interface.js
src/bot/message.js

src/interface: Remove redundant console.log

---

public/pages/customcommands/edit.html
public/pages/keywords/edit.html
public/pages/price/edit.html
public/pages/quotes/edit.html
public/pages/ranks/edit.html

ui/various: Fix incorrect search critearia sent

---

src/bot/_interface.js

src/interface: Add cleanup for undefined settings values

---

src/bot/logging.js

src/logging: Add missing raid level

---

src/bot/api.js

src/api: Fix getCurrentStreamData loop

---

.npmrc
docs/install-and-upgrade.md
src/bot/api.js
src/bot/commons.js
src/bot/databases/interface.js
src/bot/databases/mongodb.js
src/bot/databases/nedb.js
src/bot/twitch.js

Top updates

---

tools/migrate.js

tool/migrate: Fix migration of settings

---

src/bot/systems/moderation.js
test/tests/moderation/blacklist.js

Fix for loop returning after first item even when there are more words

system/moderation: Fix blacklist moderation loop

---

Makefile

make prepare - delete node_modules and shrinkwrap
make clean - cleanup dist

makefile: split clean to prepare and clean

---

cluster.js
main.js
package.json
src/bot/systems/moderation.js
src/bot/systems/quotes.js

chore: Update to twitch-js 2.0.0-beta.9

---

.travis.yml
Makefile
main.js
src/bot/commons.js
test/general.js
test/helpers/messages.js

src/commons: Fix message sending

---

public/pages/cooldown/edit.html
public/pages/cooldown/list.html

ui/cooldown: Add missing type toggles

---

.travis.yml
src/bot/events.js

src/event: Fix commercial operation

---

main.js

main: Check raw message for hosts

---

public/pages/cooldown/edit.html

ui/cooldown: Fix not saving of type

---

src/bot/twitch.js

src/twitch: Fix !top points undefined values

---

cluster.js
main.js
src/bot/api.js
src/bot/commons.js
src/bot/twitch.js
src/bot/users.js

Database will be updated only on start and on ignorelist change,
this will improve response time on all ignorelist checks

src: Add ignorelist to memory

---

src/bot/systems/moderation.js
test/tests/moderation/whitelist.js

system/moderation: Fix !songrequest and sr aliases whitelist

---

src/bot/commons.js
src/bot/widgets/chat.js

Chatters ignore

---

src/bot/commons.js

src/commons: Fix events  fireRunCommand with null sender

---

locales/cs/ui.systems.songs.json
locales/en/ui.systems.songs.json
public/pages/songs/bannedsongs.html
public/pages/songs/playlist.html
src/bot/systems/songs.js
test/tests/games/duel.js

ui/songs: Add volume and trim change

---

locales/cs.json
locales/en.json
src/bot/events.js
tools/migrate.js

src/events: Add reset each message toggle for keyword-send-x-times

---

locales/cs.json
locales/en.json
src/bot/games/duel.js
src/bot/games/fightme.js
src/bot/systems/bets.js
test/tests/games/duel.js
test/tests/games/fightme.js

Dependencies

---

src/bot/games/seppuku.js

game/seppuku: Add reason for seppuku timeout

---

docs/_sidebar.md
docs/tools/migration-nedb-mongodb.md
docs/tools/users-cleanup.md
tools/nedb-to-mongodb.js

docs: Add tools documentation

---

test/tests/moderation/whitelist.js

test: Remove redundant console.log

---

locales/cs.json
locales/en.json
src/bot/databases/nedb.js
src/bot/twitch.js

https://ideas.sogehige.tv/posts/7/new-command-top-followage

src/twitch: Add !top followage

---

src/bot/games/fightme.js
src/bot/systems/bets.js
src/bot/systems/songs.js

system: Fix missing await for message prepare

---

package.json

chore: Update twitch-js 2.0.0-beta14

---

tools/migrate.js

tool/migrate: Fix error on permission migration

---

.gitignore
Makefile
cluster.js
main.js
package.json
src/bot/panel.js
src/bot/systems/cooldown.js
test/tests/message/cvars.js
test/tests/message/if.js
tools/cleanup.js
tools/migrate.js

Public fix

---

test/general.js

test: Disable translations metrics

---

src/bot/systems/moderation.js
test/general.js
test/tests/moderation/caps.js

system/moderation: Fix emote parsing on caps

---

src/bot/translate.js

src/translate: Send metrics only if metrics are enabled

---

src/panel/widgets/components/twitch.vue

panel/twitch: Fix link for twitch player

---

src/bot/databases/master.js

database/master: Add isConnected() check to worker

---

src/bot/api.js
src/bot/commons.js
src/bot/databases/database.js
src/bot/databases/interface.js
src/bot/databases/mongodb.js
src/bot/databases/nedb.js
src/bot/main.js
test/general.js
tools/cleanup.js
tools/migrate.js

 src/main: Add oauth checks

---

src/bot/translate.js

src/translate: Send metrics only once on use

---

src/bot/translate.js

Metrics update

---

src/bot/panel.js
src/bot/translate.js

src/translate: Add check for ui/webpanel keys

---

Makefile

make: Update files to zip

---

src/bot/users.js

src/users: Fix watched time set

---

src/bot/api.js

src/api: Update follow check

---

public/pages/games.html
public/pages/systems.html

ui: Show menu item only after being selected

---

package.json

package: 8.1.0-SNAPSHOT

---

src/bot/users.js

src/users: Fix user removal

---

src/bot/users.js

src/users: Fix removal of user watched and points

---

src/bot/api.js

src/api: Hide error message if account don't exist

---

public/index.html

ui/dash: Fix version set if github returns error

---

src/bot/overlays/eventlist.js

overlay/eventlist: Fix undefined cheer

---

src/bot/systems/bets.js

src/bets: Fix incorrect command on bet open

---

src/bot/systems/bets.js

Bet open fix

---

src/bot/databases/mongodb.js

db/mongodb: Change deprecated functions

---

package.json

chore: Update winston to version 3.1.0

---

src/bot/cluster.js
src/bot/databases/master.js

db/master: Add support for count

---

package.json

chore: Update page to version 1.9.0

---

src/panel/widgets/components/ytplayer.vue

widget/ytplayer: Fix loading next song

---

docs/8.1.x/README.md
docs/8.1.x/install-and-upgrade.md
docs/README.md
docs/install-and-upgrade.md

docs: Remove greenkeeper badge

---

src/bot/main.js
src/bot/translate.js

Stats ignore errors

---

src/bot/systems/customCommands.js

system/customCommands: Fix response add on command create

---

locales/en/ui.systems.keywords.json

locale/en: Fix missing keyword locales

---

test/tests/raffles/pick.js

tests: Add test for subscriber keyword raffle

---

public/overlays/alerts.html
src/bot/databases/master.js

 overlay/alerts: Fix alert freeze after missing image 

---

src/bot/systems/songs.js

songs: Fix incorrect locale

---

src/bot/databases/mongodb.js
src/bot/main.js
tools/migrate.js

db/mongodb: Fix primary key creation on migrate

---

src/bot/twitch.js

twitch: Fix lastseenUpdate userId check

---

src/bot/cluster.js
src/bot/heapdump.js
src/bot/main.js

heap: Save heaps to same directory

---

test/tests/games/fightme.js
test/tests/raffles/pick.js

tests: Remove forgotten .only

---

docs/8.1.x/filters/all.md
locales/cs.json
locales/en.json
src/bot/cluster.js
src/bot/commons.js
src/bot/configuration.js
src/bot/customvariables.js
src/bot/events.js
src/bot/games/wheelOfFortune.js
src/bot/integrations/phillipsHue.js
src/bot/logging.js
src/bot/main.js
src/bot/message.js
src/bot/overlays/alerts.js
src/bot/overlays/emotes.js
src/bot/systems/alias.js
src/bot/systems/highlights.js
src/bot/systems/songs.js
src/bot/twitch.js
test/general.js

src: Add check if process.send is available

---

src/bot/expects.js
src/bot/systems/cooldown.js
src/bot/systems/customCommands.js
test/helpers/db.js
test/tests/cooldowns/check.js

cooldown: Fix checking for command in whole message

---

src/bot/twitch.js

twitch: Fix deprecation warnings

---

src/bot/main.js

main: Fix TMI indicator on reconnect

---

public/index.html
public/pages/viewers/edit.html

ui: Fix double loading of pages

---

src/bot/panel.js
src/panel/widgets/components/eventlist.vue

ui/eventlist: Fix incorrect settings load

---

.travis.yml
package.json

chore: Remove travis email notification and add mocha retries

---

src/bot/events.js
src/bot/webhooks.js
test/helpers/db.js
test/helpers/messages.js
test/tests/events/follow.js

tests: Add follow event tests

---

package.json
src/bot/cache.js
src/bot/cluster.js
src/bot/databases/database.js
src/bot/databases/worker.js
src/bot/games/duel.js
src/bot/main.js
src/bot/webhooks.js
test/helpers/messages.js
test/tests/games/duel.js
test/tests/points/get.js
test/tests/price/check.js
test/tests/raffles/pick.js
test/tests/webhooks/follower.js

Db worker fix

---

src/bot/cluster.js
src/bot/databases/database.js
src/bot/databases/master.js
src/bot/main.js

db/nedb: Switch nedb master/cluster relation

---

src/bot/api.js

api: Fix ending loop when token is empty

---

src/bot/commons.js
src/bot/main.js

main: Fix message send to broadcaster

---

src/bot/systems/moderation.js

moderation: Fix emotes parsing on whisper

---

src/bot/commons.js
src/bot/main.js
src/bot/oauth.js
src/bot/overlays/credits.js

oauth: Fix channelId fetch

---

src/bot/tmi.js
src/bot/users.js

users: Add fallback to ritual new_chatters

---

docs/8.1.x/_sidebar.md
docs/8.1.x/commands/overlays.md
docs/_sidebar.md
docs/commands/overlays.md

docs: Add missing link to overlay commands

---

public/overlays/alerts.html

alerts: Throw error if text alert is missing text

---

src/bot/webhooks.js

webhooks: Fix channelId check

---

src/bot/oauth.js

oauth: Change to new chat scopes

---

src/bot/events.js
src/bot/panel.js
src/bot/tmi.js

oauth: Fix multiple listeners and joins

---

public/pages/registry/customVariables/edit.html

ui: Fix saving new variable on edit

---

src/bot/systems/raffles.js
src/bot/tmi.js

 raffles: Remove participants on raffle create 

---

locales/cs.json
locales/en.json
src/bot/systems/points.js
src/bot/twitch.js

 points: Fix incorrect commands if customized

---

src/bot/api.js
src/bot/systems/highlights.js
src/bot/webhooks.js

highlights: Create marker for highlight 

---

src/bot/api.js
src/bot/oauth.js
src/bot/systems/highlights.js
src/bot/users.js

This will allow to properly reset rate count and not over poll limit
again

 api: set properly ratelimit reset on 429 

---

src/bot/api.js

Changed GET to POST, also data was not in right format in axios
Fixes #1418
- [x ] commit message follows [commit guidelines](https://github.com/sogehige/sogeBot/blob/master/CONTRIBUTING.md#commit-guidelines)

api: fix marker POST creation

---

src/bot/api.js

api: change timeouts for data fetch

---

src/bot/api.js
src/bot/commons.js
src/bot/oauth.js
src/bot/systems/points.js
src/bot/tmi.js
src/bot/users.js
src/bot/webhooks.js

api: make api shareable between worker/master

---

src/bot/api.js

api: change interval for intervalFollowerUpdate

---

PULL_REQUEST_TEMPLATE.md

chore: remove spaces from PR template

---

src/bot/systems/points.js

points: add missing toArray() on expects

---

src/bot/tmi.js

tmi: remove redundant console.log

---

src/bot/api.js
src/bot/webhooks.js

webhooks: Fix getGameFromId call

---

src/bot/systems/points.js

Fixes https://github.com/sogehige/sogeBot/issues/1433

points: fix !points give incorrect getByName call

---

src/bot/commons.js

Fixes https://github.com/sogehige/sogeBot/issues/1372

commons: remove item if index doesn't exist for compact

---

src/bot/_interface.js
src/bot/api.js
src/bot/commons.js
src/bot/configuration.js
src/bot/databases/interface.js
src/bot/databases/mongodb.js
src/bot/databases/nedb.js
src/bot/games/duel.js
src/bot/games/fightme.js
src/bot/main.js
src/bot/message.js
src/bot/oauth.js
src/bot/panel.js
src/bot/parser.js
src/bot/tmi.js
src/bot/twitch.js
src/bot/users.js
src/bot/widgets/chat.js
test/general.js
test/helpers/db.js
test/helpers/variable.js
test/tests/games/duel.js
test/tests/message/cvars.js
tools/migrate.js

This will allow onChange events, also cluster/master share of variable values
Fixes #1374

interface: proxify settings

---

public/overlays/credits.html
src/bot/overlays/credits.js

credits: play clips through plyr to force unmute

---

PULL_REQUEST_TEMPLATE.md
src/bot/oauth.js

oauth: wait for tmi to be ready

---

src/bot/api.js

api: fix incorrect error handling on 429 error

---

src/bot/tmi.js

tmi: fix typo in error logging

---

src/bot/webhooks.js

webhooks: unsubscribe on start

---

src/bot/webhooks.js

webhooks: fix incorrect if check

---

src/bot/api.js
src/bot/systems/points.js

points: allow points give to any user

---

src/bot/twitch.js

twitch: set watched 0 on undefined user

---

src/bot/commons.js
src/bot/games/duel.js
src/bot/games/fightme.js
src/bot/games/gamble.js
src/bot/games/heist.js
src/bot/games/roulette.js
src/bot/systems/bets.js
src/bot/systems/points.js
src/bot/systems/price.js
src/bot/systems/raffles.js
src/bot/users.js

points: add __COMMENT__ error stack for tracking NaN points

---

locales/cs/ui/systems/users.json
locales/en/ui/systems/users.json
src/bot/commons.js
src/bot/users.js
test/helpers/db.js
tools/migrate.js

users: add ignorelist to settings page

---

.travis.yml

chore: add osx and windows to travis tests

---

docs/8.1.x/commands/custom-commands.md
locales/cs/ui.systems.customcommands.json
locales/en/ui.systems.customcommands.json
public/pages/customcommands/edit.html
public/pages/customcommands/list.html
src/bot/systems/customCommands.js
test/tests/commands/run.js

customcommands: add response filters

---

src/bot/tmi.js

tmi: fix incorrect username in subscription

---

src/bot/tmi.js

tmi: fix incorrect username for events

---

src/bot/tmi.js

tmi: fix subgift incorrect parameters parsing

---

src/panel/widgets/components/customvariables.vue

customvariables: change option buttons to option select

---

Makefile

makefile: add env information on the end of cycle

---

src/bot/api.js
src/bot/twitch.js
src/bot/users.js

users: fetch username if its missing in db

---

src/bot/games/roulette.js
test/tests/games/roulette.js

roulette: fix incorrect reward points given to users

---

src/bot/expects.js
test/tests/points/give.js

expects: fix incorrect points regexp

---

src/bot/tmi.js

tmi: fix incorrect username on cheer

---

.travis.yml

travis: set nodejs version to 11

---

docs/8.1.x/commands/moderation.md
test/tests/moderation/whitelist.js

test: add whitelist url test

---

docs/8.1.x/commands/moderation.md
src/bot/systems/moderation.js
test/tests/moderation/whitelist.js

moderation: fix asterisk and plus regexp for urls

---

public/pages/customcommands/edit.html
src/bot/systems/customCommands.js

commands: fix response editation

---

src/bot/_interface.js

interface: fix incorrect global onchange call on root keys

---

src/panel/widgets/components/join.vue
src/panel/widgets/components/part.vue

join, part: sort lists by date asc

---

src/bot/databases/interface.js
src/bot/databases/mongodb.js
tools/migrate.js

migrate: drop unused collections from mongodb

---

src/bot/overlays/emotes.js
src/overlay/components/emotes.vue

Emotes overlay fix

---

locales/cs/ui.commons.json
locales/cs/ui.dialog.json
locales/en/ui.commons.json
locales/en/ui.dialog.json
public/pages/registry/carouselOverlay/edit.html
public/pages/registry/carouselOverlay/list.html

carousel: add missing locale

---

public/pages/games.html

games: remove additional angle-right icon

---

src/overlay/components/alerts.vue

alerts: fix delay apply on audio/video

---

tools/migrate.js

migrate: fix error if gallery dir is missing

---

package.json

package: 8.2.0-SNAPSHOT

---

public/pages/viewers/edit.html
src/bot/users.js

users: fix followed since check

---

public/pages/highlights/list.html
src/bot/api.js
src/bot/systems/highlights.js

highlights: fix incorrect highlight save

---

src/overlay/components/stats.vue

stats: set refresh interval to 1000ms

---

src/bot/overlays/emotes.js

emotes: fetch only on start or on cache remove

---

src/bot/constants.js

constants: add time constants

---

src/bot/api.js
src/bot/webhooks.js
test/tests/webhooks/follower.js

api: use from_name from payload

---

public/pages/registry/gallery/list.html
public/pages/registry/textOverlay/list.html

ui: fix loading of header translations

---

src/bot/overlays/emotes.js

emotes: remove lastFetch variable

---

src/bot/api.js
src/bot/events.js

And up check time, if api is slow
Fixes #1552

api: fix createClip interval

---

docs/_master/commands/cooldowns.md
docs/commands/cooldowns.md
locales/cs.json
locales/en.json
public/pages/cooldown/edit.html
public/pages/cooldown/list.html
src/bot/systems/cooldown.js
test/tests/cooldowns/toggleSubscribers.js
tools/migrate.js

Owner can set, if subscribers can bypass cooldown as mods and owner
Fixes #1551

cooldown: add subscriber toggle

---

locales/cs/ui.dialog.json
locales/en/ui.dialog.json
public/pages/registry/carouselOverlay/edit.html
public/pages/registry/textOverlay/edit.html
public/pages/viewers/edit.html

ui: add locale for mark to delete

---

src/overlay/components/credits.vue

credits: add game boxart

---

src/overlay/components/credits.vue

credits: usernames are unique and merged

---

src/bot/commons.js
src/bot/games/seppuku.js

commons: fix timeout reason $sender replacement

---

dist/js/components.js
locales/cs/ui.commons.json
locales/cs/ui.dialog.json
locales/en/ui.commons.json
locales/en/ui.dialog.json
public/pages/registry/gallery/list.html
public/pages/registry/textOverlay/list.html

ui: add textOverlay delete and show more buttons

---

package.json
src/panel/widgets/components/ytplayer.vue

Fixes #1563
There may be some [Vue warn], this is originating from VuePlyr
and not implementation of widget

widgets: fix ytplayer plyr player

---

docs/commands/overlays.md

docs: overlays x/y-offset, align added to 8.1.x

---

src/bot/integrations/donationalerts.js
src/bot/integrations/streamlabs.js
src/bot/logging.js
src/bot/users.js

also added tip logging
Fixes #1568
Fixes #1569

integrations: fix tip saving to user

---

public/pages/highlights/list.html

highlights: show in ui in right order

---

docs/_master/filters/all.md
src/bot/message.js

This filter will generate url safe string

message: add (url|#) filter

---

src/bot/_interface.js
src/bot/oauth.js

IDEA https://ideas.sogebot.xyz/posts/85/auto-push-broadcaster-to-owners

oauth: add broadcaster username to owners

---

src/bot/integrations/donationalerts.js

Sometimes donationalerts socket client lost connection, do reconnect.

donationalerts: reconnect to socket every hour

---

src/bot/integrations/donationalerts.js

donationalerts: move setInterval() to the right place

---

public/popout.html
src/panel/widgets/components/chat.vue
src/panel/widgets/popout.js
src/panel/widgets/widgets.js

widgets: chat should be dark if dark theme is used

---

src/bot/currency.js

currency: fix NaN currency rates

---

public/pages/registry/gallery/list.html
src/bot/_interface.js

Speed up process of loading, data is not used in list generation

gallery: remove data from socket find

---

locales/cs.json
locales/en.json
src/bot/commons.js
src/bot/games/fightme.js
src/bot/oauth.js
src/bot/tmi.js
src/bot/twitch.js
src/panel/widgets/components/ytplayer.vue
test/tests/games/fightme.js

 fightme: add $loser to messages

---

flow-typed/global.js
locales/cs.json
locales/cs/ui.menu.json
locales/en.json
locales/en/ui.menu.json
public/pages/core.html
public/pages/overlays.html
src/bot/_interface.js
src/bot/currency.js
src/bot/integrations/donationalerts.js
src/bot/integrations/streamlabs.js
src/bot/overlays/credits.js
src/bot/panel.js
src/bot/twitch.js
src/bot/users.js
tools/migrate.js

currency: move library to interface

---

docs/_master/commands/cooldowns.md
locales/cs.json
locales/en.json
public/pages/cooldown/edit.html
public/pages/cooldown/list.html
src/bot/systems/cooldown.js
test/tests/cooldowns/toggleFollowers.js

cooldown: add follower toggle

---

public/pages/cooldown/edit.html
public/pages/cooldown/list.html
src/bot/_interface.js
src/bot/systems/cooldown.js

cooldown: fix incorrect states in ui

---

src/bot/_interface.js

interface: load only defined settings

---

dist/js/components.js
locales/cs/ui.systems.bets.json
locales/en/ui.systems.bets.json
public/pages/core.html
public/pages/games.html
public/pages/overlays.html
public/pages/systems.html
src/bot/_interface.js
src/bot/overlays/clips.js
src/bot/overlays/credits.js
src/bot/overlays/emotes.js
src/bot/systems/bets.js
src/bot/systems/songs.js
src/bot/widgets/bets.js

ui: add number input for settings

---

src/bot/api.js

api: remove getGameFromId master restriction

---

src/bot/api.js
src/bot/webhooks.js

Fixes #1591
Fixes #1592 (should)

api: update interval loops

---

src/bot/api.js
src/bot/webhooks.js

api: fix typo in user update

---

dist/js/components.js
public/pages/alias/edit.html
public/pages/alias/list.html
public/pages/cooldown/list.html
src/bot/systems/alias.js

UI updates

---

src/bot/users.js

users: fix null currency symbol

---

locales/cs/ui.menu.json
locales/cs/ui/systems/clipscarousel.json
locales/en/ui.menu.json
locales/en/ui/systems/clipscarousel.json
src/bot/overlays/clipsCarousel.js
src/overlay/components/clipscarousel.vue

overlays: add simple clips carousel

---

src/bot/api.js
src/bot/databases/master.js
src/bot/webhooks.js
test/tests/webhooks/follower.js

database: throw error on master update before sending to cluster

---

locales/cs/ui/systems/clipscarousel.json
locales/en/ui/systems/clipscarousel.json
src/bot/overlays/clipsCarousel.js
src/overlay/components/clipscarousel.vue

clipscarousel: add time to nect clip settings

---

src/overlay/components/clipscarousel.vue

clipscarousel: make carousel infinite

---

src/bot/_interface.js

interface: properly load enabled state

---

public/index.html
public/pages/core.html
public/pages/games.html
public/pages/overlays.html
public/pages/systems.html

ui: add permanent hash links for settings

---

src/bot/webhooks.js

Also added additional logging for follower event

webhooks: fix resubscribe after while

---

src/bot/api.js
test/helpers/messages.js
test/tests/api/getLatest100Followers.js

tests: add getLatest100Followers test with example data

---

public/pages/core.html

ui: fix core settings page incorrect variable

---

src/bot/webhooks.js

webhooks: change follows topic per twitch docs

---

src/bot/databases/nedb.js

nedb: add more information on errors

---

src/bot/api.js
src/bot/webhooks.js

Force lower cased username

---

src/bot/databases/nedb.js

nedb: properly rethrow error

---

public/pages/events.html
src/bot/databases/nedb.js

Events fixes

---

src/bot/webhooks.js
test/tests/webhooks/follower.js

webhooks: follower event data is not an array

---

docs/_master/commands/moderation.md
src/bot/systems/moderation.js
test/tests/moderation/whitelist.js

moderation: add domain:example.com whitelisting

---

public/pages/registry/textOverlay/edit.html
public/pages/registry/textOverlay/list.html
src/bot/overlays/text.js
src/overlay/components/text.vue

overlay: add customizable css, js to text overlay

---

public/pages/registry/textOverlay/list.html

registry: add toggle for html/css/js for text overlay

---

public/pages/registry/textOverlay/list.html

registry: fix text overlay error when missing css/js

---

src/bot/webhooks.js

webhooks: fix follow event subscribe  url

---

src/bot/webhooks.js

webhooks: fix subscribe event

---

src/bot/integrations/spotify.js

integrations: fix spotify song cleanup

---

src/bot/integrations/spotify.js

integrations: remove current song check if offline

---

tools/migrate.js

migrate: fix donationalerts clientSecret migration

---

src/bot/twitch.js

twitch: filter channel and not broadcaster

---

docs/_master/integrations/spotify.md
src/bot/integrations/spotify.js
src/bot/logging.js
src/bot/systems/moderation.js

integrations: add spotify integration song request support for song link

---

public/pages/registry/textOverlay/edit.html

registry: fix text overlay button on create

---

public/pages/registry/textOverlay/list.html

registry: fix text overlay prism refresh on delete

---

public/index.html
public/pages/apistats.html

ui: api stats should group by minute

---

src/bot/integrations/spotify.js

Fix refreshing accessToken
Fixes #1656

spotify: fix authorization of user on start

---

src/bot/_interface.js

interface: up time limit for load

---

public/pages/registry/textOverlay/edit.html
src/bot/overlays/text.js
src/overlay/components/text.vue

overlay: add external js support for text overlay

---

src/bot/integrations/donationalerts.js

donationalerts: cleanup socket on disconnect

---

src/overlay/components/text.vue

overlay: fix loading of external JS if its empty

---

src/bot/_interface.js

interface: hide overlays from status check

---

src/bot/expects.js
src/bot/parser.js
src/bot/systems/cooldown.js
test/tests/parser/caseSensitiveCommands.js

cooldown: fix threadlock with uppercased commands

---

src/panel/others/checklist.vue

checklist: fix undefined error

---

src/panel/others/checklist.vue

checklist: add settings message to button

---

locales/cs.json
locales/cs/ui.menu.json
locales/en.json
locales/en/ui.menu.json
public/index.html
public/pages/apistats.html
public/pages/logger.html
src/bot/api.js
src/bot/logging.js

ui: move api stats to logs

---

public/index.html
src/panel/widgets/dashboard.vue

ui: update styling of dashboard list

---

src/bot/twitch.js
test/helpers/db.js
test/helpers/messages.js
test/tests/twitch/followers.js
test/tests/twitch/subs.js

tests: add online check for subs and followers

---

src/panel/widgets/components/twitch.vue

widget: add twitch monitor refresh button

---

src/overlay/components/clipscarousel.vue

overlay: fix clips carousel loop

---

src/panel/others/checklist.js
src/panel/widgets/components/chat.vue
src/panel/widgets/components/twitch.vue
src/panel/widgets/popout.vue

widget fixes

---

src/overlay/components/alerts.vue

alerts: fix video black border on first frames

---

src/bot/panel.js

This is not needed as client has own set of data
Fixes #1690

panel: remove resending widgets on update

---

package.json

package: 8.3.0-SNAPSHOT

---

src/bot/databases/mongodb.js
src/bot/databases/nedb.js

Db keys fix

---

src/bot/commons.js
src/bot/events.js
src/bot/systems/points.js
src/bot/tmi.js
test/tests/events/cheer.js

tmi: Save user id on cheer before other actions

---

index.d.ts

d.ts: Update definition for InterfaceSettings

---

tools/migrate.js

migrate: fix version of migration to 8.2.1

---

tools/migrate.js

migrate: fix version of migration to 8.2.1 (fix of commit)

---

locales/cs.json
locales/en.json
public/pages/viewers/edit.html
public/pages/viewers/list.html
src/bot/tmi.js

Subgift count

---

docs/_master/_sidebar.md
docs/_master/commands/top.md
index.d.ts
locales/cs.json
locales/cs/systems/top.json
locales/en.json
locales/en/systems/top.json
package.json
src/bot/databases/nedb.js
src/bot/systems/top.ts
src/bot/twitch.js
src/panel/views/managers/polls.vue
test/helpers/db.js
test/tests/top/bits.js
test/tests/top/followage.js
test/tests/top/gifts.js
test/tests/top/messages.js
test/tests/top/points.js
test/tests/top/time.js

systems: move !top to own system

---

locales/cs/ui.registry.customvariables.json
locales/en/ui.registry.customvariables.json
public/pages/registry/customVariables/edit.html
src/bot/customvariables.js

IDEA https://ideas.sogebot.xyz/posts/46/history-of-variable
https://github.com/sogehige/sogeBot/projects/16#card-15669021

customvariables: Add variable history

---

docs/_master/commands/top.md
locales/cs/systems/top.json
locales/en/systems/top.json
src/bot/systems/top.ts
test/tests/top/subage.js

IDEA https://ideas.sogebot.xyz/posts/99/top-subage

 top: add subage

---

PULL_REQUEST_TEMPLATE.md
locales/cs/ui.menu.json
locales/cs/ui/systems/polls.json
locales/cs/ui/systems/top.json
locales/en/ui.menu.json
locales/en/ui/systems/polls.json
locales/en/ui/systems/top.json

top: Fix missing locales

---

src/bot/_interface.js
src/bot/parser.js
src/bot/systems/top.ts
test/tests/top/bits.js
test/tests/top/followage.js
test/tests/top/gifts.js
test/tests/top/messages.js
test/tests/top/points.js
test/tests/top/subage.js
test/tests/top/time.js

top: Fix incorrect function names

---

src/bot/systems/top.ts
test/tests/top/followage.js
test/tests/top/subage.js

top: Add follower/subscriber checks

---

locales/cs/systems/polls.json
locales/en/systems/polls.json
src/bot/systems/polls.ts
src/panel/views/managers/polls.vue

polls: Add close message if closed by ui

---

index.d.ts
src/bot/systems/polls.ts
src/panel/views/managers/polls.vue

polls: Set dates as timestamp to avoid incorrect ordering

---

src/panel/views/managers/polls.vue

polls: Add bottom border to vote type select

---

tools/migrate.js

migrate: Add polls migration from dates to timestamps

---

src/bot/panel.js
src/panel/widgets/components/dashboard_remove.vue
src/panel/widgets/components/widget_create.vue
src/panel/widgets/dashboard.js
src/panel/widgets/dashboard.vue

dashboard: Fix issue with random chat reload

---

tools/database.js

tools: Fix error when mapping is empty

---

src/bot/databases/database.js
src/bot/databases/mongodb.js
tools/database.js

tools: Skip ObjectId objects in mongodb

---

tools/migrate.js

migrate: Remove lastTimeRemind from poll migration

---

src/bot/databases/mongodb.js
test/tests/top/subage.js

Fixes #1744
> Updated subage tests to test proper flatten

mongodb: Fix flattening on find()

---

src/bot/systems/moderation.js

moderation: Remove redundant condition check

---

public/pages/registry/customVariables/edit.html

ui: Set history as empty array if variable is empty

---

d.ts/goals.d.ts
src/bot/overlays/goals.ts
src/overlay/components/goals.vue
src/panel/views/registries/goalsEdit.vue

goals: add current types (followers, subscribers)

---

src/bot/widgets/eventlist.js
src/panel/components/holdButton.vue
src/panel/widgets/components/eventlist.vue

eventlist: add cleanup button to widget

---

src/panel/widgets/dashboard.vue

dashboard: fix error on creation of first widget

---

src/bot/systems/alias.js
src/bot/systems/customCommands.js

disabled alias/commands should not be shown in list

---

d.ts/index.d.ts
dist/js/components.js
locales/cs.json
locales/cs/ui.menu.json
locales/cs/ui/systems/userinfo.json
locales/en.json
locales/en/ui.menu.json
locales/en/ui/systems/userinfo.json
package.json
public/pages/systems.html
src/bot/api.js
src/bot/systems/polls.ts
src/bot/systems/userinfo.ts
src/bot/twitch.js
src/bot/users.js

userinfo: add new userinfo system (!me, !followage, etc)

---

src/bot/api.js
src/bot/cluster.js
src/bot/logging.js
src/bot/parser.js
src/bot/systems/moderation.js

moderation: fix whisper emote moderation

---

docs/_master/filters/all.md
src/bot/message.js

message: extend list.commands with permission

---

public/index.html
src/bot/api.js
src/bot/panel.js
src/bot/stats.js
src/bot/users.js

stats: add watchedTime stats

---

src/bot/tmi.js
src/bot/users.js

users: add ignore check to watchedTime update

---

src/bot/systems/userinfo.ts

userinfo: remove separator trimming

---

docs/_master/filters/all.md
docs/filters/all.md

docs: fix incorrect list command filter

---

src/bot/systems/userinfo.ts

userinfo: fix invalid message replace

---

src/bot/systems/top.ts
test/tests/top/tips.js

top: fix tips incorrect value

---

src/bot/_interface.js

interface: fix socket settings collection

---

src/panel/components/holdButton.vue
src/panel/components/panel.vue
src/panel/views/registries/goalsEdit.vue
src/panel/views/registries/goalsList.vue
src/panel/widgets/components/eventlist.vue

panel: update hold button to use slots

---

src/panel/components/panel.vue
src/panel/views/registries/goalsList.vue

panel: set css as scoped

---

package.json

package: remove terser from devDependencies

---

src/bot/tmi.js

tmi: show logs only on debug

---

src/bot/systems/bets.ts

bets: fix incorrect attributes to replace

---

src/bot/databases/nedb.js

nedb: fix errors not propagating correctly

---

d.ts/index.d.ts
package.json
src/bot/cluster.js
src/bot/databases/nedb.js
src/bot/systems/cooldown.js
src/bot/systems/moderation.js
src/bot/systems/polls.ts
src/bot/systems/userinfo.ts
test/helpers/messages.js
test/tests/cooldowns/check.js
test/tests/cooldowns/toggleEnabled.js
test/tests/cooldowns/toggleFollowers.js
test/tests/cooldowns/toggleModerators.js
test/tests/cooldowns/toggleOwners.js
test/tests/cooldowns/toggleSubscribers.js
test/tests/moderation/blacklist.js
test/tests/moderation/caps.js
test/tests/moderation/containsLink.js
test/tests/moderation/longMessage.js
test/tests/moderation/permitLink.js
test/tests/moderation/spam.js
test/tests/moderation/symbols.js

package: bump twitch-js to 2.0.0-beta.30

---

docs/_master/howto/write-own-system.md

docs: update write-own-system

---

locales/cs.json
locales/en.json

locale: missing subStreakShareEnabled

---

d.ts/index.d.ts
src/bot/cluster.js
src/bot/systems/cooldown.js
src/bot/systems/moderation.js
src/bot/systems/userinfo.ts

tmi: fix parsing of badges

---

src/bot/tmi.js

tmi: fix typo for streakMonths

---

public/index.html
public/pages/customcommands/edit.html

vue: remove development library

---

src/bot/overlays/eventlist.js

eventlist: simplify object generation

---

public/pages/viewers/edit.html
public/pages/viewers/list.html
src/bot/api.js
src/bot/cluster.js
src/bot/databases/nedb.js
src/bot/tmi.js
src/panel/views/registries/goalsEdit.vue

nedb: fix incorrect error logging

---

src/bot/commons.js
src/bot/tmi.js

tmi: fix is moderator checking

---

src/bot/api.js
src/bot/tmi.js

tmi: fix polling on mod check

---

src/bot/api.js

api: move intervals to function

---

CONTRIBUTING.md

chore: fix CONTRIBUTING lines order

---

src/bot/widgets/soundboard.ts

widgets: fix glob error on soundboard load

---

package.json
src/bot/configuration.js
src/bot/main.js
src/bot/message.js
src/bot/panel.js

chore: add commit instead of snapshot

---

package.json

package: 8.4.0-SNAPSHOT

---

src/bot/api.js

 api: add chatters check for getChannelChattersUnofficialAPI 

---

src/bot/api.js

api: add chatters check for getChannelChattersUnofficialAPI

---

src/panel/views/registries/goalsEdit.vue

goals: properly select goal on load/create

---

src/panel/components/panel.vue

panel: fix buttons not properly aligned

---

public/index.html

ui: add proper toFixed for numbers

---

src/bot/_interface.js

interface: skip saving of undefined keys

---

public/index.html

fix: set properly version notification as button

---

src/panel/widgets/components/raffles.vue

fix(raffles): set size of elements to correct values

---

.travis.yml
CONTRIBUTING.md
commitlint.config.js
package.json

Add precommit hooks to check commit format
Fixes #1847

chore: change commit guidelines

---

docs/_master/_sidebar.md
docs/_master/games/fightme.md
docs/_sidebar.md
docs/games/fightme.md

docs(fightme): add docs for !fightme game

---

docs/_master/_sidebar.md
docs/_master/games/gamble.md
docs/_sidebar.md
docs/games/gamble.md

docs(gamble): add docs for gamble game

---

.travis.yml

chore(travis): add linters to run on skip tests

---

src/bot/systems/alias.js

This is useful if custom variable is whole generated command

feat(alias): parse custom variables on aliases

---

docs/_master/_sidebar.md
docs/_master/howto/run-random-command.md

docs: add example for running random command in alias

---

locales/cs/ui.dialog.json
locales/en/ui.dialog.json
public/pages/registry/customVariables/edit.html

fix(ui): use $set for customVariables form errors

---

src/bot/tmi.js

fix: use correct subCumulativeMonths variable for subgift

---

docs/_master/howto/run-random-command.md
public/pages/registry/customVariables/edit.html
src/bot/customvariables.js

feat(cvars): add _current for current values

---

src/bot/users.js

fix(users): set correct id on remove id to delete correct user

---

src/bot/api.js

fix(api): remove additional socket emit

---

src/overlay/components/wheeloffortune.vue

fix(wof): import missing TweenLite library

---

docs/_master/commands/custom-commands.md

docs: add advanced example to custom commands filters

---

dist/js/components.js
locales/cs/ui/integrations/spotify.json
locales/en/ui/integrations/spotify.json
package.json
src/bot/_interface.js
src/bot/integrations/spotify.js
src/panel/components/holdButton.vue
src/panel/widgets/components/spotify.vue
src/panel/widgets/components/widget_create.vue
src/panel/widgets/dashboard.vue
src/panel/widgets/popout.vue

Widget will show current song, song requests, can enable/disable song
requests and continue of playlist
Also added two new settings:
- fetchCurrentSongWhenOffline: enable/disable song fetching if stream
is offline
- continueOnPlaylistAfterRequest: enable/disable continue on playlist after
song request
Fixes #1627

feat(spotify): add spotify widget

---

locales/cs.json
locales/en.json

fix(locale): add missing widget spotify locale

---

public/index.html

fix: remove incorrect difference arguments

---

src/bot/databases/interface.js
src/bot/databases/mongodb.js
src/bot/databases/nedb.js
test/tests/db/lookup.js

This will need second feat commit for mongodb to pass the tests
Fixes #1877

feat(nedb): add lookup to find() and findOne()

---

public/pages/viewers/list.html
src/bot/cluster.js
src/bot/databases/master.js
src/bot/users.js

fix(users): use lookup for find.viewers

---

docs/_master/README.md
docs/_master/_sidebar.md
docs/_master/commands/scrim.md
locales/cs.json
locales/cs/systems/scrim.json
locales/cs/ui.menu.json
locales/cs/ui/systems/scrim.json
locales/en.json
locales/en/systems/scrim.json
locales/en/ui.menu.json
locales/en/ui/systems/scrim.json
src/bot/commons.js
src/bot/expects.js
src/bot/systems/scrim.ts
test/helpers/db.js
test/helpers/messages.js
test/tests/scrim/workflow.js

feat(scrim): add scrim system

---

src/panel/widgets/components/part.vue

fix(widget): remove socket variable from part widget

---

src/bot/api.js

fix: save moderators correctly with id

---

test/helpers/db.js
test/helpers/messages.js
test/tests/polls/bits.js
test/tests/polls/normal.js
test/tests/polls/tips.js

test(polls): add wait time to be more robust

---

src/bot/api.js
src/bot/main.js
src/bot/workers.js

fix: start main() only if all workers are ready

---

docs/_master/install-and-upgrade.md

docs: remove LTS version from prerequisite

---

docs/_master/howto/write-own-system.md

docs: add locales for own system

---

src/bot/systems/customCommands.js

There is stlill slight possibility that messages will be out of order,
although it should happen only sporadically dependant on network
Fixes #1896

fix(commands): await for message to be sent

---

.travis.yml
package.json
test/tests/alias/add.js
tools/rerunTests.js

test: rerun only errored suites

---

src/bot/api.js
src/bot/message.js
src/bot/systems/raffles.js
src/bot/systems/songs.js
src/bot/tmi.js
src/bot/webhooks.js

fix: add parentheses to awaits in if

---

dist/js/components.js
public/pages/customcommands/edit.html
scss/custom.scss

fix(commands): add missing filters

---

dist/js/components.js

fix(ui): add margin and mouseleave to filters

---

locales/cs.json
locales/en.json
src/bot/games/duel.js
test/helpers/messages.js
test/tests/games/duel.js

 feat(duel): add bank command

---

src/bot/users.js
test/tests/users/ignore.js

fix(users): update whole ignorelist array to be retroactive

---

tools/rerunTests.js

fix(tools): rerun only unique suites

---

d.ts/goals.d.ts
locales/cs/ui/registry/goals.json
locales/en/ui/registry/goals.json
public/overlays.html
src/overlay/components/goals.vue
src/panel/views/registries/goalsEdit.vue

 fix(goals): add background bar color &  fix(overlays): set background color transparent

---

docs/_master/howto/write-own-system.md
src/bot/_interface.js

fix(interface): add simple function support for arrays

---

d.ts/goals.d.ts
locales/cs/ui/registry/goals.json
locales/en/ui/registry/goals.json
src/bot/overlays/goals.ts
src/overlay/components/goals.vue
src/panel/views/registries/goalsEdit.vue
src/panel/views/registries/goalsList.vue

feat(goals): add possibility to run goal endlessly

---

src/panel/components/button.vue
src/panel/views/registries/goalsList.vue

fix(goals): force shrink buttons on registry list

---

locales/cs.json
locales/cs/ui/core/users.json
locales/en.json
locales/en/ui/core/users.json
src/bot/commons.js
src/bot/customvariables.js
src/bot/events.js
src/bot/games/heist.js
src/bot/message.js
src/bot/systems/queue.js
src/bot/systems/scrim.ts
src/bot/systems/top.ts
src/bot/users.js

fix(users): move atUsername from legacy config to interface

---

docs/_master/commands/custom-commands.md
public/pages/customcommands/edit.html
src/bot/systems/customCommands.js

feat(commands): add $rank to filters

---

src/panel/views/registries/goalsEdit.vue

fix(ui): use proper locales for goals edit

---

docs/_master/_sidebar.md

docs: fix master sidebar top system link

---

Makefile
package.json
tools/release.js

feat(tools): add release tool

---

public/index.html
public/pages/apistats.html
src/bot/api.js
src/bot/panel.js

Also add some simple visualization for twitch set errors. It's simple change, would need to refactor when rewrited to Vue.js
Fixes #1715

fix(api): send correct data from errors

---

tools/release.js

release tool updates

---

dist/js/components.js
docs/_master/commands/custom-commands.md
locales/cs.json
locales/en.json
public/pages/customcommands/edit.html
public/pages/events.html
src/bot/commons.js
src/bot/events.js
src/bot/games/duel.js
src/bot/games/fightme.js
src/bot/games/roulette.js
src/bot/games/seppuku.js
src/bot/message.js
src/bot/parser.js
src/bot/systems/alias.js
src/bot/systems/customCommands.js
src/bot/systems/moderation.js
src/bot/tmi.js
test/tests/cooldowns/check.js
test/tests/games/fightme.js
test/tests/top/subage.js

I removed this object, doesn't seem to be comprehensive what this object might actually do, I think it was mainly used for check if user is mod etc. so I added several $is variables to filters and events
Fixes #1671

feat: remove $userObject, add $is filters

---

src/bot/integrations/spotify.js

fix(spotify): remove ambiguous error log

---

tools/release.js

 feat(tools): add build argument

---

src/bot/workers.js

fix(workers): remove core from path for interface update

---

public/pages/viewers/edit.html
public/pages/viewers/list.html
src/bot/expects.js
src/bot/systems/customCommands.js
src/bot/systems/points.js
src/bot/users.js
test/tests/points/get.js
test/tests/raffles/pick.js

fix: incorrect watched time and wrong redirect

---

locales/cs.json

fix(locales): add missing one-record-per-line locale

---

src/bot/commons.js
src/bot/message.js
test/tests/message/random.js

fix(message): filter ignored user from random filters

---

test/tests/message/random.js

test(random): remove .only

---

src/bot/parser.js
src/bot/systems/cooldown.js
test/tests/cooldowns/check.js

fix(cooldown): properly check cooldown of custom commands

---

test/helpers/messages.js
test/tests/games/duel.js
tools/rerunTests.js

test fixes

---

test/tests/polls/bits.js
test/tests/polls/normal.js
test/tests/polls/tips.js

This sometimes caused tests to fail (same user voted twice etc.)
Fixes #1945

test(polls): remove random numbers

---

src/bot/users.js

 fix(users): cleanup watched list on stream end

---

src/bot/users.js

fix(ui): set correct watched time

---

src/bot/api.js

fix(api): go through all subscribers

---

d.ts/index.d.ts
src/bot/events.js
src/bot/message.js
src/bot/systems/alias.js
src/bot/systems/bets.ts
src/bot/systems/commercial.js
src/bot/tmi.js
src/bot/widgets/cmdboard.ts
src/bot/workers.js
test/helpers/messages.js

fix(tmi): simplify message parse

---

src/bot/stats.js

fix(stats): add isNaN check

---

src/bot/panel.js
src/bot/stats.js

fix(stats): use correct class pointer

---

locales/cs/ui.registry.customvariables.json
locales/en/ui.registry.customvariables.json
public/pages/registry/customVariables/edit.html
public/pages/registry/customVariables/list.html
src/bot/customvariables.js
src/bot/message.js
src/bot/panel.js
src/bot/stats.js
test/helpers/db.js
test/helpers/messages.js
test/tests/message/cvars.js

feat(cvar): add permission options

---

src/bot/api.js
src/bot/logging.js
src/bot/message.js
src/bot/systems/points.js
src/bot/twitch.js
src/bot/users.js

 fix(users): add debug messages and force online usernames to be unique

---

src/bot/workers.js

fix(workers): restart worker on crash

---

.vscode/launch.json

chore(vscode): update launch.json

---

src/bot/cluster.js
src/bot/configuration.js
src/bot/expects.js
src/bot/main.js
src/bot/parser.js

feat(debug): add heap to $_debug command

---

src/bot/expects.js
test/tests/cooldowns/check.js

fix(expects): extend command regex for all non-whitespace

---

src/panel/widgets/components/queue.vue

fix(queue): set correct socket.emit for delete/clear

---

tools/release.js

fix(release): split build and docs branches

---

tools/release.js

fix(tools): building zip update

---

tools/release.js

fix(tools): add next build version

---

package.json
tools/release.js

Build 8.4.0

---

package.json

build: 8.5.0-SNAPSHOT

---

src/bot/widgets/soundboard.ts

fix(soundboard): update glob to be ts compliant

---

src/bot/games/duel.js
test/helpers/db.js

fix(duel): reset duel if anyone joined

---

src/bot/games/duel.js
src/bot/systems/alias.js
test/helpers/db.js
test/tests/alias/run.js

fix(alias): add missing skip to message parse

---

package.json

build: 8.4.1

---

tools/release.js

fix(release): split release tool to docs and build 

---

docs/_master/filters/all.md
test/tests/message/api.js

test: add api \n param test

---

src/bot/overlays/emotes.js

Also parse only proper emotes with word boundaries
e.g.
before: KappaLul => Kappa
after: KappaLul => null

fix(emotes): properly parse other partner emotes

---

src/bot/debug.ts
src/bot/logging.js
src/bot/workers.js

This will simplify creation of debug logging where needed.
Fixes #1966

feat(debug): add proper debug function

---

src/bot/_interface.js
src/bot/games/duel.js
src/bot/games/fightme.js
src/bot/games/gamble.js
src/bot/games/heist.js
src/bot/games/roulette.js
src/bot/games/wheelOfFortune.js
src/bot/oauth.js
src/bot/systems/bets.ts
src/bot/systems/cooldown.js
src/bot/systems/moderation.js
src/bot/systems/points.js
src/bot/systems/queue.js
src/bot/systems/quotes.js
src/bot/systems/raffles.js
src/bot/systems/songs.js

fix: remove await from settings getters

---

src/bot/systems/raffles.js

fix(raffles): use lastAnnounce time from cache only

---

src/bot/_interface.js
src/bot/workers.js

fix(interface): trigger change on correct class independent on filename

---

src/bot/api.js
src/bot/users.js

fix(api): add checks for id in users collection

---

src/bot/overlays/emotes.js

fix(emotes): fix emmote typo

---

src/bot/_interface.js

fix(interface): add better message if system doesn't start

---

docs/_master/commands/scrim.md
src/bot/commons.js
src/bot/expects.js
src/bot/systems/scrim.ts
test/helpers/messages.js
test/tests/scrim/workflow.js

Added toggle -c which will disable sending match ids

feat(scrim): add cooldown only scrim

---

src/panel/components/button.vue
src/panel/components/holdButton.vue
src/panel/components/panel.vue
src/panel/index.ts
src/panel/views/managers/polls.vue
src/panel/views/registries/goalsEdit.vue
src/panel/views/registries/goalsList.vue
src/panel/widgets/components/bets.vue
src/panel/widgets/components/chat.vue
src/panel/widgets/components/cmdboard.vue
src/panel/widgets/components/commercial.vue
src/panel/widgets/components/customvariables.vue
src/panel/widgets/components/dashboard_remove.vue
src/panel/widgets/components/eventlist.vue
src/panel/widgets/components/join.vue
src/panel/widgets/components/part.vue
src/panel/widgets/components/queue.vue
src/panel/widgets/components/raffles.vue
src/panel/widgets/components/soundboard.vue
src/panel/widgets/components/spotify.vue
src/panel/widgets/components/twitch.vue
src/panel/widgets/components/twitter.vue
src/panel/widgets/components/widget_create.vue
src/panel/widgets/components/ytplayer.vue
src/panel/widgets/dashboard.vue

fix(ui): move all font-awesome imports to index.ts

---

package.json

chore: update to 9.0.0-SNAPSHOT

---

tools/release.js

fix(tools): reinstall husky hook

---

public/pages/registry/customVariables/edit.html

fix(ui): properly order custom variable history

---

public/pages/registry/customVariables/edit.html

fix(ui): cvar options are correctly selectable

---

src/bot/integrations/spotify.js
src/bot/parser.js
tools/migrate.js

fix(parser): load custom permissions from new collection 

---

dist/js/components.js

fix(ui): order permissions by its weight

---

src/bot/parser.js
src/bot/permissions.ts
test/helpers/messages.js
test/tests/permissions/check.js

fix(permissions): properly skip disabled command

---

package.json
test/tests/message/api.js

test(message): make message.api test offline

---

package.json
src/bot/commons.js
src/bot/databases/mongodb.js
src/bot/databases/nedb.js
src/bot/events.js
src/bot/panel.js
src/bot/translate.js
test/tests/commons/flatten.js
tools/migrate.js

 chore: remove flat dependency 

---

locales/cs.json
locales/en.json
src/bot/events.js
src/bot/tmi.js
src/panel/widgets/components/eventlist.vue

fix(tmi): remove subsStreak guessing

---

src/bot/databases/master.js
src/bot/workers.js

fix(workers): remove legacy cluster code

---

src/bot/databases/master.js

fix(db): revert master connect()

---

src/bot/users.js

fix(users): update username instead of id

---

src/bot/general.ts

feat(general): load locales list dynamically

---

src/bot/commons.js
test/tests/commons/flatten.js

fix(commons): update unflatten behavior on arrays

---

src/bot/api.js
src/bot/commons.js

also deleted setModerators as it didn't work as intended
Fixes #2052

fix: better check on isModerator

---

src/panel/components/panel.vue

fix(ui): remove second button from panel

---

src/bot/commons.ts

fix(commons): initialize default class on autoload

---

src/bot/_interface.ts
src/bot/customvariables.js
src/bot/databases/interface.js
src/bot/databases/master.js
src/bot/databases/mongodb.js
src/bot/databases/nedb.js
src/bot/overlays/emotes.js
src/bot/overlays/goals.ts
src/bot/systems/polls.ts
src/bot/workers.ts

To be able to set several keys

fix(db): update index() for array use

---

.github/semantic.yml
.travis.yml
commitlint.config.js
package.json
tools/release.js

ci: replace commitlint with semantic PR checks

---

src/bot/tmi.js

fix(commons): import isBot after rework of commons

---

.travis.yml
.vscode/launch.json
src/bot/tmi.js

chore: add DEBUG=tmi when debugging

---

src/bot/databases/mongodb.js

fix(mongodb): index wait for connection lose arguments

---

src/bot/workers.ts

fix(workers): better error message on interface call

---

src/bot/users.js

fix(users):  add missing commons import

---

dist/js/components.js

fix(ui): set -moz-fit-content for textAreaWithTags

---

src/bot/tmi.js

fix(tmi): change to commons.getLocalizedName

---

src/bot/api.js

feat(api): add check if bot is a mod

---

src/bot/parser.js

fix(parser): add missing import

---

public/pages/registry/customVariables/list.html
src/bot/customvariables.js

fix(cvars): use timestamp instead of Date object

---

scss/custom.scss
src/panel/components/button.vue
src/panel/components/holdButton.vue
src/panel/components/panel.vue
src/panel/components/stateButton.vue
src/panel/views/managers/events/edit.vue
src/panel/views/managers/events/list.vue
src/panel/views/managers/polls.vue
src/panel/views/registries/goalsEdit.vue
src/panel/views/registries/goalsList.vue
src/panel/views/settings/permissions.vue

refactor(ui): use slots for panel component

---

d.ts/index.d.ts
src/bot/api.js
src/bot/events.ts
src/bot/oauth.js
src/bot/overlays/emotes.js
src/bot/systems/commercial.js
src/bot/systems/highlights.js
src/bot/systems/userinfo.ts
src/bot/users.js
src/bot/webhooks.js
test/tests/api/getLatest100Followers.js
test/tests/webhooks/follower.js

fix(followage): load data from api each call

---

src/bot/api.js

fix(api): isFollowerUpdate should handle sender object

---

src/bot/commons.ts

fix(commons): sort attributes by length desc

---

docs/_master/filters/all.md
src/bot/message.js

feat(message): add (list.price) filter

---

src/panel/index.ts

fix(ui): fix import of incorrect icon

---

src/overlay/components/eventlist.vue

fix(overlays): eventlist should have correct classes

---

src/bot/parser.js

fix(parser): add missing tmi library to populateList

---

src/bot/api.js

fix(api): remove retries and don't disable subscribers api

---

src/panel/components/holdButton.vue
src/panel/widgets/components/spotify.vue

feat(spotify): add cleanup button for song requests

---

src/bot/tmi.js

feat(tmi): parse cumulative months from badgeInfo

---

locales/cs.json
locales/en.json
src/bot/systems/userinfo.ts

feat(subage): add cumulative months to command response

---

docs/_master/filters/all.md
src/bot/message.js
test/tests/message/touser.js

feat(filter): add $touser filter

---

locales/cs.json
locales/en.json
public/pages/customcommands/edit.html

fix(commands): add missing touser filter parameter

---

Makefile

build: remove tslint from all

---

src/bot/events.ts

fix(events): remove redundant log

---

src/bot/events.ts

fix(events): use timestamp for everyXMinutesOfStream

---

locales/cs.json
locales/en.json
src/panel/views/managers/events/list.vue

fix(locales): add missing events locale

---

package.json

build: add changelog generator

---

public/pages/registry/customVariables/edit.html
src/bot/customvariables.js

feat(cvars): add async user() to get simplified user object

---

src/bot/integrations/spotify.js
src/bot/systems/top.ts
test/tests/moderation/blacklist.js
test/tests/moderation/containsLink.js
test/tests/moderation/spam.js
test/tests/moderation/whitelist.js

fix: several await removals

---

src/bot/workers.ts
src/panel/widgets/components/cmdboard.vue

fix(workers): remove widgets from workers interface update

---

public/pages/core.html
public/pages/integrations.html
public/pages/overlays.html
public/pages/systems.html

fix(ui): set correct position for menu if top is sticky

---

public/pages/registry/customVariables/edit.html
src/bot/customvariables.js

feat(cvars): add stream variable with current stream values

---

locales/cs.json
locales/en.json
public/index.html
src/bot/api.js
src/bot/oauth.js
src/bot/panel.js

feat(ui): show subscribers/bit error if not affiliate or partner

---

src/bot/api.js

fix(api): set correct variable path

---

src/bot/api.js

fix(api): update opts on failed state

---

package.json

build: 9.1.0-SNAPSHOT

---

public/pages/core.html
public/pages/games.html
public/pages/integrations.html
public/pages/overlays.html
public/pages/systems.html

fix(ui): set correct z-index for settings menu

---

tools/release.js

fix(release): remove redundant getReleaseVersion call

---

dist/js/components.js
public/index.html

fix(ui): remove http only uuid cdn

---

Makefile

build: use yarn instead of npm to install dependencies

---

.travis.yml

test(travis): add node v12

---

.gitignore

chore(gitignore): add yarn.lock

---

.babelrc
docs/_master/howto/write-own-system.md
package.json
src/bot/_interface.ts
src/bot/decorators.ts
src/bot/systems/top.ts

refactor(decorators): add @command, @default_permission, @helper

---

src/bot/tmi.js

fix(tmi): message should properly delete on timeout

---

docs/_master/filters/all.md
docs/filters/all.md
src/bot/systems/customCommands.js
test/tests/commands/count_filter.js

fix(commands): $count will return correct usage count

---

src/bot/tmi.js

fix(tmi): show proper error messages if tmi is not connected

---

public/index.html

 fix(ui): update format of commit link

---

docs/_master/filters/all.md
src/bot/systems/customCommands.js
test/tests/commands/count_filter.js

feat(command): $count can return count of different command

---

public/index.html

fix(ui): remove incorrect italic

---

locales/cs/ui/systems/credits.json
locales/en/ui/systems/credits.json

fix(ui): typo in locale aggregate => aggregated

---

test/general.js
test/mocks.js
test/tests/api/getLatest100Followers.js
test/tests/message/api.js
test/tests/message/random.js

test(api): add axios mock

---

public/index.html

fix(ui): sort menu alphabetically

---

Makefile

build: remove cleanup of lockfiles

---

src/bot/oauth.js

feat(oauth): log error if bot and broadcaster is same

---

src/bot/twitch.js

fix(twitch): missed default permissions for commands

---

src/bot/main.js

feat(startup): add check for node version

---

locales/cs/ui.registry.customvariables.json
locales/en/ui.registry.customvariables.json
public/pages/registry/customVariables/edit.html
public/pages/registry/customVariables/list.html

feat(cvars): more detailed intervals to run eval

---

src/bot/_interface.ts
src/bot/decorators.ts
src/bot/integrations/phillipsHue.js

fix: various fixes

---

docs/_master/commands/custom-commands.md
src/bot/events.ts
src/bot/systems/customCommands.js

Custom variables in filters

---

.travis.yml

chore: run tslint independently

---

src/bot/overlays/alerts.ts

fix(alerts): set correct command

---

docs/_master/howto/write-own-system.md

docs(import): add missed parser import in write-own-system

---

src/bot/_interface.ts
src/bot/decorators.ts
src/bot/parser.js
src/bot/systems/cooldown.js
src/bot/systems/price.js

This will help with restoring cooldowns and prices when some parser after failed
Fixes #2198

feat(rollback): add rollback for parsers

---

locales/cs/ui.systems.cooldown.json
locales/en/ui.systems.cooldown.json
src/bot/systems/cooldown.js

I'm not sure about CS langs, sorry :)

feat(cooldown): add notify in chat cooldown information

---

docs/_master/commands/top.md
locales/cs/systems/top.json
locales/en/systems/top.json
src/bot/systems/top.ts
test/tests/top/submonths.js

feat(top): add submonths command

---

src/panel/components/textareaWithTags.vue

fix(ui): import bootstrap components

---

src/bot/_interface.ts

refactor(interface): add interface.retroactive debug

---

src/panel/index.ts

fix(ui): use solid faComments icon

---

src/bot/overlays/emotes.js

feat(emotes): save emotes to cache on usage

---

src/bot/overlays/emotes.js

Also we don't load full cache of subscribers anymore.
Fixes #2135

fix(emotes): use v4 twitchemotes api

---

src/bot/api.js
src/bot/oauth.js
src/bot/overlays/emotes.js

fix: several oauth fixes

---

src/bot/overlays/emotes.js

fix(emotes): remove hardcoded channel

---

src/bot/systems/points.js
test/tests/events/tip.js

fix(points): add getIdByName when call from event

---

docs/_master/howto/write-own-system.md
src/bot/parser.js
src/bot/systems/alias.js
src/bot/systems/customCommands.js
test/tests/commands/add.js

feat(rollback): add rollback for alias, commands and permissions

---

src/bot/tmi.js

fix(tmi): remove all cheermotes from message

---

src/bot/systems/customCommands.js

fix(commands): return proper $count of command

---

src/bot/systems/customCommands.js

fix(commands): properly stopIfExecuted

---

public/pages/cooldown/list.html

feat(cooldown): add quiet toggler for UI list

---

test/tests/currency/rates.js

test(rates): add rates tests

---

docs/_master/commands/overlays.md

docs: add missing volume in !alert

---

src/bot/currency.js

refactor(currency): add currency list on currency exchange error

---

src/bot/currency.js

fix(currency): join keys correctly

---

src/bot/api.js
src/bot/commons.ts

fix(api): use isIgnored on join/part events

---

src/bot/_interface.ts

fix(interface): expose retroactive stacktrace

---

dist/js/commons.js
public/public/quotes.html

fix(quotes): public page should correctly be translated and metrics socket ignored

---

public/public/quotes.html

fix(quotes): public list should be correctly populated

---

src/bot/expects.js

fix(users): properly delete tips and bits from ui

---

test/tests/currency/rates.js

test(rates): reduce verbosity of rates

---

public/pages/customcommands/edit.html

fix(commands): set lowest permission on response creation

---

src/panel/views/managers/polls.vue

fix(polls): set correct moment locale

---

src/bot/_interface.ts
src/bot/commons.ts

fix(interface): settings with category should be properly updated

---

docs/_master/howto/write-own-system.md

docs: add info on disabling system by default

---

src/bot/widgets/chat.ts
src/panel/widgets/components/bets.vue
src/panel/widgets/components/cmdboard.vue
src/panel/widgets/components/queue.vue
src/panel/widgets/components/raffles.vue
src/panel/widgets/components/spotify.vue

fix(widget): align widgets with new settings

---

locales/cs/ui.systems.songs.json
locales/en/ui.systems.songs.json
src/bot/systems/songs.ts

feat(songs): add toggle for dynamic volume

---

src/bot/oauth.ts

fix(oauth): set broadcasterType as null

---

src/bot/api.js
src/bot/systems/userinfo.ts

fix(userinfo): correctly fetch data from api on !followage

---

src/bot/currency.ts
src/bot/decorators.ts

fix(currency): shared rates to be able to exchange on workers

---

src/bot/integrations/donationalerts.ts
src/bot/integrations/phillipsHue.ts
src/bot/integrations/spotify.ts
src/bot/integrations/streamlabs.ts
src/bot/integrations/twitter.ts
tools/migrate.js

fix(integrations): start properly integrations on startup

---

src/bot/customvariables.js

fix(customvariables): return proper is.online on user()

---

public/pages/registry/customVariables/edit.html

fix(customvariables): properly select initial value on eval select

---

src/bot/systems/customCommands.ts

fix(commands): properly save new responses

---

src/bot/_interface.ts
src/bot/workers.ts

fix(interface): emit should work correctly on worker

---

src/bot/systems/userinfo.ts

fix(userinfo): me should return correct tip values

---

src/bot/systems/top.ts

fix(top): top tips should return correct values

---

src/bot/oauth.ts

Also waiting will be gradually longer
Fixes #2279

fix(oauth): channelId loop should work correctly

---

src/bot/workers.ts

fix(workers): add retry for workers emit

---

src/bot/decorators.ts

fix(decorators): set variable value correctly if false

---

src/bot/_interface.ts

fix(interface): properly save enable state

---

src/bot/_interface.ts
src/bot/workers.ts

fix(interface): share command changes main<->workers

---

src/bot/users.js

fix(users): correctly save new tips

---

public/pages/alias/list.html

fix(alias): show correct permissions dropdown in list view

---

test/tests/keywords/run.js

test(keywords): add case insensitive test

---

d.ts/index.d.ts
src/bot/message.js
src/bot/systems/keywords.ts
src/bot/systems/polls.ts

We will be handling full sender object everytime
Fixes #2294

feat(message): use sender attribute lossless on (!#) and (!!#)

---

d.ts/index.d.ts
locales/cs/ui.menu.json
locales/cs/ui/stats/commandcount.json
locales/en/ui.menu.json
locales/en/ui/stats/commandcount.json
npm-shrinkwrap.json
package.json
public/index.html
src/bot/_interface.ts
src/bot/cluster.js
src/bot/helpers/commands/count.ts
src/bot/main.js
src/bot/message.js
src/bot/parser.js
src/bot/stats/_interface.ts
src/bot/stats/commandcount.ts
src/bot/systems/customCommands.ts
src/panel/index.ts
src/panel/views/loggers/commandcount.vue
test/tests/commands/count_filter.js
yarn.lock

feat(stats): add command count

---

locales/cs.json
locales/en.json
public/pages/viewers/list.html

fix(viewers): show correct locale

---

tools/migrate.js

fix(migrate): add missing migrations

---

src/bot/systems/alias.ts

fix(alias): count alias commands to stats

---

src/bot/_interface.ts

fix(interface): send command change when set as default value

---

src/bot/api.js
src/bot/main.js

We should move stats.js to another file, but this will work as
workaround for now
Fixes #2308

fix(api): use correct stats file for save

---

public/pages/viewers/list.html

fix(viewers): properly show and sort messages count

---

src/bot/systems/alias.ts

fix(alias): save correct alias command to stats

---

npm-shrinkwrap.json
package.json
src/panel/views/loggers/commandcount.vue
webpack.config.js
yarn.lock

feat(stats): add date interval selection 

---

src/bot/systems/keywords.ts

fix(keywords): $sender should have correct name

---

.travis.yml

ci(travis): remove osx from tests

---

locales/en/ui.menu.json

fix(locale): add proper en locale for commandcount

---

public/pages/customcommands/list.html

fix(ui): search in custom commands should search through responses correctly

---

package.json

build: 9.2.0-SNAPSHOT

---

src/bot/api.js

fix(api): show affiliate/sub error only once

---

d.ts/index.d.ts
locales/cs/systems/howlongtobeat.json
locales/cs/ui.menu.json
locales/en/systems/howlongtobeat.json
locales/en/ui.menu.json
npm-shrinkwrap.json
package.json
src/bot/systems/howlongtobeat.ts
src/panel/index.ts
src/panel/views/managers/hltb.vue
yarn.lock

feat(hltb): system for tracking game time

---

src/bot/api.js
src/bot/decorators/on.ts

feat(decorators): add onStreamStart decorator

---

src/bot/systems/howlongtobeat.ts

fix(hltb): do not search for game if twitch category is empty

---

public/pages/price/list.html

fix(ui): search for price commands should return correct items

---

public/pages/registry/customVariables/edit.html
src/bot/customvariables.js

fix(cvars): force sender to be object

---

src/bot/decorators/on.ts
src/bot/tmi.js

onJoinChannel, onReconnectChannel, onPartChannel
Fixes #2300

refactor(decorators): add channel events

---

locales/cs.json
locales/en.json
src/bot/systems/userinfo.ts

feat(userinfo): add bits to !me

---

scss/custom.scss
scss/themes/dark.scss
scss/themes/light.scss
src/panel/index.ts

fix(ui): revert changes done by vue-bootstrap

---

src/panel/widgets/components/ytplayer.vue

fix(ui): YT player play next song on end

---

src/bot/parser.js

fix(parser): unset opts if its permission error

---

src/panel/views/loggers/commandcount.vue

fix(commandcount): change calendar behavior to two inputs

---

package.json

build: 9.3.0-SNAPSHOT

---

src/bot/panel.js
src/panel/others/changegamedlg.vue

fix(ui): cached tags should be sent on demand

---

locales/cs/ui.menu.json
locales/cs/ui/systems/howlongtobeat.json
locales/en/ui/systems/howlongtobeat.json
src/bot/systems/howlongtobeat.ts
src/panel/views/managers/hltb.vue

fix(locale): update missing howlongtobeat locale

---

src/bot/systems/points.ts
test/tests/points/set.js

fix(points): !points set should not add points but set

---

locales/en/ui.menu.json

fix(locale): add missing howlongtobeat en locale

---

src/bot/currency.ts
src/bot/users.js

fix(ui): tips for viewers should be correctly calculated

---

public/pages/viewers/edit.html
src/bot/systems/userinfo.ts
src/bot/users.js

fix(users): return bits correctly
